### ISSUE TITLE
Login hang after logging out in LC dimension

### ISSUE THREAD

**Issue by Arctic-Circuits** [McJty/LostCities#114]
We have two accounts on two different computers that can no longer log into our server after they logged out while being in the Lost Cities dimension. The client seems to hang while logging in. However, I can see and interact with their character on the server.  We're running the ftb revelation 1.5 mod pack with some additional mods and lostcities-1.12-2.0.0. I've tried killing the character to change the location via spawn, but it hasn't fixed the issue. Neither did teleporting the character. Any recommendations?

**Comment by josephcsible** [comment]
If you have RFTools, can you build a matter transmitter under them to teleport them back to the Overworld? Also, can you post logs from both the client and server from when they try to log in?

**Comment by Arctic-Circuits** [comment]
We recovered the player accounts by editing the location in the dat file. I've attached a shortened client log. There's a severe error message in there about dimension 111. The exception loops (1.4M lines). 
[shorter client log.txt](https://github.com/McJty/LostCities/files/1873620/shorter.client.log.txt)
There were no messages on the server after the player logged in: no errors, no disconnect, no timeout.

**Comment by josephcsible** [comment]
This looks like the relevant bit:
```
[19:31:59] [main/FATAL]: Error executing task
java.util.concurrent.ExecutionException: java.lang.IllegalArgumentException: Could not get provider type for dimension 111, does not exist
	at java.util.concurrent.FutureTask.report(Unknown Source) ~[?:1.8.0_161]
	at java.util.concurrent.FutureTask.get(Unknown Source) ~[?:1.8.0_161]
	at net.minecraft.util.Util.func_181617_a(SourceFile:47) [h.class:?]
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1086) [bib.class:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:397) [bib.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:123) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_161]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_161]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_161]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_161]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
Caused by: java.lang.IllegalArgumentException: Could not get provider type for dimension 111, does not exist
	at net.minecraftforge.common.DimensionManager.getProviderType(DimensionManager.java:146) ~[DimensionManager.class:?]
	at net.minecraftforge.common.DimensionManager.createProviderFor(DimensionManager.java:296) ~[DimensionManager.class:?]
	at net.minecraft.client.multiplayer.WorldClient.<init>(WorldClient.java:63) ~[bsb.class:?]
	at net.minecraft.client.network.NetHandlerPlayClient.func_147282_a(NetHandlerPlayClient.java:298) ~[brz.class:?]
	at net.minecraft.network.play.server.SPacketJoinGame.func_148833_a(SourceFile:76) ~[jh.class:?]
	at net.minecraft.network.play.server.SPacketJoinGame.func_148833_a(SourceFile:13) ~[jh.class:?]
	at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) ~[hv$1.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) ~[?:1.8.0_161]
	at java.util.concurrent.FutureTask.run(Unknown Source) ~[?:1.8.0_161]
	at net.minecraft.util.Util.func_181617_a(SourceFile:46) ~[h.class:?]
	... 9 more
```
