### ISSUE TITLE
Crash when removing parks from library.json

### ISSUE THREAD

**Issue by resinate** [McJty/LostCities#117]
at mcjty.lostcities.dimensions.world.LostCitiesTerrainGenerator.generatePart(LostCitiesTerrainGenerator.java:1821)
	at mcjty.lostcities.dimensions.world.LostCitiesTerrainGenerator.generateStreet(LostCitiesTerrainGenerator.java:1512)
	at mcjty.lostcities.dimensions.world.LostCitiesTerrainGenerator.doCityChunk(LostCitiesTerrainGenerator.java:792)
	at mcjty.lostcities.dimensions.world.LostCitiesTerrainGenerator.generate(LostCitiesTerrainGenerator.java:223)
	at mcjty.lostcities.dimensions.world.LostCityChunkGenerator.func_185932_a(LostCityChunkGenerator.java:205)

**Comment by McJty** [comment]
I need more info.  What did you change exactly?

**Comment by resinate** [comment]
under library.json i removed this 
    "parkblocks": {
      "elevation": "x"
    },
also does same when i remove this too
    "parks": [
      {
        "factor": 0.1,
        "park": "park_trees"
      }
    ],

this is what happens with park is set to 0, it spawns this 16x16 grass square. when i edit the park it spawns the park on top of this pad. i wanna get rid of this grass pad.
https://cdn.discordapp.com/attachments/427058248781135873/430845487961079818/unknown.png
and heres another bug where gardens spawn 1 block higher than it should
https://cdn.discordapp.com/attachments/427058248781135873/430846096055468042/unknown.png

**Comment by josephcsible** [comment]
Can you paste the full crash report rather than just that tiny piece of the stack trace?

**Comment by resinate** [comment]
https://pastebin.com/B9FWziLx

**Comment by McJty** [comment]
The elevation thing you cannot remove. That's not optional. Why do you want to remove that? That doesn't generate grass. You should be able to just remove the parks however

**Comment by resinate** [comment]
on ur end how do u remove parks normally?

**Comment by McJty** [comment]
Like you did

**Comment by Shane2482** [comment]
I am having a similar prob however i can get MC to load its just when i try to generate a world it hangs on the building terrain screen and its not just the parks any thing i try to remove causes this.
As well as removing all the parks iv even tried to remove the entire park section.
"parks": [     
    ], 
or
"fountains": [
    ], 
Edit: I missed the , in the fountains so that works but parks still don't work.
