### ISSUE TITLE
[Documentation request] Information regarding the commands in lost cities

### ISSUE THREAD

**Issue by wormzjl** [McJty/LostCities#130]
Specifically the 3 following commands:
/lc_buildpart
/lc_exportbuilding
/lc_exportpart

Tried to use the lc_exportbuilding command but it gives me the following error, so I guess there are some tricks with it...

`[12:09:22] [Server thread/INFO] [STDERR]: [mcjty.lostcities.commands.CommandExportBuilding:func_184881_a:129]: java.lang.ArrayIndexOutOfBoundsException: 1
[12:09:22] [Server thread/INFO] [STDERR]: [mcjty.lostcities.commands.CommandExportBuilding:func_184881_a:129]: 	at mcjty.lostcities.commands.CommandExportBuilding.func_184881_a(CommandExportBuilding.java:51)
[12:09:22] [Server thread/INFO] [STDERR]: [mcjty.lostcities.commands.CommandExportBuilding:func_184881_a:129]: 	at net.minecraft.command.CommandHandler.func_175786_a(CommandHandler.java:119)
[12:09:22] [Server thread/INFO] [STDERR]: [mcjty.lostcities.commands.CommandExportBuilding:func_184881_a:129]: 	at net.minecraft.command.CommandHandler.func_71556_a(CommandHandler.java:91)
[12:09:22] [Server thread/INFO] [STDERR]: [mcjty.lostcities.commands.CommandExportBuilding:func_184881_a:129]: 	at net.minecraft.network.NetHandlerPlayServer.func_147361_d(NetHandlerPlayServer.java:958)
[12:09:22] [Server thread/INFO] [STDERR]: [mcjty.lostcities.commands.CommandExportBuilding:func_184881_a:129]: 	at net.minecraft.network.NetHandlerPlayServer.func_147354_a(NetHandlerPlayServer.java:937)
[12:09:22] [Server thread/INFO] [STDERR]: [mcjty.lostcities.commands.CommandExportBuilding:func_184881_a:129]: 	at net.minecraft.network.play.client.CPacketChatMessage.func_148833_a(SourceFile:37)
[12:09:22] [Server thread/INFO] [STDERR]: [mcjty.lostcities.commands.CommandExportBuilding:func_184881_a:129]: 	at net.minecraft.network.play.client.CPacketChatMessage.func_148833_a(SourceFile:9)
[12:09:22] [Server thread/INFO] [STDERR]: [mcjty.lostcities.commands.CommandExportBuilding:func_184881_a:129]: 	at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13)
[12:09:22] [Server thread/INFO] [STDERR]: [mcjty.lostcities.commands.CommandExportBuilding:func_184881_a:129]: 	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
[12:09:22] [Server thread/INFO] [STDERR]: [mcjty.lostcities.commands.CommandExportBuilding:func_184881_a:129]: 	at java.util.concurrent.FutureTask.run(Unknown Source)
[12:09:22] [Server thread/INFO] [STDERR]: [mcjty.lostcities.commands.CommandExportBuilding:func_184881_a:129]: 	at net.minecraft.util.Util.func_181617_a(SourceFile:46)
[12:09:22] [Server thread/INFO] [STDERR]: [mcjty.lostcities.commands.CommandExportBuilding:func_184881_a:129]: 	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:723)
[12:09:22] [Server thread/INFO] [STDERR]: [mcjty.lostcities.commands.CommandExportBuilding:func_184881_a:129]: 	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
[12:09:22] [Server thread/INFO] [STDERR]: [mcjty.lostcities.commands.CommandExportBuilding:func_184881_a:129]: 	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:185)
[12:09:22] [Server thread/INFO] [STDERR]: [mcjty.lostcities.commands.CommandExportBuilding:func_184881_a:129]: 	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
[12:09:22] [Server thread/INFO] [STDERR]: [mcjty.lostcities.commands.CommandExportBuilding:func_184881_a:129]: 	at java.lang.Thread.run(Unknown Source)`

**Comment by wormzjl** [comment]
nvm -.-
