### ISSUE TITLE
Client crash on getHorizon when using Mining Dimension in ATM3 pack

### ISSUE THREAD

**Issue by JheregJAB** [McJty/LostCities#134]
I'm using a custom lost cities profile based on the biosphere config for my overworld generation.

After updating my modpack, ATM3 (and probably changing forge versions), no one can access the mining dimension any more, and the crash log indicates a crash in lost cities code.

the error:
java.lang.NullPointerException: Unexpected error
    at mcjty.lostcities.dimensions.world.LostWorldTypeBOP.getHorizon(LostWorldTypeBOP.java:34)
    at net.minecraft.world.WorldProvider.getHorizon(WorldProvider.java:563)
    at net.minecraft.world.World.func_72919_O(World.java:3766)
    at net.minecraft.client.renderer.RenderGlobal.func_174976_a(RenderGlobal.java:1426)
    at net.minecraft.client.renderer.EntityRenderer.func_175068_a(EntityRenderer.java:1296)
    at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1259)
    at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1062)
    at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1117)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:397)
    at net.minecraft.client.main.Main.main(SourceFile:123)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

Full crash report:
https://pastebin.com/dL78Kp7R

Is there a way to fix this?

Why is a totally different dimension still using Lost Cities methods?

**Comment by McJty** [comment]
I think I know what's wrong. I'll fix this today

**Comment by McJty** [comment]
Fixed next release (soon)

**Comment by JheregJAB** [comment]
Thank you for being prompt, looking forward to testing the fix!

**Comment by JheregJAB** [comment]
manually upgraded my server and client to the new version, and can confirm that the crash has been fixed.

Thanks again for the quick turnaround!
