### ISSUE TITLE
Sponge server without Lost Cities dim

### ISSUE THREAD

**Issue by Vitali8** [McJty/LostCities#145]
When the server is starting, the Lost City dimensions are not creating, instead, a message appears in the console:
```
[23:16:59] [Server thread/INFO] [STDERR]: [org.spongepowered.common.world.WorldManager:getWorldFolder:1438]: java.lang.NullPointerException
[23:16:59] [Server thread/INFO] [STDERR]: [org.spongepowered.common.world.WorldManager:getWorldFolder:1438]: 	at mcjty.lostcities.dimensions.world.LostWorldProvider.getSaveFolder(LostWorldProvider.java:28)
[23:16:59] [Server thread/INFO] [STDERR]: [org.spongepowered.common.world.WorldManager:getWorldFolder:1438]: 	at org.spongepowered.common.world.WorldManager.getWorldFolder(WorldManager.java:1434)
[23:16:59] [Server thread/INFO] [STDERR]: [org.spongepowered.common.world.WorldManager:getWorldFolder:1438]: 	at org.spongepowered.common.world.WorldManager.loadAllWorlds(WorldManager.java:674)
[23:16:59] [Server thread/INFO] [STDERR]: [org.spongepowered.common.world.WorldManager:getWorldFolder:1438]: 	at net.minecraft.server.MinecraftServer.func_71247_a(MinecraftServer.java:3541)
[23:16:59] [Server thread/INFO] [STDERR]: [org.spongepowered.common.world.WorldManager:getWorldFolder:1438]: 	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:270)
[23:16:59] [Server thread/INFO] [STDERR]: [org.spongepowered.common.world.WorldManager:getWorldFolder:1438]: 	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:486)
[23:16:59] [Server thread/INFO] [STDERR]: [org.spongepowered.common.world.WorldManager:getWorldFolder:1438]: 	at java.lang.Thread.run(Thread.java:748)
[23:16:59] [Server thread/ERROR] [Sponge]: An attempt was made to load a world with dimension id [111] that has no registered world folder!
```
Forge -1.12.2-14.23.4.2705;
SpongeForge -1.12.2-2705-7.1.0-BETA-3221;
Lost Cities -1.12-2.0.9.

**Comment by clienthax** [comment]
dupe of https://github.com/McJtyMods/LostCities/issues/142
