### ISSUE TITLE
Potential issue with AromaBackup

### ISSUE THREAD

**Issue by ranger135xp** [McJty/LostCities#174]
I noticed that a backup folder did not exist on my server.
I found that running a manual backup generates an error, but does not prompt a crash.
This effectively renders backups useless as they never occur.

```
[java.lang.ThreadGroup:uncaughtException:1052]: java.lang.RuntimeException: java.util.concurrent.ExecutionException: java.lang.NullPointerException
[java.lang.ThreadGroup:uncaughtException:1052]: at com.google.common.base.Throwables.propagate(Throwables.java:240)
[java.lang.ThreadGroup:uncaughtException:1052]: at aroma1997.backup.mc.ThreadBackup.executeOnServerThreadAndWait(ThreadBackup.java:287)
[java.lang.ThreadGroup:uncaughtException:1052]: at aroma1997.backup.mc.ThreadBackup.makeBackup(ThreadBackup.java:126)
[java.lang.ThreadGroup:uncaughtException:1052]: at aroma1997.backup.mc.ThreadBackup.run(ThreadBackup.java:102)
[java.lang.ThreadGroup:uncaughtException:1052]: at java.lang.Thread.run(Thread.java:748)
[java.lang.ThreadGroup:uncaughtException:1061]: Caused by: java.util.concurrent.ExecutionException: java.lang.NullPointerException
[java.lang.ThreadGroup:uncaughtException:1061]: at java.util.concurrent.FutureTask.report(FutureTask.java:122)
[java.lang.ThreadGroup:uncaughtException:1061]: at java.util.concurrent.FutureTask.get(FutureTask.java:192)
[java.lang.ThreadGroup:uncaughtException:1061]: at aroma1997.backup.mc.ThreadBackup.executeOnServerThreadAndWait(ThreadBackup.java:285)
[java.lang.ThreadGroup:uncaughtException:1061]: ... 3 more
[java.lang.Throwable:printStackTrace:643]: Caused by: java.lang.NullPointerException
[java.lang.Throwable:printStackTrace:643]: at mcjty.lostcities.dimensions.world.LostWorldProvider.getSaveFolder(LostWorldProvider.java:28)
[java.lang.Throwable:printStackTrace:643]: at aroma1997.backup.mc.ThreadBackup.getFileLocations(ThreadBackup.java:225)
[java.lang.Throwable:printStackTrace:643]: at aroma1997.backup.mc.ThreadBackup.lambda$makeBackup$0(ThreadBackup.java:136)
[java.lang.Throwable:printStackTrace:643]: at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[java.lang.Throwable:printStackTrace:643]: at aroma1997.core.util.registry.TickRegistry$TickRegistrySingle.lambda$addSingleCallback$1(TickRegistry.java:167)
[java.lang.Throwable:printStackTrace:643]: at aroma1997.core.util.registry.TickRegistry$TickRegistrySingle.tick(TickRegistry.java:185)
[java.lang.Throwable:printStackTrace:643]: at aroma1997.core.util.registry.TickRegistry$3.serverTick(TickRegistry.java:66)
[java.lang.Throwable:printStackTrace:643]: at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_2273__serverTick_ServerTickEvent.invoke(.dynamic)
[java.lang.Throwable:printStackTrace:643]: at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
[java.lang.Throwable:printStackTrace:643]: at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
[java.lang.Throwable:printStackTrace:643]: at net.minecraftforge.fml.common.FMLCommonHandler.onPreServerTick(FMLCommonHandler.java:279)
[java.lang.Throwable:printStackTrace:643]: at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:657)
[java.lang.Throwable:printStackTrace:643]: at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
[java.lang.Throwable:printStackTrace:643]: ... 1 more
```

I'm using the latest version of AromaBackup and Lost Cities for 1.12.2,
2.1.1.4 and 2.0.12 respectively.
I created a case over with Aroma as well.

**Comment by ranger135xp** [comment]
Fixed by Aroma in Alpha 3.0.0.0.b116 of AromaBackup for 1.12.2
