### ISSUE TITLE
Server World Gen Simply Not Listening To level-type=lostcities_bop

### ISSUE THREAD

**Issue by Xelrox** [McJty/LostCities#193]
I don't know if I'm just doing something wrong but I set the level-type to level-type=lostcities_bop, level-type=lostcities, level-type=LOSTCITIES_BOP, and level-type=LOSTCITIES and it hasn't loaded anything but the DEFAULT world type. I've hit save several times and deleted the world after each test to no avail. I've set generator-settings to generator-settings={"profile":"default"} to try and get it to load the default profile but it simply wont load anything.

I'm running the mod in my modpack "Magi-Tech Runners" because I want a mega city for the cyberpunk feel. My end goal is to get a server running the rarecities profile, as I assume that spreads cities out more, which is something my friend wants because the idea of a massive city isn't a fun idea to him but without the cities it would defeat the very basis of what started the modpack's theme. Any help on figuring this out would be appreciated.

Below I'm attatching the server.properties as a txt and the modlist in case something on that is somehow effecting it.

[modlist.txt](https://github.com/McJtyMods/LostCities/files/3026928/modlist.txt)

[serverproperties.txt](https://github.com/McJtyMods/LostCities/files/3026925/serverproperties.txt)

**Comment by McJty** [comment]
Normally it is 'lostcities_bop' (lowercase). Try that first

**Comment by Xelrox** [comment]
Not sure if it worked or not yet, I noticed something interesting, I keep deleting the "world" file to delete the world, but when I loaded it up one time here, I drowned. I changed the line, saved the file, and then deleted the world and started the server... and it loaded the same world. I know this because where I died matches the land on Journeymap. Looking into it further but I do recall messing up and putting the lostcities_bop in generator-settings instead of level-type to start, so the world obviously wouldn't have loaded properly. I'm deep scrubbing the files to get the server to load a new world, will get back to you if it worked properly after that.

Thank you for the help.

**Comment by Xelrox** [comment]
Okay, I solved that problem, it's still not loading cities in with level-type=lostcities_bop

[serverproperties.txt](https://github.com/McJtyMods/LostCities/files/3026992/serverproperties.txt)

**Comment by Xelrox** [comment]
I really don't know what I'm doing wrong but there has to be something because I'm giving it the paramaters level-type=lostcities_bop and generator-settings={"profile":"default"} and it still wont generate as bop with cities it just generates default. I don't know if it's not reading the server.properties or something and just doing its own thing but it isn't telling me that when I turn the server on.

**Comment by Xelrox** [comment]
Hold on... I do get one odd error...

[15:39:55 INFO]: Starting minecraft server version 1.12.2
[15:39:55 INFO]: Loading properties
[15:39:55 ERROR]: Exception handling console input
java.io.IOException: The handle is invalid
	at java.io.FileInputStream.readBytes(Native Method) ~[?:1.8.0_201]
	at java.io.FileInputStream.read(Unknown Source) ~[?:1.8.0_201]
	at java.io.BufferedInputStream.read1(Unknown Source) ~[?:1.8.0_201]
	at java.io.BufferedInputStream.read(Unknown Source) ~[?:1.8.0_201]
	at sun.nio.cs.StreamDecoder.readBytes(Unknown Source) ~[?:1.8.0_201]
	at sun.nio.cs.StreamDecoder.implRead(Unknown Source) ~[?:1.8.0_201]
	at sun.nio.cs.StreamDecoder.read(Unknown Source) ~[?:1.8.0_201]
	at java.io.InputStreamReader.read(Unknown Source) ~[?:1.8.0_201]
	at java.io.BufferedReader.fill(Unknown Source) ~[?:1.8.0_201]
	at java.io.BufferedReader.readLine(Unknown Source) ~[?:1.8.0_201]
	at java.io.BufferedReader.readLine(Unknown Source) ~[?:1.8.0_201]
	at nz$2.run(SourceFile:100) [minecraft_server.1.12.2.jar:?]
[15:39:55 INFO]: Default game type: SURVIVAL
[15:39:55 INFO]: Generating keypair
[15:39:55 INFO]: Starting Minecraft server on *:25565
[15:39:55 INFO]: Using default channel type
[15:39:56 INFO]: Preparing level "world"
[15:39:56 INFO]: Loaded 488 advancements
**[15:39:56 WARN]: Unable to find spawn biome**
[15:39:57 INFO]: Preparing start region for level 0
[15:39:58 INFO]: Preparing spawn area: 14%
[15:39:59 INFO]: Preparing spawn area: 31%
[15:40:00 INFO]: Preparing spawn area: 48%
[15:40:01 INFO]: Preparing spawn area: 66%
[15:40:02 INFO]: Preparing spawn area: 85%
[15:40:03 INFO]: Done (6.761s)! For help, type "help" or "?"

It's odd that I'm getting [15:39:56 WARN]: Unable to find spawn biome and could be part of the issue, investigating.

**Comment by Xelrox** [comment]
Okay, so I just wanna go on record and say I am one of the dumbest people I have ever met.

You clearly see that there are no mods being loaded in above yes?
That's cause I was running the normal server, not the modded server.
Surprise! It works when I run the forge file!

I apologies for the waste of time, the mod is wonderful, keep up the good work!
