### ISSUE TITLE
lc_debug command is broken

### ISSUE THREAD

**Issue by wormzjl** [McJty/LostCities#199]
It gives a NPE on use
`[19:59:58] [Server thread/WARN] [minecraft/CommandHandler]: Couldn't process command: lc_debug
java.lang.NullPointerException: null
	at mcjty.lostcities.dimensions.world.lost.BuildingInfo.getBuildingInfo(BuildingInfo.java:634) ~[BuildingInfo.class:?]
	at mcjty.lostcities.commands.CommandDebug.func_184881_a(CommandDebug.java:44) ~[CommandDebug.class:?]
	at net.minecraft.command.CommandHandler.func_175786_a(CommandHandler.java:119) [bj.class:?]
	at net.minecraft.command.CommandHandler.func_71556_a(CommandHandler.java:91) [bj.class:?]
	at net.minecraft.network.NetHandlerPlayServer.func_147361_d(NetHandlerPlayServer.java:962) [pa.class:?]
	at net.minecraft.network.NetHandlerPlayServer.func_147354_a(NetHandlerPlayServer.java:941) [pa.class:?]
	at net.minecraft.network.play.client.CPacketChatMessage.func_148833_a(SourceFile:37) [la.class:?]
	at net.minecraft.network.play.client.CPacketChatMessage.func_148833_a(SourceFile:9) [la.class:?]
	at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) [hv$1.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_202]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_202]
	at net.minecraft.util.Util.func_181617_a(SourceFile:46) [h.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:723) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668) [MinecraftServer.class:?]
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:185) [chd.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:813) [?:1.8.0_202]`

**Comment by wormzjl** [comment]
Seems that reverting https://github.com/McJtyMods/LostCities/commit/900fd3961be96e4faf9ba75b24cb8150a2d3c254#diff-71ed966140b007769132608596960cf3 fixes the issue
