### ISSUE TITLE
crash generating chunk NPE

### ISSUE THREAD

**Issue by LukaPix** [McJty/LostCities#219]
uhm..yeah...what ?
i edited the rare cities preset and stayed within the limits stated in the options... so...
I dont know which was the last thign i changed, but it shouldnt crash anyway..

```
Description: Exception generating new chunk

java.lang.NullPointerException: Exception generating new chunk
	at mcjty.lostcities.dimensions.world.terraingen.LostCitiesTerrainGenerator.generatePart(LostCitiesTerrainGenerator.java:2038)
	at mcjty.lostcities.dimensions.world.terraingen.LostCitiesTerrainGenerator.generateBuilding(LostCitiesTerrainGenerator.java:2297)
	at mcjty.lostcities.dimensions.world.terraingen.LostCitiesTerrainGenerator.doCityChunk(LostCitiesTerrainGenerator.java:911)
	at mcjty.lostcities.dimensions.world.terraingen.LostCitiesTerrainGenerator.generate(LostCitiesTerrainGenerator.java:252)
	at mcjty.lostcities.dimensions.world.LostCityChunkGenerator.func_185932_a(LostCityChunkGenerator.java:224)
	at net.minecraft.world.gen.ChunkProviderServer.func_186025_d(ChunkProviderServer.java:143)
	at net.minecraft.server.MinecraftServer.func_71222_d(MinecraftServer.java:344)
	at net.minecraft.server.integrated.IntegratedServer.func_71247_a(IntegratedServer.java:142)
	at net.minecraft.server.integrated.IntegratedServer.func_71197_b(IntegratedServer.java:156)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:486)
	at java.lang.Thread.run(Unknown Source)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at mcjty.lostcities.dimensions.world.terraingen.LostCitiesTerrainGenerator.generatePart(LostCitiesTerrainGenerator.java:2038)
	at mcjty.lostcities.dimensions.world.terraingen.LostCitiesTerrainGenerator.generateBuilding(LostCitiesTerrainGenerator.java:2297)
	at mcjty.lostcities.dimensions.world.terraingen.LostCitiesTerrainGenerator.doCityChunk(LostCitiesTerrainGenerator.java:911)
	at mcjty.lostcities.dimensions.world.terraingen.LostCitiesTerrainGenerator.generate(LostCitiesTerrainGenerator.java:252)
	at mcjty.lostcities.dimensions.world.LostCityChunkGenerator.func_185932_a(LostCityChunkGenerator.java:224)

-- Chunk to be generated --
Details:
	Location: -2,15
	Position hash: 68719476734
	Generator: mcjty.lostcities.dimensions.world.LostCityChunkGenerator@2a2e0c62
Stacktrace:
	at net.minecraft.world.gen.ChunkProviderServer.func_186025_d(ChunkProviderServer.java:143)
	at net.minecraft.server.MinecraftServer.func_71222_d(MinecraftServer.java:344)
	at net.minecraft.server.integrated.IntegratedServer.func_71247_a(IntegratedServer.java:142)
	at net.minecraft.server.integrated.IntegratedServer.func_71197_b(IntegratedServer.java:156)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:486)
	at java.lang.Thread.run(Unknown Source)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_181, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 3195277744 bytes (3047 MB) / 3750232064 bytes (3576 MB) up to 5726797824 bytes (5461 MB)
	JVM Flags: 3 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xms2432m -Xmx6144m
	IntCache: cache: 1, tcache: 1, allocated: 12, tallocated: 94
	FML: MCP 9.42 Powered by Forge 14.23.5.2806 6 mods loaded, 6 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State  | ID         | Version      | Source                                  | Signature                                |
	|:------ |:---------- |:------------ |:--------------------------------------- |:---------------------------------------- |
	| LCHIJA | minecraft  | 1.12.2       | minecraft.jar                           | None                                     |
	| LCHIJA | mcp        | 9.42         | minecraft.jar                           | None                                     |
	| LCHIJA | FML        | 8.0.99.99    | forge-1.12.2-14.23.5.2806-universal.jar | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | forge      | 14.23.5.2806 | forge-1.12.2-14.23.5.2806-universal.jar | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | lostcities | 2.0.20       | lostcities-1.12-2.0.20.jar              | None                                     |
	| LCHIJA | lostsouls  | 1.1.4        | lostsouls-1.12-1.1.4.jar                | None                                     |

	Loaded coremods (and transformers): 
	GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
	Profiler Position: N/A (disabled)
	Player Count: 0 / 8; []
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fml,forge'
```

And here the Preset

`# Configuration file

##########################################################################################################
# cities_rarecities
#--------------------------------------------------------------------------------------------------------#
# Settings related to city generation for the rarecities profile
##########################################################################################################

cities_rarecities {
    # The default biome factor which is used if your biome is not specified in 'cityBiomeFactors' [range: 0.0 ~ 1.0, default: 1.0]
    S:cityBiomeFactorDefault=1.0

    # List of biomes with a factor to affect the city factor in that biome. Using the value 0 you can disable city generation in biomes [default: [Ljava.lang.String;@6153b116]
    S:cityBiomeFactors <
        river=0
        frozen_river=0
        ocean=.7
        frozen_ocean=.7
        deep_ocean=.4
     >

    # The chance this chunk will be the center of a city [range: 0.0 ~ 1.0, default: 0.002]
    S:cityChance=0.001

    # Below this chunk height cities will be level 0 [range: 1 ~ 255, default: 75]
    I:cityLevel0Height=75

    # Below this chunk height cities will be level 1 [range: 1 ~ 255, default: 83]
    I:cityLevel1Height=83

    # Below this chunk height cities will be level 2 [range: 1 ~ 255, default: 91]
    I:cityLevel2Height=91

    # Below this chunk height cities will be level 3 [range: 1 ~ 255, default: 99]
    I:cityLevel3Height=99

    # The maximum radius of a city [range: 1 ~ 10000, default: 128]
    I:cityMaxRadius=3000

    # The minimum radius of a city [range: 1 ~ 10000, default: 50]
    I:cityMinRadius=100

    # The center and radius of a city define a sphere. This thresshold indicates from which point a city is considered a city. This is important for calculating where cities are based on overlapping city circles (where the city thressholds are added) [range: 0.0 ~ 1.0, default: 0.2]
    S:cityThresshold=0.2
}

##########################################################################################################
# cityspheres_rarecities
#--------------------------------------------------------------------------------------------------------#
# Settings related to city sphere generation for the rarecities profile
##########################################################################################################

cityspheres_rarecities {
    # The chance that a city sphere will be generated [range: 0.0 ~ 1.0, default: 0.7]
    S:citySphereChance=0.3

    # Only used in 'space' landscape. This factor will be multiplied with the radius of the city to calculate the radius of the outer sphere [range: 0.1 ~ 10.0, default: 1.2]
    S:citySphereFactor=1.2

    # If this is true then there will be a landscape outside the city spheres [default: false]
    B:landscapeOutside=false

    # The chance that a city will have a monorail connection in a certain direction. There will only be an actual connection if there is a city in that direction that also wants a monorail [range: 0.0 ~ 1.0, default: 0.8]
    S:monorailChance=1.2

    # Offset compared to main height [range: -100 ~ 100, default: -2]
    I:monorailOffset=-3

    # If this is true then only predefined spheres are generated [default: false]
    B:onlyPredefined=false

    # Ground level for outside city spheres (DEPRECATED, USE GROUNDLEVEL OF OTHER PROFILE) [range: -1 ~ 256, default: -1]
    I:outsideGroundLevel=-1

    # An optional profile to use for the outside world [default: ]
    S:outsideProfile=

    # Smaller numbers make the surface outside a city sphere more varied [range: 0.0 ~ 1.0, default: 1.0]
    S:outsideSurfaceVariation=1.0

    # If this is true then every city sphere will be limited to one (random) biome [default: false]
    B:singleBiome=false

    # Smaller numbers make the surface inside a city sphere more varied [range: 0.0 ~ 1.0, default: 1.0]
    S:sphereSurfaceVariation=1.0
}

##########################################################################################################
# client_rarecities
#--------------------------------------------------------------------------------------------------------#
# Client side settings for the rarecities profile
##########################################################################################################

client_rarecities {
    # This is used client-side (but only if the client has this mod) for the fog color [range: -1.0 ~ 1.0, default: -1.0]
    S:fogBlue=-1.0

    # This is used client-side (but only if the client has this mod) for the fog density [range: -1.0 ~ 1.0, default: -1.0]
    S:fogDensity=-2.0

    # This is used client-side (but only if the client has this mod) for the fog color [range: -1.0 ~ 1.0, default: -1.0]
    S:fogGreen=-3.0

    # This is used client-side (but only if the client has this mod) for the fog color [range: -1.0 ~ 1.0, default: -1.0]
    S:fogRed=-1.0

    # This is used client-side (but only if the client has this mod) to set the height of the horizon [range: -1.0 ~ 256.0, default: -1.0]
    S:horizon=-1.0
}

##########################################################################################################
# explosions_rarecities
#--------------------------------------------------------------------------------------------------------#
# Settings related to explosions and damage for the rarecities profile
##########################################################################################################

explosions_rarecities {
    # A factor that determines how much debris will overflow from nearby damaged chunks. Bigger numbers mean less debris [range: 1 ~ 10000, default: 200]
    I:debrisToNearbyChunkFactor=400

    # When a section of blocks in in an explosion the generator will count the number of blocks that are connected. The number of connections divided by the total number of blocks in a connected section is compared with this number. If it is smaller then the section of blocks is destroyed or moved down with gravity [range: 0.0 ~ 1.0, default: 0.05]
    S:destroyLoneBlocksFactor=0.05

    # When a section of blocks is to be moved or destroyed this chance gives the chance of removal (as opposed to moving with gravity) [range: 0.0 ~ 1.0, default: 0.4]
    S:destroyOrMoveChance=0.2

    # A section of blocks that is about to be moved or destroyed is always destroyed if it is smaller then this size [range: 1 ~ 5000, default: 50]
    I:destroySmallSectionsSize=50

    # The chance that a chunk will contain an explosion [range: 0.0 ~ 1.0, default: 0.002]
    S:explosionChance=0.01

    # The maximum height of an explosion [range: 1 ~ 256, default: 90]
    I:explosionMaxHeight=120

    # The maximum radius of an explosion [range: 1 ~ 3000, default: 35]
    I:explosionMaxRadius=40

    # The minimum height of an explosion [range: 1 ~ 256, default: 75]
    I:explosionMinHeight=75

    # The minimum radius of an explosion [range: 1 ~ 1000, default: 15]
    I:explosionMinRadius=15

    # If this is true the center of an explosion can only be in a city (the blast can still affect non-city chunks) [default: true]
    B:explosionsInCitiesOnly=true

    # The chance that a chunk will contain a mini explosion [range: 0.0 ~ 1.0, default: 0.03]
    S:miniExplosionChance=0.03

    # The maximum height of a mini explosion [range: 1 ~ 256, default: 100]
    I:miniExplosionMaxHeight=100

    # The maximum radius of a mini explosion [range: 1 ~ 3000, default: 12]
    I:miniExplosionMaxRadius=12

    # The minimum height of a mini explosion [range: 1 ~ 256, default: 60]
    I:miniExplosionMinHeight=60

    # The minimum radius of a mini explosion [range: 1 ~ 1000, default: 5]
    I:miniExplosionMinRadius=5
}

##########################################################################################################
# lostcity_rarecities
#--------------------------------------------------------------------------------------------------------#
# Settings related to the Lost City for the rarecities profile
##########################################################################################################

lostcity_rarecities {
    # List of biomes that are allowed in the world. Empty list is default all biomes. The factor controls how much that biome is favored over the others (higher means less favored!) [default: [Ljava.lang.String;@380cb7e3]
    S:allowedBiomeFactors <
     >

    # If this is true then parks will have no foliage (trees and flowers currently) [default: false]
    B:avoidFoliage=false

    # This will prevent biomes from generating cactii [default: false]
    B:avoidGeneratedCactii=false

    # This will prevent the generation of desert wells [default: false]
    B:avoidGeneratedDesertWell=false

    # This will prevent biomes from generating flowers [default: false]
    B:avoidGeneratedFlowers=false

    # This will prevent the generation of fossils [default: false]
    B:avoidGeneratedFossils=false

    # This will prevent biomes from generating grass [default: false]
    B:avoidGeneratedGrass=false

    # This will prevent the generation of water in lakes [default: false]
    B:avoidGeneratedLakewater=false

    # This will prevent biomes from generating lilypads [default: false]
    B:avoidGeneratedLilypads=false

    # This will prevent biomes from generating mushrooms [default: false]
    B:avoidGeneratedMushrooms=false

    # This will prevent biomes from generating pumpkins [default: false]
    B:avoidGeneratedPumpkins=false

    # This will prevent biomes from generating reeds [default: false]
    B:avoidGeneratedReeds=false

    # This will prevent biomes from generating trees [default: false]
    B:avoidGeneratedTrees=false

    # If true then all water will be avoided (replaced with air) [default: false]
    B:avoidWater=false

    # Block to use as the worldgen base [default: minecraft:stone]
    S:baseBlock=minecraft:stone

    # The height of the bedrock layer that is generated at the bottom of some world types. Set to 0 to disable this and get default bedrock generation [range: 0 ~ 10, default: 1]
    I:bedrockLayer=1

    # This is used in combination with allowedBiomeFactors. 'original' is the old strategy. 'randomized' is a new strategy that tries to randomize the biomes better. 'varied' is similar but has a more relaxed biome distance function [default: original]
    S:biomeSelectionStrategy=original

    # The chance that a chunk can possibly contain a bridge. There actually being a bridge also depends on the presence of adjacent bridges and other conditions [range: 0.0 ~ 1.0, default: 0.7]
    S:bridgeChance=0.7

    # If true bridges get supports when needed. You can disable this if you have bridges that span void chunks [default: true]
    B:bridgeSupports=true

    # The chance that a chunk can possibly be the top-left chunk of 2x2 building. There actually being a 2x2 building also depends on the condition of those other chunks [range: 0.0 ~ 1.0, default: 0.03]
    S:building2x2Chance=0.03

    # The chance that a chunk in a city will have a building. Otherwise it will be a street [range: 0.0 ~ 1.0, default: 0.3]
    S:buildingChance=0.4

    # The chance that a doorway will be generated at a side of a building (on any level). Only when possible [range: 0.0 ~ 1.0, default: 0.6]
    S:buildingDoorwayChance=0.6

    # The chance that a building will have a 'front' part if this is possible (i.e. adjacent street) [range: 0.0 ~ 1.0, default: 0.2]
    S:buildingFrontChance=0.3

    # The maximum number of cellars (below ground). 0 means no cellar [range: 0 ~ 7, default: 4]
    I:buildingMaxCellars=6

    # A cap for the amount of floors a city can have (above ground) [range: 0 ~ 30, default: 9]
    I:buildingMaxFloors=29

    # The amount of floors of a building is equal to: MINFLOORS + random(MINFLOORS_CHANCE + (cityFactor + .1f) * (MAXFLOORS_CHANCE - MINFLOORS_CHANCE)) [range: 1 ~ 30, default: 6]
    I:buildingMaxFloorsChance=11

    # The minimum number of cellars (below ground). 0 means no cellar [range: 0 ~ 7, default: 0]
    I:buildingMinCellars=1

    # The minimum number of floors (above ground) for a building (0 means the first floor only) [range: 0 ~ 30, default: 0]
    I:buildingMinFloors=1

    # The amount of floors of a building is equal to: MINFLOORS + random(MINFLOORS_CHANCE + (cityFactor + .1f) * (MAXFLOORS_CHANCE - MINFLOORS_CHANCE)) [range: 1 ~ 30, default: 4]
    I:buildingMinFloorsChance=4

    # The chance that a building will have no loot and no spawners [range: 0.0 ~ 1.0, default: 0.2]
    S:buildingWithoutLootChance=0.2

    # The chance that a chest will have no loot [range: 0.0 ~ 1.0, default: 0.2]
    S:chestWithoutLootChance=0.2

    # The chance that a chunk can possibly contain a corridor. There actually being a corridor also depends on the presence of adjacent corridors [range: 0.0 ~ 1.0, default: 0.7]
    S:corridorChance=0.4

    # The chance that a 2x2 building will be a data center [range: 0.0 ~ 1.0, default: 0.1]
    S:dataCenterChance=0.1

    # The description of this profile [default: Cities are rare]
    S:description=Custom For US

    # Additional information [default: ]
    S:extraDescription=Ya YEET big builds

    # The chance that a street section contains a fountain [range: 0.0 ~ 1.0, default: 0.05]
    S:fountainChance=0.05

    # If true then there will be minimal lighting in the buildings [default: false]
    B:generateLighting=false

    # If true the chests in the buildings will contain loot [default: true]
    B:generateLoot=true

    # If true then the buildings will be full of spawners [default: true]
    B:generateSpawners=true

    # A json with generator options for the chunk generator [default: ]
    S:generatorOptions=

    # Ground level [range: 2 ~ 256, default: 71]
    I:groundLevel=71

    # Mask to control how far highways can generate. Must be a power of 2 (minus 1). If 0 there are no highways at all [range: 0 ~ 2147483647, default: 7]
    I:highwayDistanceMask=7

    # 0 (take height from top-left city), 1 (take minimum height from both cities), 2 (take maximum height from both cities), 3 (take average height) [range: 0 ~ 3, default: 0]
    I:highwayLevelFromCities=0

    # For highways on a certain axis, this value is used to scale the perlin noise generator on the main axis. Increasing this value will increase the frequency of highways but make them smaller [range: 1.0 ~ 1000.0, default: 50.0]
    S:highwayMainPerlinScale=50.0

    # The highway perlin noise is compared to this value. Setting this to 0 would give 50% chance of a highway being at a spot. Note that highways only generate on chunks a multiple of 8. Setting this very high will prevent highways from generating [range: -100.0 ~ 100.0, default: 2.0]
    S:highwayPerlinFactor=2.0

    # If true then a highway will only generate if both sides have a valid city. If false then one city is sufficient [default: false]
    B:highwayRequiresTwoCities=true

    # For highways on a certain axis, this value is used to scale the perlin noise generator on the secondary axis. Increasing this value will increase the variation of nearby highways [range: 1.0 ~ 1000.0, default: 10.0]
    S:highwaySecondaryPerlinScale=10.0

    # If true highways get supports when needed. You can disable this if you have highways that span void chunks [default: true]
    B:highwaySupports=true

    # The icon to use in the configuration screen (64x64) [default: textures/gui/icon_rarecities.png]
    S:icon=textures/gui/icon_rarecities.png

    # Type of landscape [default: default]
    S:landscapeType=default

    # The chance that a 2x2 building will be a library [range: 0.0 ~ 1.0, default: 0.1]
    S:libraryChance=0.1

    # Block to use as a liquid [default: minecraft:water]
    S:liquidBlock=minecraft:water

    # Use in combination with 'allowedBiomeFactors' to manually map some biomes to others. This is a list of the format oldbiome=newbiome [default: [Ljava.lang.String;@49d94d67]
    S:manualBiomeMappings <
     >

    # The chance that a non-building section can be a park section [range: 0.0 ~ 1.0, default: 0.2]
    S:parkChance=0.15

    # The chance that a chunk next to a railway will have a railway dungeon [range: 0.0 ~ 1.0, default: 0.01]
    S:railwayDungeonChance=0.01

    # If true then railway stations are enabled [default: true]
    B:railwayStationsEnabled=true

    # If true the a place where a station would have been if there was a city above will have an 'ending' rail part if one side of the 'station' has no connections. Useful in case cities are rare [default: true]
    B:railwaysCanEnd=true

    # If true then railways are enabled. If false they are not (but stations will still generate) [default: true]
    B:railwaysEnabled=true

    # Chance that leafblocks will be generated at the border of a building and a street [range: 0.0 ~ 1.0, default: 0.1]
    S:randomLeafBlockChance=0.3

    # Frequency of leafblocks as seen from the sides of buildings [range: 1 ~ 8, default: 2]
    I:randomLeafBlockThickness=1

    # The scale of the dirt layer. Smaller values make the layer larger. Use 0 to disable [range: 0.0 ~ 100.0, default: 3.0]
    S:rubbleDirtScale=6.0

    # If this is true an alternative way to generate dirt/stone/sand + leave blocks is used that makes the city appear more overgrown [default: true]
    B:rubbleLayer=true

    # The scale of the leave layer. Smaller values make the layer larger. Use 0 to disable [range: 0.0 ~ 100.0, default: 6.0]
    S:rubbleLeaveScale=5.0

    # If ruines are enabled this gives the chance that a building is ruined [range: 0.0 ~ 1.0, default: 0.05]
    S:ruinChance=0.3

    # If a building is ruined this indicates the maximum start height for the ruin destruction layer [range: 0.0 ~ 1.0, default: 1.0]
    S:ruinMaxlevelPercent=1.0

    # If a building is ruined this indicates the minimum start height for the ruin destruction layer [range: 0.0 ~ 1.0, default: 0.8]
    S:ruinMinlevelPercent=2.0

    # If true there is a chance a building is ruined from the top (not caused by explosion damage) [default: false]
    B:ruins=true

    # When this is set the player will always spawn in the given biome [default: ]
    S:spawnBiome=

    # When this is set the player will always spawn in the given predefined city [default: ]
    S:spawnCity=

    # If this is true the player will not spawn in a building. This can be used in combination with the other spawn settings [default: false]
    B:spawnNotInBuilding=false

    # When this is set the player will always spawn in the given predefined sphere. If you use <in> the player will always spawn in a random sphere. If you use <out> the player will always spawn outside a sphere [default: ]
    S:spawnSphere=

    # The chance that a block on the outside of a building will be covered with a vine [range: 0.0 ~ 1.0, default: 0.009]
    S:vineChance=0.009

    # How much lower the water level is compared to the ground level (63) [range: -100 ~ 100, default: 8]
    I:waterLevelOffset=8

    # The worldstyle used by this profile (defined in the assets) [default: standard]
    S:worldStyle=standard
}

maxcaveheight {
    # Maximum height at which vanilla caves can generate. Default is 128. Lower this if you don't want the caves to damage buildings [range: 20 ~ 240, default: 128]
    I:structures_rarecities=128
}

##########################################################################################################
# structures_rarecities
#--------------------------------------------------------------------------------------------------------#
# Settings related to structure generation for the rarecities profile
##########################################################################################################

structures_rarecities {
    # Generate caves
    B:generateCaves=true

    # Generate dungeons
    B:generateDungeons=true

    # Generate lakes (lava/water)
    B:generateLakes=true

    # Generate mansions
    B:generateMansions=true

    # Generate mineshafts
    B:generateMineshafts=true

    # Generate ocean monuments
    B:generateOceanMonuments=true

    # Generate ravines
    B:generateRavines=true

    # Generate scattered features (swamphunts, desert temples, ...)
    B:generateScattered=true

    # Generate strongholds
    B:generateStrongholds=true

    # Generate villages
    B:generateVillages=true

    # If true then no lakes and ravines will be generated in cities
    B:preventLakesRavinesInCities=true

    # If true then an attempt will be made to prevent villages in cities. Note that enabling this option will likely require a low city density in order to actually get a reasonable chance for villages.
    B:preventVillagesInCities=true
}`

**Comment by McJty** [comment]
It is VERY easy to crash lost cities by making the wrong config changes. It's nearly impossible for me to check all possibilities (and that would slow down worldgen a lot). Maybe try again from fresh configs and gradually change the settings. Also it would help if you could let me know which settings you changed

**Comment by LukaPix** [comment]
could be similar to #190

**Comment by LukaPix** [comment]
i changed almost all ratios.. like literally every second option but i have configured 29 floors, that could be a problem..

**Comment by LukaPix** [comment]
And i'll to as soon as i get to it !

**Comment by McJty** [comment]
I:buildingMaxFloors=29

I just saw this. That may indeed be a problem
