### ISSUE TITLE
lostcities-1.14-2.0.27-alpha crash when generating new chunks

### ISSUE THREAD

**Issue by StrangeThistle** [McJty/LostCities#243]
After updating from lostcities-1.14-2.0.26-alpha to lostcities-1.14-2.0.27-alpha (custom pack using Forge-28.1.114), the game crashed every time I tried to generate new chunks. Rolling back to the previous version did fix the issue. (World created under 2.0.26, did not try creating new world under 2.0.27). Remind me where to post the crash report if you need it.

I'm really liking the way the customization options work, although I did notice that nether generation does not yet follow them. Also still trying to decide if I like having a world wide subway grid generate when I make the cities small and infrequent. Part of me likes the convenience, but part of me thinks it should be limited to lines connecting the cities that spawn.

**Comment by josephcsible** [comment]
We absolutely need the crash report. You can either post it in a pastebin and link to it here, or just post it here.

**Comment by StrangeThistle** [comment]
Since you don't mind it posted here, here you are.

---- Minecraft Crash Report ----
// Who set us up the TNT?

Time: 1/16/20 5:03 PM
Description: Feature placement

java.lang.NullPointerException: Feature placement
	at mcjty.lostcities.setup.Config.getProfileForDimension(Config.java:75) ~[?:1.14-2.0.27-alpha] {re:classloading}
	at mcjty.lostcities.worldgen.LostCityFeature.getDimensionInfo(LostCityFeature.java:48) ~[?:1.14-2.0.27-alpha] {re:classloading}
	at mcjty.lostcities.worldgen.LostCityFeature.place(LostCityFeature.java:31) ~[?:1.14-2.0.27-alpha] {re:classloading}
	at mcjty.lostcities.worldgen.LostCityFeature.func_212245_a(LostCityFeature.java:20) ~[?:1.14-2.0.27-alpha] {re:classloading}
	at net.minecraft.world.gen.feature.ConfiguredFeature.func_222734_a(SourceFile:36) ~[?:?] {re:classloading}
	at net.minecraft.world.gen.placement.Placement.lambda$place$0(Placement.java:72) ~[?:?] {re:classloading}
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184) ~[?:1.8.0_74] {}
	at java.util.stream.IntPipeline$4$1.accept(IntPipeline.java:250) ~[?:1.8.0_74] {}
	at java.util.stream.Streams$RangeIntSpliterator.forEachRemaining(Streams.java:110) ~[?:1.8.0_74] {}
	at java.util.Spliterator$OfInt.forEachRemaining(Spliterator.java:693) ~[?:1.8.0_74] {}
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481) ~[?:1.8.0_74] {}
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471) ~[?:1.8.0_74] {}
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151) ~[?:1.8.0_74] {}
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174) ~[?:1.8.0_74] {}
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:1.8.0_74] {}
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418) ~[?:1.8.0_74] {}
	at net.minecraft.world.gen.placement.Placement.func_214998_a(Placement.java:71) ~[?:?] {re:classloading}
	at net.minecraft.world.gen.placement.ConfiguredPlacement.func_215093_a(SourceFile:35) ~[?:?] {re:classloading}
	at net.minecraft.world.gen.feature.DecoratedFeature.func_212245_a(SourceFile:20) ~[?:?] {re:classloading}
	at net.minecraft.world.gen.feature.DecoratedFeature.func_212245_a(SourceFile:13) ~[?:?] {re:classloading}
	at net.minecraft.world.gen.feature.ConfiguredFeature.func_222734_a(SourceFile:36) ~[?:?] {re:classloading}
	at net.minecraft.world.biome.Biome.func_203608_a(Biome.java:283) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.world.gen.ChunkGenerator.func_202092_b(ChunkGenerator.java:104) ~[?:?] {re:classloading}
	at net.minecraft.world.chunk.ChunkStatus.lambda$static$9(ChunkStatus.java:73) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.world.chunk.ChunkStatus.func_223198_a(ChunkStatus.java:196) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.world.server.ChunkManager.lambda$null$17(ChunkManager.java:509) ~[?:?] {re:classloading}
	at com.mojang.datafixers.util.Either$Left.map(Either.java:38) ~[datafixerupper-2.0.24.jar:?] {}
	at net.minecraft.world.server.ChunkManager.lambda$func_223156_b$19(ChunkManager.java:507) ~[?:?] {re:classloading}
	at java.util.concurrent.CompletableFuture.uniCompose(CompletableFuture.java:952) ~[?:1.8.0_74] {}
	at java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:926) ~[?:1.8.0_74] {}
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:442) ~[?:1.8.0_74] {}
	at net.minecraft.world.chunk.ChunkTaskPriorityQueueSorter.func_219083_b(SourceFile:58) ~[?:?] {re:classloading}
	at net.minecraft.util.concurrent.DelegatedTaskExecutor.func_213148_e(SourceFile:83) ~[?:?] {re:classloading}
	at net.minecraft.util.concurrent.DelegatedTaskExecutor.func_213145_a(SourceFile:123) ~[?:?] {re:classloading}
	at net.minecraft.util.concurrent.DelegatedTaskExecutor.run(SourceFile:91) ~[?:?] {re:classloading}
	at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1402) ~[?:1.8.0_74] {}
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289) ~[?:1.8.0_74] {}
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056) ~[?:1.8.0_74] {}
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692) ~[?:1.8.0_74] {}
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157) ~[?:1.8.0_74] {}


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at mcjty.lostcities.setup.Config.getProfileForDimension(Config.java:75)
	at mcjty.lostcities.worldgen.LostCityFeature.getDimensionInfo(LostCityFeature.java:48)
	at mcjty.lostcities.worldgen.LostCityFeature.place(LostCityFeature.java:31)
	at mcjty.lostcities.worldgen.LostCityFeature.func_212245_a(LostCityFeature.java:20)
	at net.minecraft.world.gen.feature.ConfiguredFeature.func_222734_a(SourceFile:36)
	at net.minecraft.world.gen.placement.Placement.lambda$place$0(Placement.java:72)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
	at java.util.stream.IntPipeline$4$1.accept(IntPipeline.java:250)
	at java.util.stream.Streams$RangeIntSpliterator.forEachRemaining(Streams.java:110)
	at java.util.Spliterator$OfInt.forEachRemaining(Spliterator.java:693)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
	at net.minecraft.world.gen.placement.Placement.func_214998_a(Placement.java:71)
	at net.minecraft.world.gen.placement.ConfiguredPlacement.func_215093_a(SourceFile:35)
	at net.minecraft.world.gen.feature.DecoratedFeature.func_212245_a(SourceFile:20)
	at net.minecraft.world.gen.feature.DecoratedFeature.func_212245_a(SourceFile:13)
	at net.minecraft.world.gen.feature.ConfiguredFeature.func_222734_a(SourceFile:36)

-- Feature --
Details:
	Id: minecraft:decorated
	Description: < DecoratedFeature [minecraft:decorated] >
Stacktrace:
	at net.minecraft.world.biome.Biome.func_203608_a(Biome.java:283)

-- Generation --
Details:
	CenterX: -3
	CenterZ: 20
	Step: RAW_GENERATION
	Seed: -8598678283581202170
	Biome: minecraft:birch_forest
Stacktrace:
	at net.minecraft.world.gen.ChunkGenerator.func_202092_b(ChunkGenerator.java:104)
	at net.minecraft.world.chunk.ChunkStatus.lambda$static$9(ChunkStatus.java:73)
	at net.minecraft.world.chunk.ChunkStatus.func_223198_a(ChunkStatus.java:196)

-- Chunk to be generated --
Details:
	Location: -3,20
	Position hash: 90194313213
	Generator: net.minecraft.world.gen.OverworldChunkGenerator@53619b13
Stacktrace:
	at net.minecraft.world.server.ChunkManager.lambda$null$17(ChunkManager.java:509)
	at com.mojang.datafixers.util.Either$Left.map(Either.java:38)
	at net.minecraft.world.server.ChunkManager.lambda$func_223156_b$19(ChunkManager.java:507)
	at java.util.concurrent.CompletableFuture.uniCompose(CompletableFuture.java:952)
	at java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:926)
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:442)
	at net.minecraft.world.chunk.ChunkTaskPriorityQueueSorter.func_219083_b(SourceFile:58)
	at net.minecraft.util.concurrent.DelegatedTaskExecutor.func_213148_e(SourceFile:83)
	at net.minecraft.util.concurrent.DelegatedTaskExecutor.func_213145_a(SourceFile:123)
	at net.minecraft.util.concurrent.DelegatedTaskExecutor.run(SourceFile:91)

-- Affected level --
Details:
	All players: 1 total; [ServerPlayerEntity['StrangeThistle'/202, l='Maximum Overdrive', x=152.28, y=64.00, z=134.59]]
	Chunk stats: ServerChunkCache: 2290
	Level dimension: DimensionType{minecraft:overworld}
	Level name: Maximum Overdrive
	Level seed: -927706378
	Level generator: ID 00 - default, ver 1. Features enabled: true
	Level generator options: {}
	Level spawn location: World: (224,65,144), Chunk: (at 0,4,0 in 14,9; contains blocks 224,0,144 to 239,255,159), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 1234004 game time, 2096949 day time
	Level storage version: 0x04ABD - Anvil
	Level weather: Rain time: 44621 (now: false), thunder time: 145714 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: true
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:832)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:764)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:112)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:622)
	at java.lang.Thread.run(Thread.java:745)

-- System Details --
Details:
	Minecraft Version: 1.14.4
	Minecraft Version ID: 1.14.4
	Operating System: Mac OS X (x86_64) version 10.15.2
	Java Version: 1.8.0_74, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 565561832 bytes (539 MB) / 2147483648 bytes (2048 MB) up to 2147483648 bytes (2048 MB)
	CPUs: 8
	JVM Flags: 8 total; -Xss1M -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	ModLauncher: 4.1.0+62+5bfa59b
	ModLauncher launch target: fmlclient
	ModLauncher naming: srg
	ModLauncher services: 
		/eventbus-1.0.0-service.jar eventbus PLUGINSERVICE 
		/forge-1.14.4-28.1.114.jar object_holder_definalize PLUGINSERVICE 
		/forge-1.14.4-28.1.114.jar runtime_enum_extender PLUGINSERVICE 
		/accesstransformers-1.0.1-milestone.0.1+94458e7-shadowed.jar accesstransformer PLUGINSERVICE 
		/forge-1.14.4-28.1.114.jar capability_inject_definalize PLUGINSERVICE 
		/forge-1.14.4-28.1.114.jar runtimedistcleaner PLUGINSERVICE 
		/forge-1.14.4-28.1.114.jar fml TRANSFORMATIONSERVICE 
	FML: 28.1
	Forge: net.minecraftforge:28.1.114
	FML Language Providers: 
		javafml@28.1
		minecraft@1
	Mod List: 
		ComPatchedStorage-1.14.4-2.1.4.jar ComPatchedStorage {compatchedstorage@2.1.4 DONE}
		blockdrops-1.14.4-1.0.2.jar Block Drops {blockdrops@1.0.2 DONE}
		extendedfoods-1.14.4-0.0.2-beta.jar Extended Foods {extendedfoods@0.0.2-beta DONE}
		curiousshulkerboxes-FORGE-1.14.4-1.0.0.1.jar Curious Shulker Boxes {curiousshulkerboxes@FORGE-1.14.4-1.0.0.1 DONE}
		ChineseWorkshop-1.14.4-2.4.1.jar ChineseWorkshop {chineseworkshop@2.4.1 DONE}
		modnametooltip_1.14.3-1.12.1.jar Mod Name Tooltip {modnametooltip@1.12.1 DONE}
		rsgauges-1.14.4-1.2.0-b2.jar Gauges and Switches {rsgauges@1.2.0-b2 DONE}
		GravelMiner_1.14.4-8.1.6.jar GravelMiner {gravelminer@8.1.6 DONE}
		XaerosWorldMap_1.5.4_Forge_1.14.4.jar Xaero's World Map {xaeroworldmap@1.5.4 DONE}
		CookingForBlockheads_1.14.4-7.4.3.jar Cooking for Blockheads {cookingforblockheads@7.4.3 DONE}
		Placebo-1.14.4-2.3.5.jar Placebo {placebo@2.3.5 DONE}
		Powah-1.14.4-0.2.2.jar Powah {powah@0.2.2 DONE}
		eggs-1.14.4_1.0.jar Eat the eggs! {eggs@1.14.4_1.0 DONE}
		rangedpumps-0.6.1.jar Ranged Pumps {rangedpumps@0.6.1 DONE}
		firefly-1.14.4-1.0.1.jar Firefly {firefly@1.14.4-1.0.1 DONE}
		Fence Jumper-1.14.4-1.0.8.jar FenceJumper {fencejumper@version DONE}
		WitherSkeletonTweaks-1.14.4-3.1.0.jar Wither Skeleton Tweaks {wstweaks@3.1.0 DONE}
		Bookshelf-1.14.4-4.4.71.jar Bookshelf {bookshelf@4.4.71 DONE}
		buildinggadgets-3.1.1b.jar Building Gadgets {buildinggadgets@3.1.1b DONE}
		Apotheosis-1.14.4-2.4.4.jar Apotheosis {apotheosis@2.4.4 DONE}
		walkthroughberries-1.0a.jar Walk Through Berries {walkthroughberries@1.0a DONE}
		CarryOn MC1.14.4 v1.12.4.jar Carry On {carryon@1.12.4 DONE}
		JustEnoughResources-1.14.4-0.10.0.70.jar Just Enough Resources {jeresources@0.10.0.70 DONE}
		shetiphiancore-1.14-3.6.0.jar ShetiPhian-Core {shetiphiancore@3.6.0 DONE}
		mysticallib-1.14.4-1.13.0.jar Mystical Lib {mysticallib@1.14.4-1.13.0 DONE}
		quartz-chests-1.0.0.3.jar Quartz Chests {quartzchests@1.0.0.3 DONE}
		mcw-bridges-1.0.3-mc1.14.4.jar Macaw's Bridges {mcwbridges@1.0.3 DONE}
		dwmh-1.14.4-3.1.1.jar Dude! Where's my Horse? {dwmh@1.14.4-3.1.1 DONE}
		wishingforsunshine-1.14.4-0.0.0.1.jar Wishing for Sunshine {wishingforsunshine@NONE DONE}
		Lollipop-1.14.4-0.0.23.jar Lollipop {lollipop@0.0.23 DONE}
		Masonry-0.3.1.jar Masonry {masonry@1.0 DONE}
		curios-FORGE-1.14.4-1.0.6.jar Curios API {curios@FORGE-1.14.4-1.0.6 DONE}
		Patchouli-1.1-24.jar Patchouli {patchouli@1.1-23 DONE}
		flying_things-1.8.5-1.14.4.jar The Flying Things {flying_things@1.8.5 DONE}
		corail_woodcutter-1.1.1-1.14.4.jar Corail Woodcutter {corail_woodcutter@1.1.1 DONE}
		AutoRegLib-1.4-35.jar AutoRegLib {arl@1.4-35 DONE}
		OreExcavation-1.6.147.jar Ore Excavation {oreexcavation@NONE DONE}
		lostcities-1.14-2.0.27-alpha.jar LostCities {lostcities@1.14-2.0.27-alpha DONE}
		tombstone-4.1.8-1.14.4.jar Corail Tombstone {tombstone@4.1.8 DONE}
		mcw-roofs-1.0.1-mc1.14.4.jar Macaw's Roofs {mcwroofs@1.0.1 DONE}
		ChunkNoGoByeBye-1.14.4-1.0.3.jar ChunkNoGoByeBye {chunknogobyebye@1.14.4-1.0.3 DONE}
		curiouselytra-FORGE-1.14.4-1.0.jar Curious Elytra {curiouselytra@FORGE-1.14.4-1.0 DONE}
		nosoliciting-1.1.jar No Soliciting {nosoliciting@1.1 DONE}
		moreoverlays-1.16.1.jar More Overlays {moreoverlays@1.16.1 DONE}
		YAMDA-4.1.1.jar YAMDA {yamda@4.1.1 DONE}
		Charm-1.14.4-1.4.3.jar Charm {charm@1.14.4-1.4.3 DONE}
		instantunify-1.14.4-1.0.3.jar InstantUnify {instantunify@1.0.3 DONE}
		FastLeafDecay-v17.jar FastLeafDecay {fastleafdecay@v17 DONE}
		PrettyBeaches_1.14.4-3.0.7.jar Pretty Beaches {prettybeaches@3.0.7 DONE}
		Cyclic-1.14.4-0.1.2.jar Cyclic {cyclic@1.14.4-0.1.2 DONE}
		Pomarf's Dimensional Ores [1.14.4] (v1.1.3).jar Pomarf's Dimensional Ores {dimensionalores@1.1.2 DONE}
		Kiwi-1.14.4-2.6.1.jar Kiwi {kiwi@2.6.1 DONE}
		mining-helmet-1.14.4-1.0.2.jar Mining Helmet {mining_helmet@1.0.2 DONE}
		bountifulbaubles-1.14.4-0.0.2.jar Bountiful Baubles {bountifulbaubles@NONE DONE}
		platforms-1.14-1.5.1.jar Platforms {platforms@1.5.0 DONE}
		jei-1.14.4-6.0.0.27.jar Just Enough Items {jei@6.0.0.27 DONE}
		metalbarrels-1.4.jar Metal Barrels {metalbarrels@1.4 DONE}
		longfallboots-1.3.0b.jar Long Fall Boots {longfallboots@1.3.0b DONE}
		Druidcraft-1.14-0.2.32.jar Druidcraft {druidcraft@0.2.32 DONE}
		FallingTree-1.14.4-1.1.0+8.jar Falling Tree {falling_tree@1.1.0+8 DONE}
		AttributeFix-1.14.4-3.0.2.jar AttributeFix {attributefix@3.0.2 DONE}
		caelus-FORGE-1.14.4-1.0.1.1.jar Caelus API {caelus@FORGE-1.14.4-1.0.1.1 DONE}
		colytra-FORGE-1.14.4-2.1.0.jar Colytra {colytra@FORGE-1.14.4-2.1.0 DONE}
		create-mc1.14.4_v0.1.1a.jar Create {create@0.1.1a DONE}
		Waystones_1.14.4-5.0.1.jar Waystones {waystones@5.0.1 DONE}
		Clumps-4.0.0.jar Clumps {clumps@4.0.0 DONE}
		comforts-FORGE-1.14.4-2.0-beta4.jar Comforts {comforts@FORGE-1.14.4-2.0-beta4 DONE}
		NaturesCompass-1.14.4-1.8.3.jar Nature's Compass {naturescompass@1.14.4-1.8.3 DONE}
		SimpleStorageNetwork-1.14.4-0.2.0.jar Simple Storage Network {storagenetwork@1.14.4-0.2.0 DONE}
		BotanyPots-1.14.4-1.0.8.jar BotanyPots {botanypots@1.0.8 DONE}
		PyramidPlunder-1.14.4-1.1.jar Pyramid Plunder {pyramidplunder@1.14.4-1.0 DONE}
		curioofundying-FORGE-1.14.4-2.0.jar Curio of Undying {curioofundying@FORGE-1.14.4-2.0 DONE}
		FarmingForBlockheads_1.14.4-5.3.2.jar Farming for Blockheads {farmingforblockheads@5.3.2 DONE}
		shb_1.14-1.0.jar Softer Hay Bales {shb@1.0 DONE}
		travellersboots-1.14.4-1.2.2.jar Traveller's Boots {travellersboots@1.2.2 DONE}
		mininggadgets-1.2.3.jar Mining Gadgets {mininggadgets@1.2.3 DONE}
		endercompass-1.1.jar Ender Compass {endercompass@1.1 DONE}
		mysticalworld-1.14.4-1.7.1.jar Mystical World {mysticalworld@1.14.4-1.7.1 DONE}
		forge-1.14.4-28.1.114-universal.jar Forge {forge@28.1.114 DONE}
		SimpleDivingGear-3.0.4 mc 1.14.4.jar Simple Diving Gear {simpledivegear@3.0.4 mc 1.14.4 DONE}
		forge-1.14.4-28.1.114-client.jar Minecraft {minecraft@1.14.4 DONE}
		theoneprobe-1.14-1.4.37.jar The One Probe {theoneprobe@NONE DONE}
		swingthroughgrass-1.14.4-1.3.2.jar SwingThroughGrass {swingthroughgrass@1.14.4-1.3.2 DONE}
		playerplates-1.14.4-forge-1.1.0.jar Player Plates {playerplates@1.14.4-forge-1.1.0 DONE}
		ToolBelt-1.14.4-1.12.5.jar Tool Belt {toolbelt@1.12.5 DONE}
		Compacted-1.14-1.3.0.jar Compacted {compacted@1.2.0 DONE}
		travel_bag-1.0.6-1.14.4.jar Travel Bag {travel_bag@1.0.6 DONE}
		bluepower-1.14.4-0.3.172-alpha-universal.jar Blue Power {bluepower@0.3.172-alpha DONE}
		TeaAndBiscuits-1.7.jar teaandbiscuits {teaandbiscuits@1.7 DONE}
		gates-1.5.0.jar Gates {gates@1.5.0 DONE}
		astikorcarts-1.0.0.1.jar AstikorCarts {astikorcarts@NONE DONE}
		Quark-r2.0-209.jar Quark {quark@r2.0-209 DONE}
		Xaeros_Minimap_1.19.7_Forge_1.14.4.jar Xaero's Minimap {xaerominimap@1.19.7 DONE}
		recycler-1.0.0.jar Recycler {recycler@1.0.0 DONE}
		mysticalmachinery-1.14.4-0.0.0.3.jar Mystical Machinery {mysticalmachinery@1.14.4-0.0.0.3 DONE}
		AppleSkin-mc1.14.4-forge-1.0.13.jar AppleSkin {appleskin@1.0.13 DONE}
		mobcatcher-1.2b.jar Mob Catcher {mobcatcher@1.2b DONE}
		CraftingCraft_1.14.4-7.1.7.jar CraftingCraft {craftingcraft@7.1.7 DONE}
		overloadedarmorbar-3.0.0b.jar Overloaded Armor Bar {overloadedarmorbar@3.0.0b DONE}
	Kiwi Modules: 
		chineseworkshop:blocks
		chineseworkshop:debug_stick
		chineseworkshop:decorations
		chineseworkshop:materials
		chineseworkshop:retexture
		kiwi:contributors
	Player Count: 1 / 8; [ServerPlayerEntity['StrangeThistle'/202, l='Maximum Overdrive', x=152.28, y=64.00, z=134.59]]
	Data Packs: vanilla, mod:apotheosis, mod:appleskin, mod:arl, mod:astikorcarts, mod:attributefix, mod:blockdrops, mod:bluepower, mod:bookshelf, mod:botanypots, mod:bountifulbaubles, mod:buildinggadgets, mod:caelus, mod:carryon, mod:charm, mod:chineseworkshop, mod:chunknogobyebye, mod:clumps, mod:colytra, mod:comforts, mod:compacted, mod:compatchedstorage, mod:cookingforblockheads, mod:corail_woodcutter, mod:craftingcraft, mod:create, mod:curioofundying, mod:curios, mod:curiouselytra, mod:curiousshulkerboxes, mod:cyclic, mod:dimensionalores, mod:druidcraft, mod:dwmh, mod:eggs (incompatible), mod:endercompass, mod:extendedfoods, mod:falling_tree, mod:farmingforblockheads, mod:fastleafdecay, mod:fencejumper, mod:flying_things, mod:forge, mod:gates, mod:gravelminer, mod:instantunify, mod:jei, mod:jeresources (incompatible), mod:kiwi, mod:lollipop, mod:longfallboots, mod:lostcities, mod:masonry, mod:mcwbridges, mod:mcwroofs, mod:metalbarrels, mod:mining_helmet, mod:mininggadgets, mod:mobcatcher, mod:modnametooltip, mod:moreoverlays, mod:mysticallib, mod:mysticalmachinery, mod:mysticalworld, mod:naturescompass, mod:nosoliciting, mod:oreexcavation, mod:overloadedarmorbar, mod:patchouli, mod:placebo, mod:platforms, mod:playerplates, mod:powah, mod:prettybeaches, mod:pyramidplunder, mod:quark, mod:quartzchests, mod:rangedpumps, mod:recycler, mod:rsgauges, mod:shb, mod:shetiphiancore, mod:simpledivegear, mod:storagenetwork, mod:swingthroughgrass, mod:teaandbiscuits, mod:theoneprobe, mod:tombstone, mod:toolbelt, mod:travel_bag, mod:travellersboots, mod:walkthroughberries, mod:waystones, mod:wstweaks, mod:xaerominimap, mod:xaeroworldmap, mod:yamda, file/bluepower, mod:firefly, mod:wishingforsunshine (incompatible)
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'forge'

**Comment by McJty** [comment]
I will fix this

**Comment by McJty** [comment]
Fixed

**Comment by StrangeThistle** [comment]
Fix confirmed.  :-)
