### ISSUE TITLE
crashes on chunk gen version 1.14-2.0.28-alpha

### ISSUE THREAD

**Issue by superdude808** [McJty/LostCities#265]
i ain't got much experience in coding but i can tell it's lost cities doing this, don't know why tho was working fine for awhile only started  doing this when i started a new world coz my old hard core one died, anyway here's the crash log.

---- Minecraft Crash Report ----
// Why is it breaking :(

Time: 3/4/20 4:10 PM
Description: Feature placement

java.lang.NullPointerException: Null part for null
	at org.apache.commons.lang3.Validate.notNull(Validate.java:225) ~[commons-lang3-3.5.jar:3.5] {}
	at mcjty.lostcities.worldgen.lost.BuildingInfo.<init>(BuildingInfo.java:843) ~[?:1.14-2.0.28-alpha] {re:classloading}
	at mcjty.lostcities.worldgen.lost.BuildingInfo.getBuildingInfo(BuildingInfo.java:666) ~[?:1.14-2.0.28-alpha] {re:classloading}
	at mcjty.lostcities.worldgen.lost.BuildingInfo.getZmin(BuildingInfo.java:274) ~[?:1.14-2.0.28-alpha] {re:classloading}
	at mcjty.lostcities.worldgen.lost.BuildingInfo.calculateTopLeft(BuildingInfo.java:545) ~[?:1.14-2.0.28-alpha] {re:classloading}
	at mcjty.lostcities.worldgen.lost.BuildingInfo.<init>(BuildingInfo.java:736) ~[?:1.14-2.0.28-alpha] {re:classloading}
	at mcjty.lostcities.worldgen.lost.BuildingInfo.getBuildingInfo(BuildingInfo.java:666) ~[?:1.14-2.0.28-alpha] {re:classloading}
	at mcjty.lostcities.worldgen.lost.BuildingInfo.getXmin(BuildingInfo.java:260) ~[?:1.14-2.0.28-alpha] {re:classloading}
	at mcjty.lostcities.worldgen.lost.BuildingInfo.calculateTopLeft(BuildingInfo.java:547) ~[?:1.14-2.0.28-alpha] {re:classloading}
	at mcjty.lostcities.worldgen.lost.BuildingInfo.<init>(BuildingInfo.java:736) ~[?:1.14-2.0.28-alpha] {re:classloading}
	at mcjty.lostcities.worldgen.lost.BuildingInfo.getBuildingInfo(BuildingInfo.java:666) ~[?:1.14-2.0.28-alpha] {re:classloading}
	at mcjty.lostcities.worldgen.lost.BuildingInfo.getZmin(BuildingInfo.java:274) ~[?:1.14-2.0.28-alpha] {re:classloading}
	at mcjty.lostcities.worldgen.lost.BuildingInfo.getLowestCityHeightAtChunkCorner(BuildingInfo.java:1595) ~[?:1.14-2.0.28-alpha] {re:classloading}
	at mcjty.lostcities.worldgen.lost.BuildingInfo.updateMinMaxL1(BuildingInfo.java:1707) ~[?:1.14-2.0.28-alpha] {re:classloading}
	at mcjty.lostcities.worldgen.lost.BuildingInfo.getDesiredMaxHeightL1(BuildingInfo.java:1648) ~[?:1.14-2.0.28-alpha] {re:classloading}
	at mcjty.lostcities.worldgen.lost.BuildingInfo.updateMinMaxL2(BuildingInfo.java:1696) ~[?:1.14-2.0.28-alpha] {re:classloading}
	at mcjty.lostcities.worldgen.lost.BuildingInfo.getDesiredMaxHeightL2(BuildingInfo.java:1680) ~[?:1.14-2.0.28-alpha] {re:classloading}
	at mcjty.lostcities.worldgen.LostCityTerrainFeature.correctTerrainShape(LostCityTerrainFeature.java:801) ~[?:1.14-2.0.28-alpha] {re:classloading}
	at mcjty.lostcities.worldgen.LostCityTerrainFeature.doNormalChunk(LostCityTerrainFeature.java:431) ~[?:1.14-2.0.28-alpha] {re:classloading}
	at mcjty.lostcities.worldgen.LostCityTerrainFeature.generate(LostCityTerrainFeature.java:311) ~[?:1.14-2.0.28-alpha] {re:classloading}
	at mcjty.lostcities.worldgen.LostCityFeature.place(LostCityFeature.java:38) ~[?:1.14-2.0.28-alpha] {re:classloading}
	at mcjty.lostcities.worldgen.LostCityFeature.func_212245_a(LostCityFeature.java:20) ~[?:1.14-2.0.28-alpha] {re:classloading}
	at net.minecraft.world.gen.feature.ConfiguredFeature.func_222734_a(SourceFile:36) ~[?:?] {re:classloading}
	at net.minecraft.world.gen.placement.Placement.lambda$place$0(Placement.java:72) ~[?:?] {re:classloading}
	at net.minecraft.world.gen.placement.Placement$$Lambda$7984/1973984132.accept(Unknown Source) ~[?:?] {}
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184) ~[?:1.8.0_51] {}
	at java.util.stream.IntPipeline$4$1.accept(IntPipeline.java:250) ~[?:1.8.0_51] {}
	at java.util.stream.Streams$RangeIntSpliterator.forEachRemaining(Streams.java:110) ~[?:1.8.0_51] {}
	at java.util.Spliterator$OfInt.forEachRemaining(Spliterator.java:693) ~[?:1.8.0_51] {}
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:512) ~[?:1.8.0_51] {}
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:502) ~[?:1.8.0_51] {}
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151) ~[?:1.8.0_51] {}
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174) ~[?:1.8.0_51] {}
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:1.8.0_51] {}
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418) ~[?:1.8.0_51] {}
	at net.minecraft.world.gen.placement.Placement.func_214998_a(Placement.java:71) ~[?:?] {re:classloading}
	at net.minecraft.world.gen.placement.ConfiguredPlacement.func_215093_a(SourceFile:35) ~[?:?] {re:classloading}
	at net.minecraft.world.gen.feature.DecoratedFeature.func_212245_a(SourceFile:20) ~[?:?] {re:classloading}
	at net.minecraft.world.gen.feature.DecoratedFeature.func_212245_a(SourceFile:13) ~[?:?] {re:classloading}
	at net.minecraft.world.gen.feature.ConfiguredFeature.func_222734_a(SourceFile:36) ~[?:?] {re:classloading}
	at net.minecraft.world.biome.Biome.func_203608_a(Biome.java:283) ~[?:?] {re:classloading,pl:accesstransformer:B,xf:fml:sereneseasons:temperature_transformer,xf:fml:environs:environs_biome_transformer}
	at net.minecraft.world.gen.ChunkGenerator.func_202092_b(ChunkGenerator.java:104) ~[?:?] {re:classloading}
	at net.minecraft.world.chunk.ChunkStatus.lambda$static$9(ChunkStatus.java:73) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.world.chunk.ChunkStatus$$Lambda$1570/1155636121.doWork(Unknown Source) ~[?:?] {}
	at net.minecraft.world.chunk.ChunkStatus.func_223198_a(ChunkStatus.java:196) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.world.server.ChunkManager.lambda$null$17(ChunkManager.java:509) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.world.server.ChunkManager$$Lambda$7881/577008947.apply(Unknown Source) ~[?:?] {}
	at com.mojang.datafixers.util.Either$Left.map(Either.java:38) ~[datafixerupper-2.0.24.jar:?] {}
	at net.minecraft.world.server.ChunkManager.lambda$func_223156_b$19(ChunkManager.java:507) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.world.server.ChunkManager$$Lambda$7878/2106565067.apply(Unknown Source) ~[?:?] {}
	at java.util.concurrent.CompletableFuture.uniCompose(CompletableFuture.java:952) ~[?:1.8.0_51] {}
	at java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:926) ~[?:1.8.0_51] {}
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:442) ~[?:1.8.0_51] {}
	at net.minecraft.world.chunk.ChunkTaskPriorityQueueSorter.func_219083_b(SourceFile:58) ~[?:?] {re:classloading}
	at net.minecraft.world.chunk.ChunkTaskPriorityQueueSorter$$Lambda$7808/794329818.run(Unknown Source) ~[?:?] {}
	at net.minecraft.util.concurrent.DelegatedTaskExecutor.func_213148_e(SourceFile:83) ~[?:?] {re:classloading}
	at net.minecraft.util.concurrent.DelegatedTaskExecutor.func_213145_a(SourceFile:123) ~[?:?] {re:classloading}
	at net.minecraft.util.concurrent.DelegatedTaskExecutor.run(SourceFile:91) ~[?:?] {re:classloading}
	at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1402) ~[?:1.8.0_51] {}
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289) ~[?:1.8.0_51] {}
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056) ~[?:1.8.0_51] {}
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1689) ~[?:1.8.0_51] {}
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157) ~[?:1.8.0_51] {}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at org.apache.commons.lang3.Validate.notNull(Validate.java:225)
	at mcjty.lostcities.worldgen.lost.BuildingInfo.<init>(BuildingInfo.java:843)
	at mcjty.lostcities.worldgen.lost.BuildingInfo.getBuildingInfo(BuildingInfo.java:666)
	at mcjty.lostcities.worldgen.lost.BuildingInfo.getZmin(BuildingInfo.java:274)
	at mcjty.lostcities.worldgen.lost.BuildingInfo.calculateTopLeft(BuildingInfo.java:545)
	at mcjty.lostcities.worldgen.lost.BuildingInfo.<init>(BuildingInfo.java:736)
	at mcjty.lostcities.worldgen.lost.BuildingInfo.getBuildingInfo(BuildingInfo.java:666)
	at mcjty.lostcities.worldgen.lost.BuildingInfo.getXmin(BuildingInfo.java:260)
	at mcjty.lostcities.worldgen.lost.BuildingInfo.calculateTopLeft(BuildingInfo.java:547)
	at mcjty.lostcities.worldgen.lost.BuildingInfo.<init>(BuildingInfo.java:736)
	at mcjty.lostcities.worldgen.lost.BuildingInfo.getBuildingInfo(BuildingInfo.java:666)
	at mcjty.lostcities.worldgen.lost.BuildingInfo.getZmin(BuildingInfo.java:274)
	at mcjty.lostcities.worldgen.lost.BuildingInfo.getLowestCityHeightAtChunkCorner(BuildingInfo.java:1595)
	at mcjty.lostcities.worldgen.lost.BuildingInfo.updateMinMaxL1(BuildingInfo.java:1707)
	at mcjty.lostcities.worldgen.lost.BuildingInfo.getDesiredMaxHeightL1(BuildingInfo.java:1648)
	at mcjty.lostcities.worldgen.lost.BuildingInfo.updateMinMaxL2(BuildingInfo.java:1696)
	at mcjty.lostcities.worldgen.lost.BuildingInfo.getDesiredMaxHeightL2(BuildingInfo.java:1680)
	at mcjty.lostcities.worldgen.LostCityTerrainFeature.correctTerrainShape(LostCityTerrainFeature.java:801)
	at mcjty.lostcities.worldgen.LostCityTerrainFeature.doNormalChunk(LostCityTerrainFeature.java:431)
	at mcjty.lostcities.worldgen.LostCityTerrainFeature.generate(LostCityTerrainFeature.java:311)
	at mcjty.lostcities.worldgen.LostCityFeature.place(LostCityFeature.java:38)
	at mcjty.lostcities.worldgen.LostCityFeature.func_212245_a(LostCityFeature.java:20)
	at net.minecraft.world.gen.feature.ConfiguredFeature.func_222734_a(SourceFile:36)
	at net.minecraft.world.gen.placement.Placement.lambda$place$0(Placement.java:72)
	at net.minecraft.world.gen.placement.Placement$$Lambda$7984/1973984132.accept(Unknown Source)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
	at java.util.stream.IntPipeline$4$1.accept(IntPipeline.java:250)
	at java.util.stream.Streams$RangeIntSpliterator.forEachRemaining(Streams.java:110)
	at java.util.Spliterator$OfInt.forEachRemaining(Spliterator.java:693)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:512)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:502)
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
	at net.minecraft.world.gen.placement.Placement.func_214998_a(Placement.java:71)
	at net.minecraft.world.gen.placement.ConfiguredPlacement.func_215093_a(SourceFile:35)
	at net.minecraft.world.gen.feature.DecoratedFeature.func_212245_a(SourceFile:20)
	at net.minecraft.world.gen.feature.DecoratedFeature.func_212245_a(SourceFile:13)
	at net.minecraft.world.gen.feature.ConfiguredFeature.func_222734_a(SourceFile:36)

-- Feature --
Details:
	Id: minecraft:decorated
	Description: < DecoratedFeature [minecraft:decorated] >
Stacktrace:
	at net.minecraft.world.biome.Biome.func_203608_a(Biome.java:283)

-- Generation --
Details:
	CenterX: 11
	CenterZ: -3
	Step: RAW_GENERATION
	Seed: 1908931017888734118
	Biome: minecraft:plains
Stacktrace:
	at net.minecraft.world.gen.ChunkGenerator.func_202092_b(ChunkGenerator.java:104)
	at net.minecraft.world.chunk.ChunkStatus.lambda$static$9(ChunkStatus.java:73)
	at net.minecraft.world.chunk.ChunkStatus$$Lambda$1570/1155636121.doWork(Unknown Source)
	at net.minecraft.world.chunk.ChunkStatus.func_223198_a(ChunkStatus.java:196)

-- Chunk to be generated --
Details:
	Location: 11,-3
	Position hash: -12884901877
	Generator: net.minecraft.world.gen.OverworldChunkGenerator@6109e820
Stacktrace:
	at net.minecraft.world.server.ChunkManager.lambda$null$17(ChunkManager.java:509)
	at net.minecraft.world.server.ChunkManager$$Lambda$7881/577008947.apply(Unknown Source)
	at com.mojang.datafixers.util.Either$Left.map(Either.java:38)
	at net.minecraft.world.server.ChunkManager.lambda$func_223156_b$19(ChunkManager.java:507)
	at net.minecraft.world.server.ChunkManager$$Lambda$7878/2106565067.apply(Unknown Source)
	at java.util.concurrent.CompletableFuture.uniCompose(CompletableFuture.java:952)
	at java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:926)
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:442)
	at net.minecraft.world.chunk.ChunkTaskPriorityQueueSorter.func_219083_b(SourceFile:58)
	at net.minecraft.world.chunk.ChunkTaskPriorityQueueSorter$$Lambda$7808/794329818.run(Unknown Source)
	at net.minecraft.util.concurrent.DelegatedTaskExecutor.func_213148_e(SourceFile:83)
	at net.minecraft.util.concurrent.DelegatedTaskExecutor.func_213145_a(SourceFile:123)
	at net.minecraft.util.concurrent.DelegatedTaskExecutor.run(SourceFile:91)

-- Affected level --
Details:
	All players: 1 total; [ServerPlayerEntity['superdudette808'/533, l='Hulasikali Wala', x=133.27, y=68.00, z=120.72]]
	Chunk stats: ServerChunkCache: 2102
	Level dimension: DimensionType{minecraft:overworld}
	Level name: Hulasikali Wala
	Level seed: 3029830
	Level generator: ID 00 - default, ver 1. Features enabled: true
	Level generator options: {}
	Level spawn location: World: (176,69,161), Chunk: (at 0,4,1 in 11,10; contains blocks 176,0,160 to 191,255,175), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 838 game time, 838 day time
	Level storage version: 0x04ABD - Anvil
	Level weather: Rain time: 177278 (now: false), thunder time: 25432 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: true
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:832)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:764)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:112)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:622)
	at java.lang.Thread.run(Thread.java:745)

-- System Details --
Details:
	Minecraft Version: 1.14.4
	Minecraft Version ID: 1.14.4
	Operating System: Windows 7 (amd64) version 6.1
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 743387632 bytes (708 MB) / 3252158464 bytes (3101 MB) up to 5488246784 bytes (5234 MB)
	CPUs: 8
	JVM Flags: 5 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx5888m -Xms256m -XX:PermSize=256m
	ModLauncher: 4.1.0+62+5bfa59b
	ModLauncher launch target: fmlclient
	ModLauncher naming: srg
	ModLauncher services: 
		/eventbus-1.0.0-service.jar eventbus PLUGINSERVICE 
		/forge-1.14.4-28.2.1.jar object_holder_definalize PLUGINSERVICE 
		/forge-1.14.4-28.2.1.jar runtime_enum_extender PLUGINSERVICE 
		/accesstransformers-1.0.1-milestone.0.1+94458e7-shadowed.jar accesstransformer PLUGINSERVICE 
		/forge-1.14.4-28.2.1.jar capability_inject_definalize PLUGINSERVICE 
		/forge-1.14.4-28.2.1.jar runtimedistcleaner PLUGINSERVICE 
		/forge-1.14.4-28.2.1.jar fml TRANSFORMATIONSERVICE 
	FML: 28.2
	Forge: net.minecraftforge:28.2.1
	FML Language Providers: 
		javafml@28.2
		minecraft@1
	Mod List: 
		enchantedbookredesign-1.1.jar Enchanted Book Redesign {enchantedbookredesign@1.1 DONE}
		decorative_blocks_compat_1.jar Decorative Blocks Compat {decorative_blocks_compat@1.0 DONE}
		vilnames_1.14-1.4.jar Villager Names {vilnames@1.4 DONE}
		mcw-windows-1.0.0-mc1.14.4.jar Macaw's Windows {mcwwindows@1.0.0 DONE}
		ManCatcher_1.14.4_1.0.2.jar ManCatcher {mancatcher@1.0.0 DONE}
		CookingForBlockheads_1.14.4-7.4.3.jar Cooking for Blockheads {cookingforblockheads@7.4.3 DONE}
		Placebo-1.14.4-2.3.5.jar Placebo {placebo@2.3.5 DONE}
		potionsmaster-0.0.6-1.14.4-28.1.114.jar Potions Master {potionsmaster@0.0.6 DONE}
		NomadicTents-1.14.4-10.1.0.jar Nomadic Tents {nomadictents@10.1.0 DONE}
		WitherSkeletonTweaks-1.14.4-3.1.0.jar Wither Skeleton Tweaks {wstweaks@3.1.0 DONE}
		branders-enhanced-mob-spawners-v1.14.4-1.4.3.jar Enhanced Mob Spawners {spawnermod@1.4.4 DONE}
		ironshulkerboxes-1.14.4-3.1.12.jar Iron Shulker Boxes {ironshulkerbox@1.14.4-3.1.12 DONE}
		PickUpNotifier-v1.1.2-1.14.4.jar Pick Up Notifier {pickupnotifier@1.1.2 DONE}
		WaterStrainer-1.14.4-7.0.2.jar Water Strainer {waterstrainer@1.14.4-7.0.2 DONE}
		stone-age-1.14.4-1.1.4.jar Stone Age {stone_age@1.14.4-1.1.4 DONE}
		Wither+Totem+0.1.jar Wither Skeleton Totems {totemmod@0.1 DONE}
		CarryOn+MC1.14.4+v1.12.4.jar Carry On {carryon@1.12.4 DONE}
		JustEnoughResources-1.14.4-0.10.1.74.jar Just Enough Resources {jeresources@0.10.1.74 DONE}
		Paraglider-1.14.4-1.1.0.2.jar Paraglider {paraglider@1.1.0.2 DONE}
		shetiphiancore-1.14-3.6.1.jar ShetiPhian-Core {shetiphiancore@3.6.1 DONE}
		absentbydesign-1.14.4-1.0.5.jar Absent By Design Mod {absentbydesign@1.14.4-1.0.5 DONE}
		lavawaderbauble-3.1.jar Lava Wader Bauble {lavawaderbauble@3.1 DONE}
		mcw-bridges-1.0.3-mc1.14.4.jar Macaw's Bridges {mcwbridges@1.0.3 DONE}
		embellishcraft-1.14.4-1.4.1.jar EmbellishCraft {embellishcraft@1.14.4-1.4.1 DONE}
		AmbientSounds_v3.0.14_mc1.14.4.jar Ambient Sounds {ambientsounds@3.0.3 DONE}
		valhelsia_structures-1.14.4-0.0.2a.jar Valhelsia Structures {valhelsia_structures@1.14.4-0.0.2a DONE}
		extcaves-1.5.jar Extended Caves {extcaves@1.5 DONE}
		Uncharted_1.14.4_v05.jar Uncharted {uncharted@v05 DONE}
		simplefarming-1.14.4-1.2.8.jar Simple Farming {simplefarming@1.14.4-1.2.8 DONE}
		fairylights-2.1.15-1.14.4.jar Fairy Lights {fairylights@2.1.15 DONE}
		horsemodifiers-1.2.2.jar Horse Modifiers {horsemodifiers@1.2.2 DONE}
		curios-FORGE-1.14.4-1.0.6.1.jar Curios API {curios@FORGE-1.14.4-1.0.6.1 DONE}
		corail_woodcutter-1.1.1-1.14.4.jar Corail Woodcutter {corail_woodcutter@1.1.1 DONE}
		AutoRegLib-1.4-35.jar AutoRegLib {arl@1.4-35 DONE}
		extlights-1.8.jar Extended Lights {extlights@1.8 DONE}
		ages-api-1.14.4-1.0.5.jar Ages API {ages_api@1.14.4-1.0.5 DONE}
		lostcities-1.14-2.0.28-alpha.jar LostCities {lostcities@1.14-2.0.28-alpha DONE}
		tombstone-4.2.3-1.14.4.jar Corail Tombstone {tombstone@4.2.3 DONE}
		mcw-roofs-1.0.2-mc1.14.4.jar Macaw's Roofs {mcwroofs@1.0.2 DONE}
		curiouselytra-FORGE-1.14.4-1.0.jar Curious Elytra {curiouselytra@FORGE-1.14.4-1.0 DONE}
		biomeinfo-1.14.4-v1.2.5.jar BiomeInfo {biomeinfo@v1.2.5 DONE}
		mcw-furnitures-1.0.0-mc1.14.4.jar Macaw's Furniture {mcwfurnitures@1.0.0 DONE}
		BetterBurning-1.14.4-1.0.1.jar BetterBurning {betterburning@1.0.1 DONE}
		incubation-1.0.1-1.14.4.jar Incubation {incubation@1.0.1 DONE}
		ScalingHealth-1.14.4-2.4.1+44.jar Scaling Health {scalinghealth@2.4.1+44 DONE}
		Disenchanting_(forge)_1.14.4-1.1.1.jar Disenchanting {disenchanting@1.1.1 DONE}
		Cyclic-1.14.4-0.1.2.jar Cyclic {cyclic@1.14.4-0.1.2 DONE}
		SaveMyStronghold-1.14.4-1.0.0.jar Save My Stronghold! {savemystronghold@1.14.4-1.0.0 DONE}
		SoundControl-1.14.4-0.1.0.0.jar Â§3Dynamic Surroundings: Â§eSound Control {sndctrl@1.14.4-0.1.0.0 DONE}
		flamboyant-1.0.4.jar Flamboyant {flamboyant@1.0.4 DONE}
		Berry-Good-1.14.4-v1.0.3.jar Berry Good {berry_good@1.0.3 DONE}
		wolfrevivemod-1.1.jar Collar Catcher: Dog Revival Mod! {wolfrevivemod@1.1 DONE}
		bountifulbaubles-1.14.4-0.0.2.jar Bountiful Baubles {bountifulbaubles@NONE DONE}
		bambooblocks-1.2.12.jar Bamboo Blocks {bambooblocks@1.2.11 DONE}
		platforms-1.14-1.5.1.jar Platforms {platforms@1.5.0 DONE}
		jei-1.14.4-6.0.0.27.jar Just Enough Items {jei@6.0.0.27 DONE}
		vanillathings-1.14.4-0.4.4.jar Vanilla Things {vanillathings@0.4.4 DONE}
		Druidcraft-1.14-0.3.0.jar Druidcraft {druidcraft@0.3.0 DONE}
		BirdsNestsAndTreasures-1.14.4-1.0.0.jar Birds Nests & Treasures {birdsneststres@1.0.0 DONE}
		AttributeFix-1.14.4-3.0.3.jar AttributeFix {attributefix@3.0.3 DONE}
		caelus-FORGE-1.14.4-1.0.1.2.jar Caelus API {caelus@FORGE-1.14.4-1.0.1.2 DONE}
		Upgrade-Aquatic-1.14.4-v1.4.10.jar Upgrade Aquatic {upgrade_aquatic@1.4.9 DONE}
		extraboats-1.2.3-1.14.4.jar Extra Boats {extraboats@1.2.3 DONE}
		FloristV1.1.4.jar Florist {florist@1.1.4 DONE}
		ensorcellation-1.14.4-0.2.0b.jar Ensorcellation {ensorcellation@0.2.0b DONE}
		Waystones_1.14.4-5.1.1.jar Waystones {waystones@5.1.1 DONE}
		WallpaperCraft-1.14.4-1.0.6.jar Wallpapercraft {wallpapercraft@1.0.6 DONE}
		NaturesCompass-1.14.4-1.8.5.jar Nature's Compass {naturescompass@1.14.4-1.8.5 DONE}
		SereneSeasons-1.14.4-2.0.0.40-universal.jar Serene Seasons {sereneseasons@1.14.4-2.0.0.40 DONE}
		decorative_blocks_6.jar Decorative Blocks {decorative_blocks@1.5 DONE}
		curioofundying-FORGE-1.14.4-2.0.jar Curio of Undying {curioofundying@FORGE-1.14.4-2.0 DONE}
		cofh_core-1.14.4-0.2.0b.jar CoFH Core {cofh_core@0.2.0b DONE}
		firstaid-1.7.11.jar First Aid {firstaid@1.7.11 DONE}
		forge-1.14.4-28.2.1-universal.jar Forge {forge@28.2.1 DONE}
		ironchest-1.14.4-9.1.5.jar Iron Chests {ironchest@1.14.3-9.0.3 DONE}
		forge-1.14.4-28.2.1-client.jar Minecraft {minecraft@1.14.4 DONE}
		Environs-1.14.4-0.1.0.0.jar Â§3Dynamic Surroundings: Â§eEnvirons {environs@1.14.4-0.1.0.0 DONE}
		theoneprobe-1.14-1.4.37.jar The One Probe {theoneprobe@NONE DONE}
		watercan-1.14.4-2.1.0.jar Watercan {watercan@1.14.4-2.1.0 DONE}
		SilentLib-1.14.4-4.4.0+44.jar Silent Lib {silentlib@4.4.0+44 DONE}
		modifiers-0.0.1.jar Modifiers {modifiers@NONE DONE}
		ceramicshears-1.0.1-1.14.4_1.15.X.jar Ceramic Shears {ceramicshears@1.0.1-1.14.4 DONE}
		MobEffects-1.14.4-0.1.0.0.jar Â§3Dynamic Surroundings: Â§eMob Effects {mobeffects@1.14.4-0.1.0.0 DONE}
		extragolems-9.0.5.jar Extra Golems {golems@9.0.5 DONE}
		SpartanShields-1.14.4-2.0.0.jar Spartan Shields {spartanshields@2.0.0 DONE}
		Quark-r2.0-211.jar Quark {quark@r2.0-211 DONE}
		Xaeros_Minimap_20.4.0.1_Forge_1.14.4.jar Xaero's Minimap {xaerominimap@20.4.0.1 DONE}
		FastWorkbench-1.14.4-2.1.4.jar FastWorkbench {fastbench@2.1.4 DONE}
		multibeds-1.14-1.5.2.jar Multi-Beds {multibeds@1.5.0 DONE}
		corail_recycler-4.0.2-1.14.4.jar Corail Recycler {corail_recycler@4.0.2 DONE}
		StorageDrawers-1.14.4-6.0.6.jar Storage Drawers {storagedrawers@1.14.4-6.0.6 DONE}
		backpacked-1.4.0-1.14.4.jar Backpacked {backpacked@1.4.0 DONE}
		themidnight-0.4.6.jar The Midnight {midnight@0.4.6 DONE}
		simplytea-2.0.4.jar Simply Tea {simplytea@2.0.4 DONE}
		grindr-1.14.4-0.0.0.9.jar Grindr {grindr@NONE DONE}
		dispensebreaker-1.14.4-1.0.jar Dispense Breaker {dispensebreaker@1.0 DONE}
		RefinedRelocation_1.14.4-6.2.6.jar Refined Relocation {refinedrelocation@6.2.6 DONE}
		ilikewood-1.14.4-1.1.2.3.jar I Like Wood {ilikewood@1.1.2.3 DONE}
		Aquaculture-1.14.4-2.0.7.jar Aquaculture 2 {aquaculture@1.14.4-2.0.7 DONE}
		FriendlyFire-1.14.4-3.0.2.jar FriendlyFire {friendlyfire@3.0.2 DONE}
		CHAS+v1.3+for+1.14.jar Craftable Horse Armour {craftablehorsearmour@1.3 DONE}
	Player Count: 1 / 8; [ServerPlayerEntity['superdudette808'/533, l='Hulasikali Wala', x=133.27, y=68.00, z=120.72]]
	Data Packs: vanilla, mod:absentbydesign, mod:ages_api, mod:ambientsounds, mod:aquaculture, mod:arl, mod:attributefix, mod:backpacked, mod:bambooblocks, mod:berry_good, mod:betterburning, mod:biomeinfo, mod:birdsneststres, mod:bountifulbaubles, mod:caelus, mod:carryon, mod:ceramicshears, mod:cofh_core, mod:cookingforblockheads, mod:corail_recycler, mod:corail_woodcutter, mod:craftablehorsearmour, mod:curioofundying, mod:curios, mod:curiouselytra, mod:cyclic, mod:decorative_blocks, mod:disenchanting, mod:dispensebreaker, mod:druidcraft, mod:embellishcraft, mod:enchantedbookredesign, mod:ensorcellation, mod:environs, mod:extcaves, mod:extlights, mod:extraboats, mod:fairylights, mod:fastbench, mod:firstaid, mod:flamboyant, mod:florist, mod:forge, mod:friendlyfire, mod:golems, mod:grindr, mod:horsemodifiers, mod:ilikewood, mod:incubation, mod:ironchest, mod:ironshulkerbox, mod:jei, mod:jeresources (incompatible), mod:lavawaderbauble, mod:lostcities, mod:mancatcher, mod:mcwbridges, mod:mcwfurnitures, mod:mcwroofs (incompatible), mod:mcwwindows, mod:midnight, mod:mobeffects, mod:modifiers, mod:multibeds, mod:naturescompass, mod:nomadictents, mod:paraglider, mod:pickupnotifier, mod:placebo, mod:platforms, mod:potionsmaster, mod:quark, mod:refinedrelocation, mod:savemystronghold, mod:scalinghealth, mod:sereneseasons, mod:shetiphiancore, mod:silentlib, mod:simplefarming, mod:simplytea, mod:sndctrl, mod:spartanshields, mod:spawnermod, mod:stone_age, mod:storagedrawers, mod:theoneprobe, mod:tombstone, mod:totemmod, mod:uncharted, mod:upgrade_aquatic, mod:valhelsia_structures, mod:vanillathings, mod:vilnames, mod:wallpapercraft, mod:watercan, mod:waterstrainer, mod:waystones, mod:wolfrevivemod, mod:wstweaks, mod:xaerominimap, mod:decorative_blocks_compat
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'forge'

**Comment by McJty** [comment]
Best move to the 1.15 version as I no longer work on the 1.14 versions
