### ISSUE TITLE
Throwing Eyes of Ender sometimes doesn't work in a Lost Cities world

### ISSUE THREAD

**Issue by snydej** [McJty/LostCities#310]
Sometimes throwing an Eye of Ender doesn't work and instead results in this stack trace being logged:

java.util.concurrent.ExecutionException: java.lang.NullPointerException
	at java.util.concurrent.FutureTask.report(Unknown Source) ~[?:1.8.0_212]
	at java.util.concurrent.FutureTask.get(Unknown Source) ~[?:1.8.0_212]
	at net.minecraft.util.Util.func_181617_a(SourceFile:47) [h.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:723) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668) [MinecraftServer.class:?]
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:185) [chd.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_212]
Caused by: java.lang.NullPointerException
	at net.minecraft.world.gen.structure.MapGenStronghold.func_189104_c(MapGenStronghold.java:141) ~[bbs.class:?]
	at net.minecraft.world.gen.structure.MapGenStronghold.func_180706_b(MapGenStronghold.java:77) ~[bbs.class:?]
	at mcjty.lostcities.dimensions.world.LostCityChunkGenerator.func_180513_a(LostCityChunkGenerator.java:677) ~[LostCityChunkGenerator.class:?]
	at net.minecraft.world.gen.ChunkProviderServer.func_180513_a(ChunkProviderServer.java:305) ~[on.class:?]
	at net.minecraft.item.ItemEnderEye.func_77659_a(SourceFile:87) ~[aia.class:?]
	at net.minecraft.item.ItemStack.func_77957_a(ItemStack.java:217) ~[aip.class:?]
	at net.minecraft.server.management.PlayerInteractionManager.func_187250_a(PlayerInteractionManager.java:358) ~[or.class:?]
	at net.minecraft.network.NetHandlerPlayServer.func_147346_a(NetHandlerPlayServer.java:765) ~[pa.class:?]
	at net.minecraft.network.play.client.CPacketPlayerTryUseItem.func_148833_a(SourceFile:32) ~[mb.class:?]
	at net.minecraft.network.play.client.CPacketPlayerTryUseItem.func_148833_a(SourceFile:9) ~[mb.class:?]
	at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) ~[hv$1.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) ~[?:1.8.0_212]
	at java.util.concurrent.FutureTask.run(Unknown Source) ~[?:1.8.0_212]
	at net.minecraft.util.Util.func_181617_a(SourceFile:46) ~[h.class:?]
	... 5 more

If you keep trying to throw Eyes of Ender from different locations eventually a throw will succeed and then all future throws will succeed until the world is reloaded.

I have created quite a few test worlds and this bug seems to affect all Lost Cities "biosphere" type worlds. It doesn't seem to affect Lost Cities "default" worlds or non-Lost Cities world types. I have only tested it in the FTB Revelation mod pack; other mods from that pack may play a role in this bug.

Here are steps to reproduce the bug:

1. On the FTB Revelation title screen click "Singleplayer"->"Create New World"
2. Change the game mode to "Creative"
3. Click "More World Options..."
4. Set the seed to -6239615112416465306 (I don't think the seed affects anything, but I put it here just in case)
5. Set the World Type to "Lost Cities (BoP)" and click "Customize"->"biosphere"
6. Click "Create New World"
7. Run this command: "/give @p minecraft:ender_eye 64"
At this point if you were to throw an Eye of Ender it would get properly thrown.
8. Save and Quit to Title
9. Reopen the world
10. Try to throw an Eye of Ender. It should fail this time and log the stack trace.
11. Fly around the world while trying to throw Eyes of Ender. Eventually it will succeed and then you'll be able to throw eyes from anywhere. Note that the movement is essential; if you stand in place and try to throw you'll never throw anything besides Exceptions. *ba dum tss*

**Comment by DereC4** [comment]
Hey i got this problem too; turns out biosphere config has strongholds disabled so you should enable those
