### ISSUE TITLE
BUG NullPointerException with Sleeping Bags

### ISSUE THREAD

**Issue by RattenDieb** [McJty/LostCities#338]
Hey there,

I got an issue with my modpack with the last update in combination with Sleeping Bags mod (sleeping_bags-1.16.4-1.0.1.jar)

I made a test just with lost cities and sleeping bags. When somebody uses a sleeping bag this error triggers:

`Error executing task on Server
java.lang.NullPointerException
	at net.minecraft.world.World.func_189509_E(World.java:151)
	at net.minecraft.world.World.func_180495_p(World.java:376)
	at mcjty.lostcities.setup.ForgeEventHandlers.isValidSpawnBed(ForgeEventHandlers.java:190)
	at mcjty.lostcities.setup.ForgeEventHandlers.onPlayerSleepInBedEvent(ForgeEventHandlers.java:294)
	at net.minecraftforge.eventbus.ASMEventHandler_19_ForgeEventHandlers_onPlayerSleepInBedEvent_PlayerSleepInBedEvent.invoke(.dynamic)
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85)
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:297)
	at net.minecraftforge.event.ForgeEventFactory.onPlayerSleepInBed(ForgeEventFactory.java:457)
	at de.maxhenkel.sleepingbags.items.ItemSleepingBag.trySleep(ItemSleepingBag.java:66)
	at de.maxhenkel.sleepingbags.items.ItemSleepingBag.func_77659_a(ItemSleepingBag.java:56)
	at net.minecraft.item.ItemStack.func_77957_a(ItemStack.java:214)
	at net.minecraft.server.management.PlayerInteractionManager.func_187250_a(PlayerInteractionManager.java:287)
	at net.minecraft.network.play.ServerPlayNetHandler.func_147346_a(ServerPlayNetHandler.java:982)
	at net.minecraft.network.play.client.CPlayerTryUseItemPacket.func_148833_a(SourceFile:31)
	at net.minecraft.network.play.client.CPlayerTryUseItemPacket.func_148833_a(SourceFile:9)
	at net.minecraft.network.PacketThreadUtil.func_225383_a(SourceFile:21)
	at net.minecraft.network.PacketThreadUtil$$Lambda$5799/1630621040.run(Unknown Source)
	at net.minecraft.util.concurrent.TickDelayedTask.run(SourceFile:18)
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213166_h(SourceFile:144)
	at net.minecraft.util.concurrent.RecursiveEventLoop.func_213166_h(SourceFile:23)
	at net.minecraft.server.MinecraftServer.func_213166_h(MinecraftServer.java:733)
	at net.minecraft.server.MinecraftServer.func_213166_h(MinecraftServer.java:159)
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213168_p(SourceFile:118)
	at net.minecraft.server.MinecraftServer.func_213205_aW(MinecraftServer.java:716)
	at net.minecraft.server.MinecraftServer.func_213168_p(MinecraftServer.java:710)
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213161_c(SourceFile:127)
	at net.minecraft.server.MinecraftServer.func_213202_o(MinecraftServer.java:696)
	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:645)
	at net.minecraft.server.MinecraftServer.lambda$startServer$0(MinecraftServer.java:232)
	at net.minecraft.server.MinecraftServer$$Lambda$5178/315771971.run(Unknown Source)
	at java.lang.Thread.run(Thread.java:745)`

I Hope you can check this :) 

Thanks!

**Comment by RattenDieb** [comment]
I tried the last version of both mods. Unfortunately the bug is still there. Due to the error, I am unfortunately unable to update Cities on my server. *sigh*
