### ISSUE TITLE
Bridge unable to generate with provided palette

### ISSUE THREAD

**Issue by TqLxQuanZ** [McJty/LostCities#398]
There is a bug where bridge cannot be generated with provided palette, but works with standard palette that used by city style.
Version: lostcities-1.16-4.0.9-beta

![image](https://user-images.githubusercontent.com/31058251/124275880-b2104780-db75-11eb-81ed-7dc6f8d49ca1.png)
![image](https://user-images.githubusercontent.com/31058251/124275922-be94a000-db75-11eb-90dc-a378bae4ea9a.png)

**Comment by Ironnoob73** [comment]
The same. Other buildings also cannot use custom entries, otherwise it will crash and give the following crash-report.
```
Description: Exception generating new chunk

java.lang.RuntimeException: Could not find entry 'O' in the palette for part 'building4_1'!
    at mcjty.lostcities.dimensions.world.terraingen.LostCitiesTerrainGenerator.generatePart(LostCitiesTerrainGenerator.java:2083)
    at mcjty.lostcities.dimensions.world.terraingen.LostCitiesTerrainGenerator.generateBuilding(LostCitiesTerrainGenerator.java:2323)
    at mcjty.lostcities.dimensions.world.terraingen.LostCitiesTerrainGenerator.doCityChunk(LostCitiesTerrainGenerator.java:911)
    at mcjty.lostcities.dimensions.world.terraingen.LostCitiesTerrainGenerator.generate(LostCitiesTerrainGenerator.java:252)
    at mcjty.lostcities.dimensions.world.LostCityChunkGenerator.generateChunk(LostCityChunkGenerator.java:224)
    at net.minecraft.world.gen.ChunkProviderServer.provideChunk(ChunkProviderServer.java:143)
    at net.minecraft.server.management.PlayerChunkMapEntry.providePlayerChunk(PlayerChunkMapEntry.java:126)
    at net.minecraft.server.management.PlayerChunkMap.tick(PlayerChunkMap.java:226)
    at net.minecraft.world.WorldServer.tick(WorldServer.java:227)
    at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:756)
    at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:668)
    at net.minecraft.server.integrated.IntegratedServer.tick(IntegratedServer.java:279)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
    at java.lang.Thread.run(Thread.java:748)
```
