### ISSUE TITLE
[Lost Souls] [1.12.1] Crash on Pack Load

### ISSUE THREAD

**Issue by DaggerTM** [McJty/LostCities#42]
I have added Lost Souls to my Modpack Pristine, which crashed before it could start up, this crash didnt happen yesterday, or while i was testing the update i was doing bfeore this crash started.

# **Crash:**

> net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from The Lost Cities (lostcities)
> Caused by: java.lang.NoClassDefFoundError: mcjty/lostcities/api/ILostCityAsset
> 	at mcjty.lostcities.proxy.CommonProxy.postInit(CommonProxy.java:77)
> 	at mcjty.lostcities.proxy.ClientProxy.postInit(ClientProxy.java:20)
> 	at mcjty.lostcities.LostCities.postInit(LostCities.java:86)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
> 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> 	at java.lang.reflect.Method.invoke(Method.java:483)
> 	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:609)
> 	at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source)
> 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> 	at java.lang.reflect.Method.invoke(Method.java:483)
> 	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
> 	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
> 	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
> 	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
> 	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
> 	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
> 	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
> 	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:253)
> 	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:231)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
> 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> 	at java.lang.reflect.Method.invoke(Method.java:483)
> 	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
> 	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
> 	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
> 	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
> 	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
> 	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
> 	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
> 	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:148)
> 	at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:786)
> 	at net.minecraftforge.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:343)
> 	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:534)
> 	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:377)
> 	at net.minecraft.client.main.Main.main(SourceFile:123)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
> 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> 	at java.lang.reflect.Method.invoke(Method.java:483)
> 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
> 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
> Caused by: java.lang.ClassNotFoundException: mcjty.lostcities.api.ILostCityAsset
> 	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
> 	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
> 	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
> 	... 43 more
> Caused by: java.lang.NullPointerException

**Comment by McJty** [comment]
What other mods do you have? What version of Lost Cities?

**Comment by DaggerTM** [comment]
It doesn't crash anymore it did it that one time, if it crashes a again you might want to keep this open until further notice...
