### ISSUE TITLE
Worker-Mains die; new chunks cease to generate

### ISSUE THREAD

**Issue by cincinnatus4502** [McJty/LostCities#420]
Similar to #387 , although not using any pregeneration, after a while a world generated with Lost Cities will stop generating. Reading logs reveals that, almost exactly like #387 , server worker-mains are dying and won't generate any more new chunks. 

Testing on a default world without Lost Cities works fine, no worker-mains die as a result of the nullpointer. Testing on a Biomes O' Plenty world without Lost Cities works fine, no worker-mains die as a result of the nullpointer. Default worldtype with Lost Cities runs into the same error, although does not specify all the weird lighting errors (or whatever those mean) as in the BOP+LC world, but still runs into an unidentified null pointer. Default worldtype + LC error is completely unspecified. My log copy .txt is from a BOP world with Lost Cities, tallbuildings preset if it matters. Log copy text file goes from about where I join the world (singleplayer, 8gb RAM allocated, never even gets close to full usage) to where I leave.

An example of where the worker mains are dying, again almost exactly like #387 :
> [17:21:49] [Worker-Main-39/WARN]: Worker-Main-39 died
java.lang.NullPointerException: null
	at net.minecraft.world.lighting.SectionLightStorage.func_215521_h(SourceFile:96) ~[?:?]
	at net.minecraft.world.lighting.LightEngine.func_215471_c(LightEngine.java:129) ~[?:?]
	at net.minecraft.world.lighting.LevelBasedGraph.func_215469_a(LevelBasedGraph.java:122) ~[?:?]
	at net.minecraft.world.lighting.BlockLightEngine.func_215623_a(BlockLightEngine.java:118) ~[?:?]
	at net.minecraft.world.lighting.WorldLightManager.func_215573_a(SourceFile:41) ~[?:?]
	at net.minecraft.world.server.ServerWorldLightManager.func_215579_a(SourceFile:135) ~[?:?]
	at net.minecraft.world.server.ServerWorldLightManager$$Lambda$17834/1359355233.accept(Unknown Source) ~[?:?]
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1374) ~[?:1.8.0_51]
	at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:580) ~[?:1.8.0_51]
	at net.minecraft.world.server.ServerWorldLightManager.func_223117_a(SourceFile:135) ~[?:?]
	at net.minecraft.world.server.ServerWorldLightManager$$Lambda$17826/491687158.run(Unknown Source) ~[?:?]
	at net.minecraft.world.server.ServerWorldLightManager.func_215603_b(SourceFile:170) ~[?:?]
	at net.minecraft.world.server.ServerWorldLightManager.func_223119_a(SourceFile:108) ~[?:?]
	at net.minecraft.world.server.ServerWorldLightManager$$Lambda$17829/1002201084.run(Unknown Source) ~[?:?]
	at net.minecraft.world.chunk.ChunkTaskPriorityQueueSorter.func_219083_b(SourceFile:58) ~[?:?]
	at net.minecraft.world.chunk.ChunkTaskPriorityQueueSorter$$Lambda$17528/994628924.run(Unknown Source) ~[?:?]
	at net.minecraft.util.concurrent.DelegatedTaskExecutor.func_213148_e(SourceFile:94) ~[?:?]
	at net.minecraft.util.concurrent.DelegatedTaskExecutor.func_213145_a(SourceFile:137) ~[?:?]
	at net.minecraft.util.concurrent.DelegatedTaskExecutor.run(SourceFile:105) ~[?:?]
	at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1402) ~[?:1.8.0_51]
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289) ~[?:1.8.0_51]
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056) ~[?:1.8.0_51]
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1689) ~[?:1.8.0_51]
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157) [?:1.8.0_51]

[log copy.txt](https://github.com/McJtyMods/LostCities/files/7834174/log.copy.txt)

Can provide modlist if necessary. I don't have any lighting mods that could cause the null pointer (since it all seems to be light engine related). 
Thanks!

**Comment by McJty** [comment]
Version?

**Comment by cincinnatus4502** [comment]
> Version?

Minecraft 1.16.5, Forge 36.2.20, Lost Cities 4.0.10 beta.

**Comment by McJty** [comment]
I haven't been able to reproduce this. Could perhaps be caused by an incompatible mod

**Comment by cincinnatus4502** [comment]
> I haven't been able to reproduce this. Could perhaps be caused by an incompatible mod

What are some of the known incompatibilities? This pack isn't super large or fancy, sub-100 mods. 

List is as follows if you know any that frequently conflict with Lost Cities:
Desolation (Forge), JEI, Lootr, Mekanism and Mekanism Generators, Polymorph, Sons of Sins, Lost Cities (of course), trash cans, Tropicraft, Untamed Wilds, Absent by Design, Apotheosis, AppleSkin, Architectury API, Artifacts, AutoRegLib, BetterEnd, Beyond Earth, Biomes O' Plenty, Blueprint, Carry On, Citadel, Cloth Config API (forge), Clumps, CodeChicken Lib, CofH core, Comforts, Controlling, Craftable Blaze Rods, Crafting Tweaks, Create, Create Crafts & Additions, Create Stuff Additions, Curios API, Ding, Ender Crop, Ender Storage, ExpandAbility, Farmer's Delight, Farmer's Delight Integrations, Fast Leaf Decay, FastFurnace and FastWorkbench, Flywheel, FTB Library + FTB Ultimine, GraveStone Mod, Hardcore Questing Mod, Hunter Illager, JEI Integration, JourneyMap, Just Enough Resources, Just Enough Vehicles, Morpheus, MrCrayfish's Furniture Mod, MrCrayfish's Gun Mod, MrCrayfish's Vehicle Mod, an integration mod for Crayfish's furniture, My Server Is Compatible, Nature's Compass, Obfuscate, Performant, Pillagers, Placebo, Quark, Quark Oddities, Rope Bridge, Selene Lib, Server Tab Info, Stoneholm, SuperMartijn642 core lib, Supplementaries, SwingThroughGrass, The One Probe, The Undead, Thermal Expansion and Foundation, Timeless and Classics, Upgrade Aquatic, Waystones, and Whisperwoods. 

Not sure if any of those would cause other worldgen incompatibilities or any lighting related error that causes the world to cease generating.

**Comment by NixityNull** [comment]
I have been having a similar issue in which chunks won't generate and mob ai freezes. I haven't been able to figure out the source of the problem because it doesn't crash the game, just breaks it, so I annoyingly cannot get any crash reports for the issue. It may be another mod's issue, but it only ever seems to happen with Lost cities installed.

I also happen to have apotheosis, quark, the undead and whisperwoods, so it could be one of them causing the issue out of incompatibility

**Comment by Zelly9191** [comment]
I'm experiencing the same issue but i do notice it doesn't seem to happen on default lost cities generation settings. (at least for me} or settings with buildings that are not hard on world gen. when using the "tall buildings" settings it seems to happen pretty frequently although it still takes a while to occur. it seems to have an effect similar to killing the tps. all mobs freeze any you cant light portals.

These are the mods i share with cincinnatus4502.

JEI, Lootr, Polymorph, Lost Cities, trash cans, AppleSkin, Biomes O' Plenty, Clumps, Curios API, Ding, FastFurnace, FastWorkbench, JEI Integration, Just Enough Resources, MrCrayfish's Furniture Mod, MrCrayfish's Gun Mod, Nature's Compass, Placebo, SuperMartijn642 core lib, and Supplementaries.

additionally here is a screenshot of said effect and my log.
[latest.log](https://github.com/McJtyMods/LostCities/files/9312253/latest.log)
![2022-08-11_14 15 28](https://user-images.githubusercontent.com/23410655/184246322-ed5e11c2-0e94-4290-9926-c39dbf816eb7.png)
