### ISSUE TITLE
Can't use bed + diamond + skull to get to other dimension.

### ISSUE THREAD

**Issue by Chrisjohnson57387** [McJty/LostCities#424]
minecraft: 1.18.1
forge: 39.0.9
Lost cities: 1.18-5.0.1
No other mods.

I get the below error when trying to use the bed on diamonds with sulls around to teleport to the lost cities dimension.

```
Exception caught during firing event: Cannot invoke "net.minecraft.server.level.ServerLevel.m_8055_(net.minecraft.core.BlockPos)" because "destWorld" is null
	Index: 1
	Listeners:
		0: NORMAL
		1: ASM: mcjty.lostcities.setup.ForgeEventHandlers@7e584e13 onPlayerSleepInBedEvent(Lnet/minecraftforge/event/entity/player/PlayerSleepInBedEvent;)V
java.lang.NullPointerException: Cannot invoke "net.minecraft.server.level.ServerLevel.m_8055_(net.minecraft.core.BlockPos)" because "destWorld" is null
	at TRANSFORMER/lostcities@1.18-5.0.1/mcjty.lostcities.setup.ForgeEventHandlers.findLocation(ForgeEventHandlers.java:323)
	at TRANSFORMER/lostcities@1.18-5.0.1/mcjty.lostcities.setup.ForgeEventHandlers.onPlayerSleepInBedEvent(ForgeEventHandlers.java:315)
	at net.minecraftforge.eventbus.ASMEventHandler_20_ForgeEventHandlers_onPlayerSleepInBedEvent_PlayerSleepInBedEvent.invoke(.dynamic)
	at MC-BOOTSTRAP/eventbus@5.0.3/net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85)
	at MC-BOOTSTRAP/eventbus@5.0.3/net.minecraftforge.eventbus.EventBus.post(EventBus.java:302)
	at MC-BOOTSTRAP/eventbus@5.0.3/net.minecraftforge.eventbus.EventBus.post(EventBus.java:283)
	at TRANSFORMER/forge@39.0.9/net.minecraftforge.event.ForgeEventFactory.onPlayerSleepInBed(ForgeEventFactory.java:462)
	at TRANSFORMER/minecraft@1.18.1/net.minecraft.server.level.ServerPlayer.m_7720_(ServerPlayer.java:811)
	at TRANSFORMER/minecraft@1.18.1/net.minecraft.world.level.block.BedBlock.m_6227_(BedBlock.java:115)
	at TRANSFORMER/minecraft@1.18.1/net.minecraft.world.level.block.state.BlockBehaviour$BlockStateBase.m_60664_(BlockBehaviour.java:695)
	at TRANSFORMER/minecraft@1.18.1/net.minecraft.server.level.ServerPlayerGameMode.m_7179_(ServerPlayerGameMode.java:335)
	at TRANSFORMER/minecraft@1.18.1/net.minecraft.server.network.ServerGamePacketListenerImpl.m_6371_(ServerGamePacketListenerImpl.java:975)
	at TRANSFORMER/minecraft@1.18.1/net.minecraft.network.protocol.game.ServerboundUseItemOnPacket.m_5797_(ServerboundUseItemOnPacket.java:30)
	at TRANSFORMER/minecraft@1.18.1/net.minecraft.network.protocol.game.ServerboundUseItemOnPacket.m_5797_(ServerboundUseItemOnPacket.java:8)
	at TRANSFORMER/minecraft@1.18.1/net.minecraft.network.protocol.PacketUtils.m_131356_(PacketUtils.java:21)
	at TRANSFORMER/minecraft@1.18.1/net.minecraft.server.TickTask.run(TickTask.java:18)
	at TRANSFORMER/minecraft@1.18.1/net.minecraft.util.thread.BlockableEventLoop.m_6367_(BlockableEventLoop.java:151)
	at TRANSFORMER/minecraft@1.18.1/net.minecraft.util.thread.ReentrantBlockableEventLoop.m_6367_(ReentrantBlockableEventLoop.java:23)
	at TRANSFORMER/minecraft@1.18.1/net.minecraft.server.MinecraftServer.m_6367_(MinecraftServer.java:765)
	at TRANSFORMER/minecraft@1.18.1/net.minecraft.server.MinecraftServer.m_6367_(MinecraftServer.java:161)
	at TRANSFORMER/minecraft@1.18.1/net.minecraft.util.thread.BlockableEventLoop.m_7245_(BlockableEventLoop.java:125)
	at TRANSFORMER/minecraft@1.18.1/net.minecraft.server.MinecraftServer.m_129961_(MinecraftServer.java:748)
	at TRANSFORMER/minecraft@1.18.1/net.minecraft.server.MinecraftServer.m_7245_(MinecraftServer.java:742)
	at TRANSFORMER/minecraft@1.18.1/net.minecraft.util.thread.BlockableEventLoop.m_18701_(BlockableEventLoop.java:134)
	at TRANSFORMER/minecraft@1.18.1/net.minecraft.server.MinecraftServer.m_130012_(MinecraftServer.java:728)
	at TRANSFORMER/minecraft@1.18.1/net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:672)
	at TRANSFORMER/minecraft@1.18.1/net.minecraft.server.MinecraftServer.m_177918_(MinecraftServer.java:258)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

**Comment by McJty** [comment]
Fixed in 5.0.3
