### ISSUE TITLE
cant start server. issue with lostcities 

### ISSUE THREAD

**Issue by PastryG** [McJty/LostCities#435]
every time i try start the server it just crashes no clue why here is the crash report 

---- Minecraft Crash Report ----

WARNING: coremods are present:
  RandomPatches (randompatches-1.12.2-1.21.0.3.jar)
  ForgelinPlugin (Forgelin-1.8.4.jar)
  Quark Plugin (Quark-r1.6-179.jar)
  BetterFoliageLoader (BetterFoliage-MC1.12-2.2.0.jar)
  ThiccEntities Plugin (thiccentities-1.4.jar)
  FutureMC (future-mc-1.12.2-0.2.6.1.jar)
  LoadingPlugin (Bloodmoon-MC1.12.2-1.5.3.jar)
Contact their authors BEFORE contacting forge

// Ouch. That hurt :(

Time: 3/20/22 6:16 PM
Description: Exception in server tick loop

java.lang.IllegalStateException: Not a JSON Object: "lostcities"
	at com.google.gson.JsonElement.getAsJsonObject(JsonElement.java:90)
	at mcjty.lostcities.dimensions.world.WorldTypeTools.getProfileOnServer(WorldTypeTools.java:133)
	at mcjty.lostcities.dimensions.world.WorldTypeTools.getProfile(WorldTypeTools.java:58)
	at mcjty.lostcities.dimensions.world.LostWorldType.getBiomeProvider(LostWorldType.java:64)
	at net.minecraft.world.WorldProvider.func_76572_b(WorldProvider.java:58)
	at net.minecraft.world.WorldProvider.func_76558_a(WorldProvider.java:40)
	at net.minecraft.world.WorldServer.<init>(WorldServer.java:116)
	at net.minecraft.server.MinecraftServer.func_71247_a(MinecraftServer.java:298)
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:270)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:486)
	at java.lang.Thread.run(Thread.java:748)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Linux (amd64) version 3.10.0-1160.49.1.el7.x86_64
	Java Version: 1.8.0_212, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 169532600 bytes (161 MB) / 565182464 bytes (539 MB) up to 2863661056 bytes (2731 MB)
	JVM Flags: 6 total; -Xms256M -Xmx3072M -XX:+CMSIncrementalPacing -XX:+CMSClassUnloadingEnabled -XX:MinHeapFreeRatio=10 -XX:MaxHeapFreeRatio=20
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2855 44 mods loaded, 44 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State  | ID                  | Version         | Source                                            | Signature                                |
	|:------ |:------------------- |:--------------- |:------------------------------------------------- |:---------------------------------------- |
	| LCHIJA | minecraft           | 1.12.2          | minecraft.jar                                     | None                                     |
	| LCHIJA | mcp                 | 9.42            | minecraft.jar                                     | None                                     |
	| LCHIJA | FML                 | 8.0.99.99       | forge-1.12.2-14.23.5.2855.jar                     | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | forge               | 14.23.5.2855    | forge-1.12.2-14.23.5.2855.jar                     | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | randompatches       | 1.12.2-1.21.0.3 | randompatches-1.12.2-1.21.0.3.jar                 | None                                     |
	| LCHIJA | securitycraft       | v1.8.20.2       | [1.12.2] SecurityCraft v1.8.20.2.jar              | None                                     |
	| LCHIJA | jei                 | 4.16.1.302      | jei_1.12.2-4.16.1.302.jar                         | None                                     |
	| LCHIJA | quark               | r1.6-179        | Quark-r1.6-179.jar                                | None                                     |
	| LCHIJA | autoreglib          | 1.3-32          | AutoRegLib-1.3-32.jar                             | None                                     |
	| LCHIJA | badmobs             | 1.1.40          | BadMobs-1.12.2-1.1.40.jar                         | d476d1b22b218a10d845928d1665d45fce301b27 |
	| LCHIJA | betterbuilderswands | 0.13.2          | BetterBuildersWands-1.12.2-0.13.2.271+5997513.jar | None                                     |
	| LCHIJA | biomesoplenty       | 7.0.1.2444      | BiomesOPlenty-1.12.2-7.0.1.2444-universal.jar     | None                                     |
	| LCHIJA | bloodmoon           | 1.5.3           | Bloodmoon-MC1.12.2-1.5.3.jar                      | d72e0dd57935b3e9476212aea0c0df352dd76291 |
	| LCHIJA | extendedrenderer    | v1.0            | coroutil-1.12.1-1.2.37.jar                        | None                                     |
	| LCHIJA | coroutil            | 1.12.1-1.2.37   | coroutil-1.12.1-1.2.37.jar                        | None                                     |
	| LCHIJA | configmod           | v1.0            | coroutil-1.12.1-1.2.37.jar                        | None                                     |
	| LCHIJA | dayzombies          | 1.0.0           | DayZombiez.jar                                    | None                                     |
	| LCHIJA | flansmod            | 5.10.0          | Flan's+Mod-1.12.2-5.10.0.jar                      | None                                     |
	| LCHIJA | forgelin            | 1.8.4           | Forgelin-1.8.4.jar                                | None                                     |
	| LCHIJA | cfm                 | 6.3.1           | furniture-6.3.1-1.12.2.jar                        | None                                     |
	| LCHIJA | futuremc            | 0.2.6           | future-mc-1.12.2-0.2.6.1.jar                      | None                                     |
	| LCHIJA | ichunutil           | 7.2.2           | iChunUtil-1.12.2-7.2.2.jar                        | 4db5c2bd1b556f252a5b8b54b256d381b2a0a6b8 |
	| LCHIJA | mts                 | 21.1.0          | Immersive+Vehicles-1.12.2-21.1.0.jar              | None                                     |
	| LCHIJA | lostcities          | 2.0.21          | lostcities-1.12-2.0.21.jar                        | None                                     |
	| LCHIJA | mcwdoors            | 1.3             | mcw-doors-1.0.3-mc1.12.2.jar                      | None                                     |
	| LCHIJA | mcwfences           | 1.0.0           | mcw-fences-1.0.0-mc1.12.2.jar                     | None                                     |
	| LCHIJA | mcwfurnitures       | 1.0.1           | mcw-furniture-1.0.1-mc1.12.2beta.jar              | None                                     |
	| LCHIJA | mcwwindows          | 1.0             | mcw-windows-1.0.0-mc1.12.2.jar                    | None                                     |
	| LCHIJA | mobends             | 1.2.1           | MoBends_1.12.2-1.2.1-19.12.21.jar                 | None                                     |
	| LCHIJA | mobsunscreen        | 1.12.2-2.1.3    | mobsunscreen-1.12.2-2.1.3.jar                     | None                                     |
	| LCHIJA | modernweaponspack   | 5.8.2           | Modern+Warfare-Content+Pack-1.12.2-5.8.2.jar      | None                                     |
	| LCHIJA | nifty               | 1.20.1          | NiftyBlocks-1.20.1.jar                            | None                                     |
	| LCHIJA | simplepartspack     | 5.7.2           | Simple+Parts-Content+Pack-1.12.2-5.7.2.jar        | None                                     |
	| LCHIJA | snowvariants        | 1.12.2-1.3.1    | snowvariants-1.12.2-1.3.1.jar                     | None                                     |
	| LCHIJA | spartanshields      | 1.5.4           | SpartanShields-1.12.2-1.5.4.jar                   | None                                     |
	| LCHIJA | spartanweaponry     | beta 1.3.8      | SpartanWeaponry-1.12.2-beta-1.3.8.jar             | None                                     |
	| LCHIJA | switchbow           | 1.6             | switchbow-1.6.jar                                 | None                                     |
	| LCHIJA | thiccentities       | GRADLE:VERSION  | thiccentities-1.4.jar                             | None                                     |
	| LCHIJA | toolbelt            | 1.9.13          | ToolBelt-1.12.2-1.9.13.jar                        | None                                     |
	| LCHIJA | toughasnails        | 3.1.0.141       | ToughAsNails-1.12.2-3.1.0.141-universal.jar       | None                                     |
	| LCHIJA | unuparts            | 5.1.0           | UNU+Parts+Pack+[MTS]+1.12.2-20.5.0-5.1.0.jar      | None                                     |
	| LCHIJA | unucivil            | 5.2.0           | UNU+Civilian+Pack+[MTS]+1.12.2-20.5.0-5.2.0.jar   | None                                     |
	| LCHIJA | zombieawareness     | 1.12.1-1.11.16  | zombieawareness-1.12.1-1.11.16.jar                | None                                     |
	| LCHIJA | orelib              | 3.6.0.1         | OreLib-1.12.2-3.6.0.1.jar                         | 7a2128d395ad96ceb9d9030fbd41d035b435753a |

	Loaded coremods (and transformers): 
RandomPatches (randompatches-1.12.2-1.21.0.3.jar)
  com.therandomlabs.randompatches.core.RPTransformer
ForgelinPlugin (Forgelin-1.8.4.jar)
  
Quark Plugin (Quark-r1.6-179.jar)
  vazkii.quark.base.asm.ClassTransformer
BetterFoliageLoader (BetterFoliage-MC1.12-2.2.0.jar)
  mods.betterfoliage.loader.BetterFoliageTransformer
ThiccEntities Plugin (thiccentities-1.4.jar)
  wiresegal.thicc.asm.ThiccAsmTransformer
FutureMC (future-mc-1.12.2-0.2.6.1.jar)
  thedarkcolour.futuremc.asm.CoreTransformer
LoadingPlugin (Bloodmoon-MC1.12.2-1.5.3.jar)
  lumien.bloodmoon.asm.ClassTransformer
	Profiler Position: N/A (disabled)
	Player Count: 0 / 30; []
	Is Modded: Definitely; Server brand changed to 'fml,forge'
	Type: Dedicated Server (map_server.txt)

**Comment by PastryG** [comment]
im an idiot
