### ISSUE TITLE
Game freezes and dies

### ISSUE THREAD

**Issue by Nodachi216** [McJty/LostCities#459]
ATM7 pack, Lost cities 1.18-5.3.2

This snippet is repeated in the log multiple times

> [13:25:05] [Server thread/ERROR]: Encountered an unexpected exception
net.minecraft.ReportedException: Feature placement
	at net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:906) ~[client-1.18.2-20220404.173914-srg.jar%23378!/:?]
	at net.minecraft.server.MinecraftServer.m_5705_(MinecraftServer.java:842) ~[client-1.18.2-20220404.173914-srg.jar%23378!/:?]
	at net.minecraft.client.server.IntegratedServer.m_5705_(IntegratedServer.java:84) ~[client-1.18.2-20220404.173914-srg.jar%23378!/:?]
	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:685) ~[client-1.18.2-20220404.173914-srg.jar%23378!/:?]
	at net.minecraft.server.MinecraftServer.m_177918_(MinecraftServer.java:261) ~[client-1.18.2-20220404.173914-srg.jar%23378!/:?]
	at java.lang.Thread.run(Thread.java:833) [?:?]
Caused by: java.lang.NullPointerException: Cannot invoke "mcjty.lostcities.config.LostCityProfile.getWorldStyle()" because "profile" is null
	at mcjty.lostcities.worldgen.DefaultDimensionInfo.<init>(DefaultDimensionInfo.java:35) ~[lostcities-1.18-5.3.2.jar%23237!/:1.18-5.3.2]
	at mcjty.lostcities.worldgen.LostCityFeature.getDimensionInfo(LostCityFeature.java:95) ~[lostcities-1.18-5.3.2.jar%23237!/:1.18-5.3.2]
	at mcjty.lostcities.worldgen.LostCityFeature.m_142674_(LostCityFeature.java:62) ~[lostcities-1.18-5.3.2.jar%23237!/:1.18-5.3.2]
	at net.minecraft.world.level.levelgen.feature.Feature.m_204740_(Feature.java:153) ~[client-1.18.2-20220404.173914-srg.jar%23378!/:?]
	at net.minecraft.world.level.levelgen.feature.ConfiguredFeature.m_65385_(ConfiguredFeature.java:27) ~[client-1.18.2-20220404.173914-srg.jar%23378!/:?]
	at net.minecraft.world.level.levelgen.placement.PlacedFeature.m_191789_(PlacedFeature.java:56) ~[client-1.18.2-20220404.173914-srg.jar%23378!/:?]
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183) ~[?:?]
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183) ~[?:?]
	at java.util.stream.IntPipeline$1$1.accept(IntPipeline.java:180) ~[?:?]
	at java.util.stream.Streams$RangeIntSpliterator.forEachRemaining(Streams.java:104) ~[?:?]
	at java.util.Spliterator$OfInt.forEachRemaining(Spliterator.java:711) ~[?:?]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509) ~[?:?]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?]
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150) ~[?:?]
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173) ~[?:?]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596) ~[?:?]
	at java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:276) ~[?:?]
	at java.util.stream.Streams$StreamBuilderImpl.forEachRemaining(Streams.java:411) ~[?:?]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509) ~[?:?]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?]
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150) ~[?:?]
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173) ~[?:?]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596) ~[?:?]
	at net.minecraft.world.level.levelgen.placement.PlacedFeature.m_191797_(PlacedFeature.java:55) ~[client-1.18.2-20220404.173914-srg.jar%23378!/:?]
	at net.minecraft.world.level.levelgen.placement.PlacedFeature.m_191806_(PlacedFeature.java:44) ~[client-1.18.2-20220404.173914-srg.jar%23378!/:?]
	at net.minecraft.world.level.chunk.ChunkGenerator.m_183372_(ChunkGenerator.java:475) ~[client-1.18.2-20220404.173914-srg.jar%23378!/:?]
	at net.minecraft.world.level.chunk.ChunkStatus.m_187807_(ChunkStatus.java:135) ~[client-1.18.2-20220404.173914-srg.jar%23378!/:?]
	at net.minecraft.world.level.chunk.ChunkStatus.m_187788_(ChunkStatus.java:262) ~[client-1.18.2-20220404.173914-srg.jar%23378!/:?]
	at net.minecraft.server.level.ChunkMap.lambda$scheduleChunkGeneration$22(ChunkMap.java:589) ~[client-1.18.2-20220404.173914-srg.jar%23378!/:?]
	at com.mojang.datafixers.util.Either$Left.map(Either.java:38) ~[datafixerupper-4.1.27.jar%2334!/:?]
	at net.minecraft.server.level.ChunkMap.lambda$scheduleChunkGeneration$24(ChunkMap.java:587) ~[client-1.18.2-20220404.173914-srg.jar%23378!/:?]
	at java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1150) ~[?:?]
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482) ~[?:?]
	at net.minecraft.server.level.ChunkTaskPriorityQueueSorter.m_143188_(ChunkTaskPriorityQueueSorter.java:62) ~[client-1.18.2-20220404.173914-srg.jar%23378!/:?]
	at net.minecraft.util.thread.ProcessorMailbox.m_18759_(ProcessorMailbox.java:91) ~[client-1.18.2-20220404.173914-srg.jar%23378!/:?]
	at net.minecraft.util.thread.ProcessorMailbox.m_18747_(ProcessorMailbox.java:146) ~[client-1.18.2-20220404.173914-srg.jar%23378!/:?]
	at net.minecraft.util.thread.ProcessorMailbox.run(ProcessorMailbox.java:102) ~[client-1.18.2-20220404.173914-srg.jar%23378!/:?]
	at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1395) ~[?:?]
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?]
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?]
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?]
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?]
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?]
[13:25:05] [Server thread/FATAL]: Preparing crash report with UUID aa198100-a12f-413b-9db2-9db2d4ce704b

**Comment by McJty** [comment]
Can you give me more details? How did you configure Lost Cities? What profile did you select? Single player/server?

**Comment by Nodachi216** [comment]
Sure! 
I'm running single player and used the No Damage profile modified by setting the rarity to 0.0004.

**Comment by McJty** [comment]
And did it crash immediatelly after creating the world or the next time you started up an already created world?

**Comment by Nodachi216** [comment]
The world ran fine on the initial run, it was on subsequent starts that it would crash and even then it's not immediate, it happens after wandering around a little bit.

**Comment by McJty** [comment]
Ok. Thanks for the information. I will see if I can reproduce and fix this

**Comment by McJty** [comment]
Ah one final question. on the subsequent starts, was this the first thing you did on that Minecraft instance or did you first load another world or something? I've found that you better load Lost City worlds with a clean fresh minecraft instance

**Comment by Nodachi216** [comment]
Yeah, that's the only world on the instance so it's a clean start each time. Oh, and the world is newly generated with the 1.18-5.3.2 version.
Hope this helps!

**Comment by McJty** [comment]
Just to clarify. If you start minecraft fresh (whatever client you use), don't do anything and immediatelly load your previously created world it can crash?

**Comment by Nodachi216** [comment]
Yes, sir. Fire up the client, start the world, wander a bit... crash.

**Comment by Nodachi216** [comment]
Found a workaround. I went into the config folder and copied the nodamage profile, made the rarity change, and saved it as a new profile. Then I went into the worldsave serverconfig and changed the toml to point at the new profile.
Fired up the game, loaded the world went to one of the places I remembered it freezing before. There was a small hiccup but it kept running!

**Comment by McJty** [comment]
Interesting. I haven't been able to reproduce your problem atm but I have a theory that it has to do with customized profiles. Just not sure why it sometimes fails

**Comment by Nodachi216** [comment]
The lostcities_server.toml file is what made me think of trying the workaround.

> #General settings
> [profiles]
> 	#Block to put underneath a bed so that it qualifies as a teleporter bed
> 	specialBedBlock = "minecraft:diamond_block"
> 	selectedProfile = "Nodachi"
> 	selectedCustomJson = ""

SelectedProfile was "custom" or "customized" (I don't remember which) but selectedCustomJson was null so I figured that giving it a profile to load might work.

**Comment by McJty** [comment]
Aha indeed. That's the problem. Now I have to figure out under what circumstances selectedCustomJson could become null. It wasn't null in the case where I tried it

**Comment by McJty** [comment]
I have been able to reproduce the problem and I have some clues about what's wrong but no solution yet. Working on it

**Comment by inlanoche** [comment]
Interesting.  I had this happen to me as well a few times.  Once was when I turned on the option for lights.  A few other times I played with more basements and tweaked the roads a bit.  Did not check if that above was the same for me as I just switched to nodamage as that fit what I needed enough.  Curious to see if this gets solved.

**Comment by McJty** [comment]
Actually forgot to close this but this should in fact be fixed a few releases ago
