### ISSUE TITLE
Crash with edited config files On lost souls

### ISSUE THREAD

**Issue by Tskuno** [McJty/LostCities#482]
Hello I get a crash when trying to go into haunted buildings with an edited config file, this is the crash report, I'll make a pastebin for the config file for you. I'm not sure why it's crashing, it's very odd.. I've deleted the config file, and ran the default and it runs fine, using mine though it crashes. I'm unsure why. 	config: https://pastebin.com/dycZML3v

Description: Exception in server tick loop

java.lang.ArrayIndexOutOfBoundsException: 0
	at mcjty.lostsouls.config.Config.makeList(Config.java:133)
	at mcjty.lostsouls.config.Config.getRandomChests(Config.java:99)
	at mcjty.lostsouls.ForgeEventHandlers.boostEntity(ForgeEventHandlers.java:253)
	at mcjty.lostsouls.ForgeEventHandlers.handleSpawn(ForgeEventHandlers.java:182)
	at mcjty.lostsouls.ForgeEventHandlers.onTickEvent(ForgeEventHandlers.java:111)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_2032_ForgeEventHandlers_onTickEvent_ServerTickEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraftforge.fml.common.FMLCommonHandler.onPostServerTick(FMLCommonHandler.java:266)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:712)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:279)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Thread.java:745)

**Comment by Tskuno** [comment]
this is for 1.12.2 btw

**Comment by Tskuno** [comment]
full crash log: https://pastebin.com/RtTQQtmM

**Comment by McJty** [comment]
Show your edit

**Comment by McJty** [comment]
[.3=minecraft:diamond_chestplate], [.3=minecraft:iron_chestplate]]
    S:randomChestplates <
        .3=null
        .3=minecraft:diamond_chestplate
        .3=minecraft:iron_chestplate
 
     >

The extra empty line is probably the problem
