### ISSUE TITLE
Crash during feature placement: ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by trienow** [McJty/LostCities#487]
The server crashes when generating new chunks. If any specific information is needed, I am happy to provide it.

~~Version `1.18-5.3.7` of the mod did not have this problem.~~ It did. My mistake.

Snippet of crash report:
```java
---- Minecraft Crash Report ----
// Why did you do that?

Time: 18.09.22, 21:45
Description: Feature placement

java.lang.ArrayIndexOutOfBoundsException: Index -2044 out of bounds for length 24
	at mcjty.lostcities.worldgen.ChunkDriver$SectionCache.get(ChunkDriver.java:391) ~[lostcities-1.18-5.3.9.jar%2390!/:1.18-5.3.9] {re:classloading}
	at mcjty.lostcities.worldgen.ChunkDriver.getBlock(ChunkDriver.java:73) ~[lostcities-1.18-5.3.9.jar%2390!/:1.18-5.3.9] {re:classloading}
	at mcjty.lostcities.worldgen.ChunkDriver.getBlockSafe(ChunkDriver.java:69) ~[lostcities-1.18-5.3.9.jar%2390!/:1.18-5.3.9] {re:classloading}
	at mcjty.lostcities.worldgen.ChunkDriver.updateAdjacent(ChunkDriver.java:191) ~[lostcities-1.18-5.3.9.jar%2390!/:1.18-5.3.9] {re:classloading}
	at mcjty.lostcities.worldgen.ChunkDriver.correct(ChunkDriver.java:274) ~[lostcities-1.18-5.3.9.jar%2390!/:1.18-5.3.9] {re:classloading}
	at mcjty.lostcities.worldgen.ChunkDriver.add(ChunkDriver.java:317) ~[lostcities-1.18-5.3.9.jar%2390!/:1.18-5.3.9] {re:classloading}
	at mcjty.lostcities.worldgen.LostCityTerrainFeature.generatePart(LostCityTerrainFeature.java:2316) ~[lostcities-1.18-5.3.9.jar%2390!/:1.18-5.3.9] {re:classloading}
	at mcjty.lostcities.worldgen.LostCityTerrainFeature.generateScatteredBuilding(LostCityTerrainFeature.java:657) ~[lostcities-1.18-5.3.9.jar%2390!/:1.18-5.3.9] {re:classloading}
	at mcjty.lostcities.worldgen.LostCityTerrainFeature.generateScattered(LostCityTerrainFeature.java:532) ~[lostcities-1.18-5.3.9.jar%2390!/:1.18-5.3.9] {re:classloading}
	at mcjty.lostcities.worldgen.LostCityTerrainFeature.doNormalChunk(LostCityTerrainFeature.java:432) ~[lostcities-1.18-5.3.9.jar%2390!/:1.18-5.3.9] {re:classloading}
	at mcjty.lostcities.worldgen.LostCityTerrainFeature.generate(LostCityTerrainFeature.java:296) ~[lostcities-1.18-5.3.9.jar%2390!/:1.18-5.3.9] {re:classloading}
	at mcjty.lostcities.worldgen.LostCityFeature.m_142674_(LostCityFeature.java:76) ~[lostcities-1.18-5.3.9.jar%2390!/:1.18-5.3.9] {re:classloading}
	at net.minecraft.world.level.levelgen.feature.Feature.m_204740_(Feature.java:153) ~[server-1.18.2-20220404.173914-srg.jar%23135!/:?] {re:mixin,re:classloading}
	at net.minecraft.world.level.levelgen.feature.ConfiguredFeature.m_65385_(ConfiguredFeature.java:27) ~[server-1.18.2-20220404.173914-srg.jar%23135!/:?] {re:classloading}
	at net.minecraft.world.level.levelgen.placement.PlacedFeature.m_191789_(PlacedFeature.java:56) ~[server-1.18.2-20220404.173914-srg.jar%23135!/:?] {re:classloading,pl:accesstransformer:B}
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(Unknown Source) ~[?:?] {}
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(Unknown Source) ~[?:?] {}
	at java.util.stream.IntPipeline$1$1.accept(Unknown Source) ~[?:?] {}
	at java.util.stream.Streams$RangeIntSpliterator.forEachRemaining(Unknown Source) ~[?:?] {}
	at java.util.Spliterator$OfInt.forEachRemaining(Unknown Source) ~[?:?] {}
	at java.util.stream.AbstractPipeline.copyInto(Unknown Source) ~[?:?] {}
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source) ~[?:?] {}
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(Unknown Source) ~[?:?] {}
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(Unknown Source) ~[?:?] {}
	at java.util.stream.AbstractPipeline.evaluate(Unknown Source) ~[?:?] {}
	at java.util.stream.ReferencePipeline.forEach(Unknown Source) ~[?:?] {}
	at java.util.stream.ReferencePipeline$7$1.accept(Unknown Source) ~[?:?] {}
	at java.util.stream.Streams$StreamBuilderImpl.forEachRemaining(Unknown Source) ~[?:?] {}
	at java.util.stream.AbstractPipeline.copyInto(Unknown Source) ~[?:?] {}
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source) ~[?:?] {}
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(Unknown Source) ~[?:?] {}
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(Unknown Source) ~[?:?] {}
	at java.util.stream.AbstractPipeline.evaluate(Unknown Source) ~[?:?] {}
	at java.util.stream.ReferencePipeline.forEach(Unknown Source) ~[?:?] {}
	at net.minecraft.world.level.levelgen.placement.PlacedFeature.m_191797_(PlacedFeature.java:55) ~[server-1.18.2-20220404.173914-srg.jar%23135!/:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.world.level.levelgen.placement.PlacedFeature.m_191806_(PlacedFeature.java:44) ~[server-1.18.2-20220404.173914-srg.jar%23135!/:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.world.level.chunk.ChunkGenerator.m_183372_(ChunkGenerator.java:475) ~[server-1.18.2-20220404.173914-srg.jar%23135!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:byg.mixins.json:access.ChunkGeneratorAccess,pl:mixin:A}
	at net.minecraft.world.level.chunk.ChunkStatus.m_187807_(ChunkStatus.java:135) ~[server-1.18.2-20220404.173914-srg.jar%23135!/:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.world.level.chunk.ChunkStatus.m_187788_(ChunkStatus.java:262) ~[server-1.18.2-20220404.173914-srg.jar%23135!/:?] {re:classloading,pl:accesstransformer:B}
```
Full crash report: https://pastebin.com/SdNcHmNa

# Versions
| Entity      | Version                              |
| ----------- | ------------------------------------ |
| Minecraft   | 1.18.2                               |
| Forge       | 40.1.80 |
| Lost Cities | 1.18-5.3.9              |

**Comment by McJty** [comment]
What profile are you using?  Did you make any modifications?

**Comment by trienow** [comment]
I am using a custom profile with numerous changes. I have uploaded my profile here, in case you would like to take a look: https://gist.github.com/trienow/54639abcebf9cf98746d25deb4ae6a1a

As I started out with `cavern.json`, a diff to it is here, though GitHub's diff algorithm doesn't seem very good: 
https://gist.github.com/trienow/54639abcebf9cf98746d25deb4ae6a1a/revisions?diff=split

And I have to correct myself, the issue was present in `1.18-5.3.7`. When I downgraded I still got a crash. I guess even though the world has been explored a lot, it never got some special combination(?) to generate.

**Comment by 0DeltaWaves** [comment]
I'm getting a similar crash also when loading the nether (cavernous turned on): https://paste.ee/p/u96V7
Any ideas?

Edit: Seems to have corrupted/softlocked my world and server, had to delete the nether DIM file and change the mod config to turn off nether city generation to fix it

**Comment by MrBOOMberMAN** [comment]
> I'm getting a similar crash also when loading the nether (cavernous turned on): https://paste.ee/p/u96V7 Any ideas?
> 
> Edit: Seems to have corrupted/softlocked my world and server, had to delete the nether DIM file and change the mod config to turn off nether city generation to fix it

Exact same problem:
[crash-2025-08-12_21.58.10-server.txt](https://github.com/user-attachments/files/21751595/crash-2025-08-12_21.58.10-server.txt)

**Comment by McJty** [comment]
This is now fixed
