### ISSUE TITLE
CRASH: java.lang.RuntimeException: Invalid name given to minecraft:root getOrThrow!

### ISSUE THREAD

**Issue by RueTV** [McJty/LostCities#498]
Im playing a modded forge 1.19.2 world
How do I resolve the problem for the following crash issue :

java.lang.RuntimeException: Invalid name given to minecraft:root getOrThrow!
	at mcjty.lostcities.worldgen.lost.cityassets.RegistryAssetRegistry.getOrThrow(RegistryAssetRegistry.java:43) ~[lostcities-1.19-6.0.8.jar%23186!/:1.19-6.0.8] {re:classloading}
	at mcjty.lostcities.worldgen.lost.BuildingInfo.<init>(BuildingInfo.java:887) ~[lostcities-1.19-6.0.8.jar%23186!/:1.19-6.0.8] {re:classloading}
	at mcjty.lostcities.worldgen.lost.BuildingInfo.getBuildingInfo(BuildingInfo.java:669) ~[lostcities-1.19-6.0.8.jar%23186!/:1.19-6.0.8] {re:classloading}
	at mcjty.lostcities.worldgen.lost.BuildingInfo.getXmax(BuildingInfo.java:212) ~[lostcities-1.19-6.0.8.jar%23186!/:1.19-6.0.8] {re:classloading}
	at mcjty.lostcities.worldgen.lost.BuildingInfo.isElevatedParkSection(BuildingInfo.java:1139) ~[lostcities-1.19-6.0.8.jar%23186!/:1.19-6.0.8] {re:classloading}
	at mcjty.lostcities.worldgen.LostCityTerrainFeature.generateParkSection(LostCityTerrainFeature.java:2241) ~[lostcities-1.19-6.0.8.jar%23186!/:1.19-6.0.8] {re:classloading}
	at mcjty.lostcities.worldgen.LostCityTerrainFeature.generateStreet(LostCityTerrainFeature.java:1921) ~[lostcities-1.19-6.0.8.jar%23186!/:1.19-6.0.8] {re:classloading}
	at mcjty.lostcities.worldgen.LostCityTerrainFeature.doCityChunk(LostCityTerrainFeature.java:1404) ~[lostcities-1.19-6.0.8.jar%23186!/:1.19-6.0.8] {re:classloading}
	at mcjty.lostcities.worldgen.LostCityTerrainFeature.generate(LostCityTerrainFeature.java:293) ~[lostcities-1.19-6.0.8.jar%23186!/:1.19-6.0.8] {re:classloading}
	at mcjty.lostcities.worldgen.LostCityFeature.m_142674_(LostCityFeature.java:74) ~[lostcities-1.19-6.0.8.jar%23186!/:1.19-6.0.8] {re:classloading}
	at net.minecraft.world.level.levelgen.feature.Feature.m_225028_(Feature.java:154) ~[client-1.19.2-20220805.130853-srg.jar%23218!/:?] {re:classloading,re:mixin}
	at net.minecraft.world.level.levelgen.feature.ConfiguredFeature.m_224953_(ConfiguredFeature.java:27) ~[client-1.19.2-20220805.130853-srg.jar%23218!/:?] {re:classloading}
	at net.minecraft.world.level.levelgen.placement.PlacedFeature.m_226362_(PlacedFeature.java:56) ~[client-1.19.2-20220805.130853-srg.jar%23218!/:?] {re:classloading}
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183) ~[?:?] {}
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183) ~[?:?] {}
	at java.util.stream.IntPipeline$1$1.accept(IntPipeline.java:180) ~[?:?] {}
	at java.util.stream.Streams$RangeIntSpliterator.forEachRemaining(Streams.java:104) ~[?:?] {}
	at java.util.Spliterator$OfInt.forEachRemaining(Spliterator.java:711) ~[?:?] {}
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509) ~[?:?] {}
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?] {}
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150) ~[?:?] {}
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173) ~[?:?] {}
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?] {}
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596) ~[?:?] {}
	at java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:276) ~[?:?] {}
	at java.util.stream.Streams$StreamBuilderImpl.forEachRemaining(Streams.java:411) ~[?:?] {}
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509) ~[?:?] {}
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?] {}
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150) ~[?:?] {}
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173) ~[?:?] {}
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?] {}
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596) ~[?:?] {}
	at net.minecraft.world.level.levelgen.placement.PlacedFeature.m_226368_(PlacedFeature.java:55) ~[client-1.19.2-20220805.130853-srg.jar%23218!/:?] {re:classloading}
	at net.minecraft.world.level.levelgen.placement.PlacedFeature.m_226377_(PlacedFeature.java:44) ~[client-1.19.2-20220805.130853-srg.jar%23218!/:?] {re:classloading}
	at net.minecraft.world.level.chunk.ChunkGenerator.m_213609_(ChunkGenerator.java:466) ~[client-1.19.2-20220805.130853-srg.jar%23218!/:?] {re:mixin,re:classloading,pl:mixin:APP:betteroceanmonuments.mixins.json:DisableVanillaMonumentsMixin,pl:mixin:APP:citadel.mixins.json:ChunkGeneratorMixin,pl:mixin:APP:terrablender_forge.mixins.json:MixinChunkGenerator,pl:mixin:APP:bettermineshafts.mixins.json:DisableVanillaMineshaftsMixin,pl:mixin:A}
	at net.minecraft.world.level.chunk.ChunkStatus.m_223313_(ChunkStatus.java:145) ~[client-1.19.2-20220805.130853-srg.jar%23218!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
	at net.minecraft.world.level.chunk.ChunkStatus.m_223279_(ChunkStatus.java:292) ~[client-1.19.2-20220805.130853-srg.jar%23218!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.level.ChunkMap.lambda$scheduleChunkGeneration$25(ChunkMap.java:621) ~[client-1.19.2-20220805.130853-srg.jar%23218!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:securitycraft.mixins.json:camera.ChunkMapMixin,pl:mixin:A}
	at com.mojang.datafixers.util.Either$Left.map(Either.java:38) ~[datafixerupper-5.0.28.jar%23120!/:?] {}
	at net.minecraft.server.level.ChunkMap.lambda$scheduleChunkGeneration$27(ChunkMap.java:619) ~[client-1.19.2-20220805.130853-srg.jar%23218!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:securitycraft.mixins.json:camera.ChunkMapMixin,pl:mixin:A}
	at java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1150) ~[?:?] {}
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482) ~[?:?] {}
	at net.minecraft.server.level.ChunkTaskPriorityQueueSorter.m_143188_(ChunkTaskPriorityQueueSorter.java:62) ~[client-1.19.2-20220805.130853-srg.jar%23218!/:?] {re:classloading}
	at net.minecraft.util.thread.ProcessorMailbox.m_18759_(ProcessorMailbox.java:91) ~[client-1.19.2-20220805.130853-srg.jar%23218!/:?] {re:classloading}
	at net.minecraft.util.thread.ProcessorMailbox.m_18747_(ProcessorMailbox.java:146) ~[client-1.19.2-20220805.130853-srg.jar%23218!/:?] {re:classloading}
	at net.minecraft.util.thread.ProcessorMailbox.run(ProcessorMailbox.java:102) ~[client-1.19.2-20220805.130853-srg.jar%23218!/:?] {re:classloading}
	at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1395) ~[?:?] {}
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?] {re:computing_frames}
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?] {re:computing_frames}
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?] {}
	
	Hopefully I'll get a response soon

**Comment by McJty** [comment]
What version of forge? You might have to update that

**Comment by RueTV** [comment]
During the last hour I tried to change some settings and looks like it was cause I was using up to 1 - 7 cellars in building settings, that honestly doesnt make any sense how a setting that allows the underground generation was messing up EVERYTHING. I even tried to remove the better dungeons and custom buildings generation mods before trying to do that and the game was still crashing.

**Comment by McJty** [comment]
You didn't answer my question

**Comment by RueTV** [comment]
latest version of forge forge-1.19.2-43.1.47
Also the crash problem got fixed by removing the cellar settings and Im also not lagging anymore and I run minecraft at 80+ fps
These are all the mods Im using btw
![immagine_2022-11-02_143048231](https://user-images.githubusercontent.com/117225717/199502288-2628c006-9ffc-4eb5-85ce-bac34beac88a.png)

**Comment by McJty** [comment]
Ok, so the problem is solved then?

**Comment by RueTV** [comment]
Yeah its solved, but I suggest the devs to fix the cellars underground generation problem

**Comment by McJty** [comment]
If you use wrong values for cellars then it will crash. That's not something I can avoid really. At least not without performance overhead for checking that during worldgen
