### ISSUE TITLE
1.16.5 it wont start and keeps giving me this message LostCities (lostcities) encountered an error during the common_setup event phase java.lang.IllegalStateException: Not a JSON Object: true

### ISSUE THREAD

**Issue by jackgames55** [McJty/LostCities#499]
---- Minecraft Crash Report ----
// Uh... Did I do that?

Time: 11/6/22 9:18 AM
Description: Mod loading error has occurred

java.lang.Exception: Mod Loading has failed
	at net.minecraftforge.fml.CrashReportExtender.dumpModLoadingCrashReport(CrashReportExtender.java:71) [?:?] {re:classloading}
	at net.minecraftforge.fml.client.ClientModLoader.completeModLoading(ClientModLoader.java:174) [?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.lambda$null$1(Minecraft.java:508) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft$$Lambda$4758/2102224373.run(Unknown Source) [?:?] {}
	at net.minecraft.util.Util.func_215077_a(Util.java:320) [?:?] {re:classloading}
	at net.minecraft.client.Minecraft.lambda$new$2(Minecraft.java:504) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft$$Lambda$4318/711135305.accept(Unknown Source) [?:?] {}
	at net.minecraft.client.gui.ResourceLoadProgressGui.func_230430_a_(ResourceLoadProgressGui.java:113) [?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.GameRenderer.func_195458_a(GameRenderer.java:481) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:977) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:607) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:184) [?:?] {re:classloading,pl:runtimedistcleaner:A}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51] {}
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:37) [forge-1.16.5-36.2.39.jar:36.2] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$467/978035840.call(Unknown Source) [forge-1.16.5-36.2.39.jar:36.2] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-8.1.3.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-8.1.3.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-8.1.3.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82) [modlauncher-8.1.3.jar:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) [modlauncher-8.1.3.jar:?] {}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at com.google.gson.JsonElement.getAsJsonObject(JsonElement.java:90) ~[gson-2.8.0.jar:?] {}
-- MOD lostcities --
Details:
	Mod File: lostcities-1.16-4.0.12-beta.jar
	Failure message: LostCities (lostcities) encountered an error during the common_setup event phase
		java.lang.IllegalStateException: Not a JSON Object: true
	Mod Version: 1.16-4.0.12-beta
	Mod Issue URL: http://github.com/McJtyMods/LostCities/issues
	Exception message: java.lang.IllegalStateException: Not a JSON Object: true
Stacktrace:
	at com.google.gson.JsonElement.getAsJsonObject(JsonElement.java:90) ~[gson-2.8.0.jar:?] {}
	at mcjty.lostcities.config.Configuration.fromJson(Configuration.java:135) ~[?:1.16-4.0.12-beta] {re:classloading}
	at mcjty.lostcities.config.LostCityProfile.<init>(LostCityProfile.java:225) ~[?:1.16-4.0.12-beta] {re:classloading}
	at mcjty.lostcities.config.LostCityConfiguration.readProfiles(LostCityConfiguration.java:468) ~[?:1.16-4.0.12-beta] {re:classloading}
	at mcjty.lostcities.config.LostCityConfiguration.setupProfiles(LostCityConfiguration.java:458) ~[?:1.16-4.0.12-beta] {re:classloading}
	at mcjty.lostcities.setup.ModSetup.init(ModSetup.java:35) ~[?:1.16-4.0.12-beta] {re:classloading}
	at mcjty.lostcities.LostCities$$Lambda$3194/1871273878.accept(Unknown Source) ~[?:?] {}
	at net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:247) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:239) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.eventbus.EventBus$$Lambda$2972/1638472859.invoke(Unknown Source) ~[?:?] {}
	at net.minecraftforge.eventbus.EventBus$$Lambda$3233/39871652.invoke(Unknown Source) ~[?:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.acceptEvent(FMLModContainer.java:106) ~[?:36.2] {re:classloading}
	at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$4(ModContainer.java:107) ~[?:?] {re:classloading}
	at net.minecraftforge.fml.ModContainer$$Lambda$3145/765551203.run(Unknown Source) ~[?:?] {}
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1618) ~[?:1.8.0_51] {}
	at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1610) ~[?:1.8.0_51] {}
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289) ~[?:1.8.0_51] {}
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056) ~[?:1.8.0_51] {}
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1689) ~[?:1.8.0_51] {}
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157) ~[?:1.8.0_51] {}

-- System Details --
Details:
	Minecraft Version: 1.16.5
	Minecraft Version ID: 1.16.5
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 3117628016 bytes (2973 MB) / 3657433088 bytes (3488 MB) up to 4294967296 bytes (4096 MB)
	CPUs: 12
	JVM Flags: 10 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -XX:+IgnoreUnrecognizedVMOptions -Xmx4G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	ModLauncher: 8.1.3+8.1.3+main-8.1.x.c94d18ec
	ModLauncher launch target: fmlclient
	ModLauncher naming: srg
	ModLauncher services: 
		/mixin-0.8.4.jar mixin PLUGINSERVICE 
		/eventbus-4.0.0.jar eventbus PLUGINSERVICE 
		/forge-1.16.5-36.2.39.jar object_holder_definalize PLUGINSERVICE 
		/forge-1.16.5-36.2.39.jar runtime_enum_extender PLUGINSERVICE 
		/accesstransformers-3.0.1.jar accesstransformer PLUGINSERVICE 
		/forge-1.16.5-36.2.39.jar capability_inject_definalize PLUGINSERVICE 
		/forge-1.16.5-36.2.39.jar runtimedistcleaner PLUGINSERVICE 
		/mixin-0.8.4.jar mixin TRANSFORMATIONSERVICE 
		/forge-1.16.5-36.2.39.jar fml TRANSFORMATIONSERVICE 
	FML: 36.2
	Forge: net.minecraftforge:36.2.39
	FML Language Providers: 
		javafml@36.2
		minecraft@1
	Mod List: 
		forge-1.16.5-36.2.39-client.jar                   |Minecraft                     |minecraft                     |1.16.5              |SIDED_SETU|Manifest: NOSIGNATURE
		Zombie+Extreme+1.16.5+1.8.2.jar                   |Zombie Extreme                |zombie_extreme                |1.8.2               |SIDED_SETU|Manifest: NOSIGNATURE
		lostcities-1.16-4.0.12-beta.jar                   |LostCities                    |lostcities                    |1.16-4.0.12-beta    |ERROR     |Manifest: NOSIGNATURE
		forge-1.16.5-36.2.39-universal.jar                |Forge                         |forge                         |36.2.39             |SIDED_SETU|Manifest: 22:af:21:d8:19:82:7f:93:94:fe:2b:ac:b7:e4:41:57:68:39:87:b1:a7:5c:c6:44:f9:25:74:21:14:f5:0d:90
		valhelsia_core-16.0.15.jar                        |Valhelsia Core                |valhelsia_core                |16.0.15             |SIDED_SETU|Manifest: NOSIGNATURE
		valhelsia_structures-1.16.5-0.1.6.jar             |Valhelsia Structures          |valhelsia_structures          |1.16.5-0.1.6        |SIDED_SETU|Manifest: NOSIGNATURE
	Crash Report UUID: aa88b188-f93c-4312-bc11-049c94d71a46

**Comment by McJty** [comment]
This is caused by a bad config or profile somewhere. What did you change and how are you creating the world?

**Comment by jackgames55** [comment]
i was experiencing a different issue and i was told that deleting a certain .json it would work and it did but after a while it started to do this

**Comment by McJty** [comment]
Can you be more specific? What certain json?

**Comment by jackgames55** [comment]
i don't remember the specific one but these are the ones that are left 
["/assets/lostcities/citydata/conditions.json", "/assets/lostcities/citydata/palette.json", "/assets/lostcities/citydata/palette_desert.json", "/assets/lostcities/citydata/palette_chisel.json", "/assets/lostcities/citydata/palette_chisel_desert.json", "/assets/lostcities/citydata/highwayparts.json", "/assets/lostcities/citydata/railparts.json", "/assets/lostcities/citydata/buildingparts.json", "/assets/lostcities/citydata/library.json", "$lostcities/userassets.json"]

**Comment by jackgames55** [comment]
i do remember that it was only one json

**Comment by McJty** [comment]
Don't mess with those. Please restore and then we can solve whatever issue you had the good way

**Comment by jackgames55** [comment]
ok im sorry for my inexperience but how do i restore it

**Comment by jackgames55** [comment]
ok i did a full reset on the file and it worked thank you so much for how fast you responded i really appreciate it

**Comment by ellicprime** [comment]
Ok so how do I do a full reset?
![image](https://user-images.githubusercontent.com/117617825/200221901-60a495fa-e9d4-41da-afc8-30fc2e0156e1.png)

Thats an Image of my mods
Idk what to do lol

**Comment by McJty** [comment]
You remove the lost cities config folder

**Comment by ellicprime** [comment]
Ok, how do I put it back in?
I already tried downloading it again.

**Comment by McJty** [comment]
Just remove it. It will be put back automatically when the game starts

**Comment by ellicprime** [comment]
Remove what the mod?

**Comment by McJty** [comment]
I already told you: the Lost Cities config folder

**Comment by ellicprime** [comment]
Ok how do u remove the config folder?

**Comment by McJty** [comment]
You just do? I'm not going to explain how to use your computer. That's basic knowledge

**Comment by ellicprime** [comment]
Ight

**Comment by strubium** [comment]
> Ok how do u remove the config folder?

fam just delete the folder that the config stuff is inside.

**Comment by ColdKoala19** [comment]
HELP ME I HAVE THIS PROBLEM TOO How Do I Delete My Config Folder

**Comment by ColdKoala19** [comment]
---- Minecraft Crash Report ----
// Why did you do that?

Time: 7/19/23 7:15 PM
Description: Mod loading error has occurred

java.lang.Exception: Mod Loading has failed
	at net.minecraftforge.fml.CrashReportExtender.dumpModLoadingCrashReport(CrashReportExtender.java:71) [?:?] {re:classloading}
	at net.minecraftforge.fml.client.ClientModLoader.completeModLoading(ClientModLoader.java:174) [?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.lambda$null$1(Minecraft.java:508) [?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:tac.mixins.json:client.MinecraftStaticMixin,pl:mixin:APP:architectury.mixins.json:MixinMinecraft,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft$$Lambda$5212/835020577.run(Unknown Source) [?:?] {}
	at net.minecraft.util.Util.func_215077_a(Util.java:430) [?:?] {re:classloading,xf:OptiFine:default}
	at net.minecraft.client.Minecraft.lambda$new$2(Minecraft.java:504) [?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:tac.mixins.json:client.MinecraftStaticMixin,pl:mixin:APP:architectury.mixins.json:MixinMinecraft,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft$$Lambda$4630/1972193961.accept(Unknown Source) [?:?] {}
	at net.minecraft.client.gui.ResourceLoadProgressGui.func_230430_a_(ResourceLoadProgressGui.java:172) [?:?] {re:classloading,xf:OptiFine:default}
	at net.minecraft.client.renderer.GameRenderer.func_195458_a(GameRenderer.java:802) [?:?] {re:mixin,pl:accesstransformer:B,xf:OptiFine:default,re:classloading,pl:accesstransformer:B,xf:OptiFine:default,pl:mixin:APP:cgm.mixins.json:client.GameRendererMixin,pl:mixin:APP:tac.mixins.json:client.GameRendererMixin,pl:mixin:APP:forge-mca.mixin.json:client.MixinGameRenderer,pl:mixin:A}
	at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:977) [?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:tac.mixins.json:client.MinecraftStaticMixin,pl:mixin:APP:architectury.mixins.json:MixinMinecraft,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:607) [?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:tac.mixins.json:client.MinecraftStaticMixin,pl:mixin:APP:architectury.mixins.json:MixinMinecraft,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:184) [?:?] {re:classloading,pl:runtimedistcleaner:A}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51] {}
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:37) [forge-1.16.5-36.2.39.jar:36.2] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$468/655059806.call(Unknown Source) [forge-1.16.5-36.2.39.jar:36.2] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-8.1.3.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-8.1.3.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-8.1.3.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82) [modlauncher-8.1.3.jar:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) [modlauncher-8.1.3.jar:?] {}


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at com.google.gson.JsonElement.getAsJsonObject(JsonElement.java:90) ~[gson-2.8.0.jar:?] {}
-- MOD lostcities --
Details:
	Mod File: lostcities-1.16-4.0.12-beta.jar
	Failure message: LostCities (lostcities) encountered an error during the common_setup event phase
		java.lang.IllegalStateException: Not a JSON Object: true
	Mod Version: 1.16-4.0.12-beta
	Mod Issue URL: http://github.com/McJtyMods/LostCities/issues
	Exception message: java.lang.IllegalStateException: Not a JSON Object: true
Stacktrace:
	at com.google.gson.JsonElement.getAsJsonObject(JsonElement.java:90) ~[gson-2.8.0.jar:?] {}
	at mcjty.lostcities.config.Configuration.fromJson(Configuration.java:135) ~[?:1.16-4.0.12-beta] {re:classloading}
	at mcjty.lostcities.config.LostCityProfile.<init>(LostCityProfile.java:225) ~[?:1.16-4.0.12-beta] {re:classloading}
	at mcjty.lostcities.config.LostCityConfiguration.readProfiles(LostCityConfiguration.java:468) ~[?:1.16-4.0.12-beta] {re:classloading}
	at mcjty.lostcities.config.LostCityConfiguration.setupProfiles(LostCityConfiguration.java:458) ~[?:1.16-4.0.12-beta] {re:classloading}
	at mcjty.lostcities.setup.ModSetup.init(ModSetup.java:35) ~[?:1.16-4.0.12-beta] {re:classloading}
	at mcjty.lostcities.LostCities$$Lambda$3724/1305121807.accept(Unknown Source) ~[?:?] {}
	at net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:247) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:239) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.eventbus.EventBus$$Lambda$2928/1949709901.invoke(Unknown Source) ~[?:?] {}
	at net.minecraftforge.eventbus.EventBus$$Lambda$3244/1360747626.invoke(Unknown Source) ~[?:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.acceptEvent(FMLModContainer.java:106) ~[?:36.2] {re:classloading}
	at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$4(ModContainer.java:107) ~[?:?] {re:classloading}
	at net.minecraftforge.fml.ModContainer$$Lambda$3123/117701189.run(Unknown Source) ~[?:?] {}
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1618) ~[?:1.8.0_51] {}
	at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1610) ~[?:1.8.0_51] {}
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289) ~[?:1.8.0_51] {}
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056) ~[?:1.8.0_51] {}
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1689) ~[?:1.8.0_51] {re:computing_frames}
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157) ~[?:1.8.0_51] {}


-- System Details --
Details:
	Minecraft Version: 1.16.5
	Minecraft Version ID: 1.16.5
	Operating System: Windows 7 (amd64) version 6.1
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 135281864 bytes (129 MB) / 559472640 bytes (533 MB) up to 2771779584 bytes (2643 MB)
	CPUs: 2
	JVM Flags: 5 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -XX:+IgnoreUnrecognizedVMOptions -Xmx2660M -XX:+UseConcMarkSweepGC
	ModLauncher: 8.1.3+8.1.3+main-8.1.x.c94d18ec
	ModLauncher launch target: fmlclient
	ModLauncher naming: srg
	ModLauncher services: 
		/mixin-0.8.4.jar mixin PLUGINSERVICE 
		/eventbus-4.0.0.jar eventbus PLUGINSERVICE 
		/forge-1.16.5-36.2.39.jar object_holder_definalize PLUGINSERVICE 
		/forge-1.16.5-36.2.39.jar runtime_enum_extender PLUGINSERVICE 
		/accesstransformers-3.0.1.jar accesstransformer PLUGINSERVICE 
		/forge-1.16.5-36.2.39.jar capability_inject_definalize PLUGINSERVICE 
		/forge-1.16.5-36.2.39.jar runtimedistcleaner PLUGINSERVICE 
		/mixin-0.8.4.jar mixin TRANSFORMATIONSERVICE 
		/OptiFine-OptiFine-1.16.5_HD_U_G8_pre2.jar OptiFine TRANSFORMATIONSERVICE 
		/forge-1.16.5-36.2.39.jar fml TRANSFORMATIONSERVICE 
	FML: 36.2
	Forge: net.minecraftforge:36.2.39
	FML Language Providers: 
		javafml@36.2
		minecraft@1
	Mod List: 
		forge-1.16.5-36.2.39-client.jar                   |Minecraft                     |minecraft                     |1.16.5              |SIDED_SETU|Manifest: NOSIGNATURE
		TenshiLib-1.16.3-1.3.0.jar                        |TenshiLib                     |tenshilib                     |1.16.3-1.3.0        |SIDED_SETU|Manifest: NOSIGNATURE
		cgm-1.2.6-1.16.5.jar                              |MrCrayfish's Gun Mod          |cgm                           |1.2.6               |SIDED_SETU|Manifest: NOSIGNATURE
		Dayzombies_rebooted-1.0.1_1.16.5.jar              |dayzombierebooted             |dayzombierebooted             |1.0.0               |SIDED_SETU|Manifest: NOSIGNATURE
		bunker-down+1-1-0.jar                             |Bunker Down                   |bunker_down                   |1.1.0               |SIDED_SETU|Manifest: NOSIGNATURE
		Horror+Elements+mod+1.16.5_Halloween_update.jar   |Horror elements mod           |horror_elements_mod           |1.0.0               |SIDED_SETU|Manifest: NOSIGNATURE
		incontrol-1.16-5.2.12.jar                         |InControl                     |incontrol                     |1.16-5.2.12         |SIDED_SETU|Manifest: NOSIGNATURE
		libraryferret-forge-1.16.5-3.0.0.jar              |Library ferret                |libraryferret                 |3.0.0               |SIDED_SETU|Manifest: NOSIGNATURE
		day_counter_v1.0_1.16.5_[FORGE].jar               |Day Counter                   |ag_day_counter                |1.0.0               |SIDED_SETU|Manifest: NOSIGNATURE
		tac-r-0.3.5.3-1.16.5.jar                          |Timeless and Classics Guns    |tac                           |0.3.5.3             |SIDED_SETU|Manifest: NOSIGNATURE
		Zombie+Mob+drops+1.16.5+v3.jar                    |zombie drops                  |zombie_drops_                 |1.0.0               |SIDED_SETU|Manifest: NOSIGNATURE
		InsaneLib-1.4.1-mc1.16.5.jar                      |InsaneLib                     |insanelib                     |1.4.1               |SIDED_SETU|Manifest: NOSIGNATURE
		curios-forge-1.16.5-4.1.0.0.jar                   |Curios API                    |curios                        |1.16.5-4.1.0.0      |SIDED_SETU|Manifest: NOSIGNATURE
		collective-1.16.5-5.49.jar                        |Collective                    |collective                    |5.49                |SIDED_SETU|Manifest: NOSIGNATURE
		mobsunscreen-1.16.4-2.1.3 (1).jar                 |Mob Sunscreen                 |mobsunscreen                  |1.16.4-2.1.3        |SIDED_SETU|Manifest: NOSIGNATURE
		philips+ruin+1.0.jar                              |philips ruins                 |philips_ruins                 |1.0.0               |SIDED_SETU|Manifest: NOSIGNATURE
		bettervillage-forge-1.16.5-2.0.0.jar              |Better village                |bettervillage                 |2.0.0               |SIDED_SETU|Manifest: NOSIGNATURE
		additional-guns-0.7.0-1.16.5.jar                  |Additional Guns               |additionalguns                |0.7.0               |SIDED_SETU|Manifest: NOSIGNATURE
		lostcities-1.16-4.0.12-beta.jar                   |LostCities                    |lostcities                    |1.16-4.0.12-beta    |ERROR     |Manifest: NOSIGNATURE
		obfuscate-0.6.3-1.16.5.jar                        |Obfuscate                     |obfuscate                     |0.6.3               |SIDED_SETU|Manifest: NOSIGNATURE
		BadMobs-1.16.5-9.0.5.jar                          |BadMobs                       |badmobs                       |9.0.5               |SIDED_SETU|Manifest: eb:c4:b1:67:8b:f9:0c:db:dc:4f:01:b1:8e:61:64:39:4c:10:85:0b:a6:c4:c7:48:f0:fa:95:f2:cb:08:3a:e5
		farsightedmobs-1.0.jar                            |Farsighted Mobs               |farsightedmobs                |1.0                 |SIDED_SETU|Manifest: NOSIGNATURE
		guardvillagers-1.16.5.1.2.6.jar                   |Guard Villagers               |guardvillagers                |1.2.6               |SIDED_SETU|Manifest: NOSIGNATURE
		starterkit_1.16.5-4.0.jar                         |Starter Kit                   |starterkit                    |4.0                 |SIDED_SETU|Manifest: NOSIGNATURE
		architectury-1.32.68.jar                          |Architectury                  |architectury                  |1.32.68             |SIDED_SETU|Manifest: NOSIGNATURE
		minecraft-comes-alive-7.3.23+1.16.5-universal.jar |Minecraft Comes Alive         |mca                           |7.3.23+1.16.5       |SIDED_SETU|Manifest: NOSIGNATURE
		EnhancedAI-1.2.3-mc1.16.5.jar                     |Enhanced AI                   |enhancedai                    |1.2.3               |SIDED_SETU|Manifest: NOSIGNATURE
		forge-1.16.5-36.2.39-universal.jar                |Forge                         |forge

**Comment by McJty** [comment]
Go to your Minecraft instance and the config folder in there and then delete the lost city config

**Comment by Justinjop** [comment]
> You remove the lost cities config folder

Thanks. It worked.
