### ISSUE TITLE
The command lc_debug does not work on Sponge.

### ISSUE THREAD

**Issue by BlayzerQ** [McJty/LostCities#50]
The command lc_debug does not work on Sponge.
If you type this command, you get an error:
https://pastebin.com/TzQTY39z
`[16:59:58] [Server thread/ERROR] [Sponge/]: Error occurred while executing command 'lc_debug' for source EntityPlayerMP['Blayzer'/2092, l='world', x=-150.77, y=82.00, z=137.50]: org.spongepowered.mod.world.gen.SpongeChunkGeneratorForge cannot be cast to mcjty.lostcities.dimensions.world.LostCityChunkGenerator
java.lang.ClassCastException: org.spongepowered.mod.world.gen.SpongeChunkGeneratorForge cannot be cast to mcjty.lostcities.dimensions.world.LostCityChunkGenerator
	at mcjty.lostcities.commands.CommandDebug.func_184881_a(CommandDebug.java:43) ~[CommandDebug.class:?]
	at net.minecraft.command.CommandHandler.func_175786_a(CommandHandler.java:104) ~[k.class:?]
	at org.spongepowered.common.command.MinecraftCommandWrapper.tryExecute(MinecraftCommandWrapper.java:151) ~[MinecraftCommandWrapper.class:1.10.2-2281-5.2.0-BETA-2597]
	at org.spongepowered.common.command.MinecraftCommandWrapper.process(MinecraftCommandWrapper.java:137) ~[MinecraftCommandWrapper.class:1.10.2-2281-5.2.0-BETA-2597]
	at org.spongepowered.api.command.dispatcher.SimpleDispatcher.process(SimpleDispatcher.java:336) ~[SimpleDispatcher.class:1.10.2-2281-5.2.0-BETA-2597]
	at org.spongepowered.common.command.SpongeCommandManager.process(SpongeCommandManager.java:291) ~[SpongeCommandManager.class:1.10.2-2281-5.2.0-BETA-2597]
	at net.minecraft.command.ServerCommandManager.func_71556_a(SourceFile:1083) ~[bd.class:?]
	at net.minecraft.network.NetHandlerPlayServer.func_147361_d(NetHandlerPlayServer.java:913) ~[me.class:?]
	at net.minecraft.network.NetHandlerPlayServer.func_147354_a(NetHandlerPlayServer.java:892) ~[me.class:?]
	at net.minecraft.network.play.client.CPacketChatMessage.func_148833_a(SourceFile:37) ~[im.class:?]
	at net.minecraft.network.play.client.CPacketChatMessage.func_148833_a(SourceFile:9) ~[im.class:?]
	at org.spongepowered.common.network.PacketUtil.lambda$onProcessPacket$0(PacketUtil.java:157) ~[PacketUtil.class:1.10.2-2281-5.2.0-BETA-2597]
	at org.spongepowered.common.event.tracking.CauseTracker.switchToPhase(CauseTracker.java:163) [CauseTracker.class:1.10.2-2281-5.2.0-BETA-2597]
	at org.spongepowered.common.network.PacketUtil.onProcessPacket(PacketUtil.java:156) [PacketUtil.class:1.10.2-2281-5.2.0-BETA-2597]
	at net.minecraft.network.PacketThreadUtil$1.redirect$onProcessPacket$zjj000(SourceFile:539) [fl$1.class:?]
	at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) [fl$1.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_91]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_91]
	at net.minecraft.util.Util.func_181617_a(SourceFile:45) [h.class:?]
	at org.spongepowered.common.SpongeImplHooks.onUtilRunTask(SpongeImplHooks.java:238) [SpongeImplHooks.class:1.10.2-2281-5.2.0-BETA-2597]
	at net.minecraft.server.MinecraftServer.redirect$onRun$zhp000(MinecraftServer.java:3951) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:668) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:387) [ld.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_91]`

**Comment by Deamon5550** [comment]
May as well close this, if its anything its an issue with sponge.
