### ISSUE TITLE
Bound must be positive 

### ISSUE THREAD

**Issue by Artembelov** [McJty/LostCities#510]
32: ASM: INSTANCE worldTick(Lnet/minecraftforge/event/TickEvent$WorldTickEvent;)V
		33: ASM: com.github.alexthe668.domesticationinnovation.client.ClientProxy@5ad41827 onServerTick(Lnet/minecraftforge/event/TickEvent$WorldTickEvent;)V
		34: ASM: class com.github.alexthe666.alexsmobs.event.ServerEvents onServerTick(Lnet/minecraftforge/event/TickEvent$WorldTickEvent;)V
		35: ASM: class com.simibubi.create.events.CommonEvents onWorldTick(Lnet/minecraftforge/event/TickEvent$WorldTickEvent;)V
		36: ASM: mcjty.lostcities.setup.ForgeEventHandlers@39fb45c0 onWorldTick(Lnet/minecraftforge/event/TickEvent$WorldTickEvent;)V
		37: ASM: top.theillusivec4.curios.common.event.CuriosEventHandler@1a34a5d9 worldTick(Lnet/minecraftforge/event/TickEvent$WorldTickEvent;)V
		38: ASM: top.theillusivec4.polymorph.common.CommonEventsListener@246e334e worldTick(Lnet/minecraftforge/event/TickEvent$WorldTickEvent;)V
		39: net.minecraftforge.eventbus.EventBus$$Lambda$3176/0x0000000080c80cd8@51c239f6
		40: ASM: com.natamus.collective.events.CollectiveEvents@2447462 onWorldTick(Lnet/minecraftforge/event/TickEvent$WorldTickEvent;)V
java.util.concurrent.CompletionException: net.minecraft.ReportedException: Feature placement
	at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:315)
	at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:320)
	at java.base/java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1159)
	at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482)
	at TRANSFORMER/minecraft@1.18.2/net.minecraft.server.level.ChunkTaskPriorityQueueSorter.m_143188_(ChunkTaskPriorityQueueSorter.java:62)
	at TRANSFORMER/minecraft@1.18.2/net.minecraft.util.thread.ProcessorMailbox.m_18759_(ProcessorMailbox.java:91)
	at TRANSFORMER/minecraft@1.18.2/net.minecraft.util.thread.ProcessorMailbox.m_18747_(ProcessorMailbox.java:146)
	at TRANSFORMER/minecraft@1.18.2/net.minecraft.util.thread.ProcessorMailbox.run(ProcessorMailbox.java:102)
	at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1395)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
Caused by: net.minecraft.ReportedException: Feature placement
	at TRANSFORMER/minecraft@1.18.2/net.minecraft.server.level.ChunkMap.lambda$scheduleChunkGeneration$22(ChunkMap.java:604)
	at MC-BOOTSTRAP/datafixerupper@4.1.27/com.mojang.datafixers.util.Either$Left.map(Either.java:38)
	at TRANSFORMER/minecraft@1.18.2/net.minecraft.server.level.ChunkMap.lambda$scheduleChunkGeneration$24(ChunkMap.java:587)
	at java.base/java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1150)
	... 11 more
Caused by: java.lang.IllegalArgumentException: bound must be positive
	at java.base/java.util.Random.nextInt(Random.java:322)
	at TRANSFORMER/lostcities@1.18-5.3.13/mcjty.lostcities.worldgen.lost.BuildingInfo.<init>(BuildingInfo.java:842)
	at TRANSFORMER/lostcities@1.18-5.3.13/mcjty.lostcities.worldgen.lost.BuildingInfo.getBuildingInfo(BuildingInfo.java:673)
	at TRANSFORMER/lostcities@1.18-5.3.13/mcjty.lostcities.worldgen.lost.BuildingInfo.getZmin(BuildingInfo.java:223)
	at TRANSFORMER/lostcities@1.18-5.3.13/mcjty.lostcities.worldgen.lost.BuildingInfo.getDesiredMaxHeightL1(BuildingInfo.java:1694)
	at TRANSFORMER/lostcities@1.18-5.3.13/mcjty.lostcities.worldgen.lost.BuildingInfo.updateMinMaxL2(BuildingInfo.java:1758)
	at TRANSFORMER/lostcities@1.18-5.3.13/mcjty.lostcities.worldgen.lost.BuildingInfo.getDesiredMaxHeightL2(BuildingInfo.java:1749)
	at TRANSFORMER/lostcities@1.18-5.3.13/mcjty.lostcities.worldgen.LostCityTerrainFeature.correctTerrainShape(LostCityTerrainFeature.java:1130)
	at TRANSFORMER/lostcities@1.18-5.3.13/mcjty.lostcities.worldgen.LostCityTerrainFeature.doNormalChunk(LostCityTerrainFeature.java:528)
	at TRANSFORMER/lostcities@1.18-5.3.13/mcjty.lostcities.worldgen.LostCityTerrainFeature.generate(LostCityTerrainFeature.java:292)
	at TRANSFORMER/lostcities@1.18-5.3.13/mcjty.lostcities.worldgen.LostCityFeature.m_142674_(LostCityFeature.java:74)
	at TRANSFORMER/minecraft@1.18.2/net.minecraft.world.level.levelgen.feature.Feature.m_204740_(Feature.java:153)
	at TRANSFORMER/minecraft@1.18.2/net.minecraft.world.level.levelgen.feature.ConfiguredFeature.m_65385_(ConfiguredFeature.java:27)
	at TRANSFORMER/minecraft@1.18.2/net.minecraft.world.level.levelgen.placement.PlacedFeature.m_191789_(PlacedFeature.java:56)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
	at java.base/java.util.stream.IntPipeline$1$1.accept(IntPipeline.java:180)
	at java.base/java.util.stream.Streams$RangeIntSpliterator.forEachRemaining(Streams.java:104)
	at java.base/java.util.Spliterator$OfInt.forEachRemaining(Spliterator.java:711)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596)
	at java.base/java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:276)
	at java.base/java.util.stream.Streams$StreamBuilderImpl.forEachRemaining(Streams.java:411)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596)
	at TRANSFORMER/minecraft@1.18.2/net.minecraft.world.level.levelgen.placement.PlacedFeature.m_191797_(PlacedFeature.java:55)
	at TRANSFORMER/minecraft@1.18.2/net.minecraft.world.level.levelgen.placement.PlacedFeature.m_191806_(PlacedFeature.java:44)
	at TRANSFORMER/minecraft@1.18.2/net.minecraft.world.level.chunk.ChunkGenerator.m_183372_(ChunkGenerator.java:475)
	at TRANSFORMER/minecraft@1.18.2/net.minecraft.world.level.chunk.ChunkStatus.m_187807_(ChunkStatus.java:135)
	at TRANSFORMER/minecraft@1.18.2/net.minecraft.world.level.chunk.ChunkStatus.m_187788_(ChunkStatus.java:262)
	at TRANSFORMER/minecraft@1.18.2/net.minecraft.server.level.ChunkMap.lambda$scheduleChunkGeneration$22(ChunkMap.java:589)
	... 14 more

[15:19:20] [Server thread/ERROR]: Encountered an unexpected exception
java.util.concurrent.CompletionException: net.minecraft.ReportedException: Feature placement
	at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:315) ~[?:?]
	at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:320) ~[?:?]
	at java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1159) ~[?:?]
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482) ~[?:?]
	at net.minecraft.server.level.ChunkTaskPriorityQueueSorter.m_143188_(ChunkTaskPriorityQueueSorter.java:62) ~[client-1.18.2-20220404.173914-srg.jar%23460!/:?]
	at net.minecraft.util.thread.ProcessorMailbox.m_18759_(ProcessorMailbox.java:91) ~[client-1.18.2-20220404.173914-srg.jar%23460!/:?]
	at net.minecraft.util.thread.ProcessorMailbox.m_18747_(ProcessorMailbox.java:146) ~[client-1.18.2-20220404.173914-srg.jar%23460!/:?]
	at net.minecraft.util.thread.ProcessorMailbox.run(ProcessorMailbox.java:102) ~[client-1.18.2-20220404.173914-srg.jar%23460!/:?]
	at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1395) ~[?:?]
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?]
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?]
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?]
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?]
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?]
Caused by: net.minecraft.ReportedException: Feature placement
	at net.minecraft.server.level.ChunkMap.lambda$scheduleChunkGeneration$22(ChunkMap.java:604) ~[client-1.18.2-20220404.173914-srg.jar%23460!/:?]
	at com.mojang.datafixers.util.Either$Left.map(Either.java:38) ~[datafixerupper-4.1.27.jar%2334!/:?]
	at net.minecraft.server.level.ChunkMap.lambda$scheduleChunkGeneration$24(ChunkMap.java:587) ~[client-1.18.2-20220404.173914-srg.jar%23460!/:?]
	at java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1150) ~[?:?]
	... 11 more
Caused by: java.lang.IllegalArgumentException: bound must be positive
	at java.util.Random.nextInt(Random.java:322) ~[?:?]
	at mcjty.lostcities.worldgen.lost.BuildingInfo.<init>(BuildingInfo.java:842) ~[lostcities-1.18-5.3.13.jar%23270!/:1.18-5.3.13]
	at mcjty.lostcities.worldgen.lost.BuildingInfo.getBuildingInfo(BuildingInfo.java:673) ~[lostcities-1.18-5.3.13.jar%23270!/:1.18-5.3.13]
	at mcjty.lostcities.worldgen.lost.BuildingInfo.getZmin(BuildingInfo.java:223) ~[lostcities-1.18-5.3.13.jar%23270!/:1.18-5.3.13]
	at mcjty.lostcities.worldgen.lost.BuildingInfo.getDesiredMaxHeightL1(BuildingInfo.java:1694) ~[lostcities-1.18-5.3.13.jar%23270!/:1.18-5.3.13]
	at mcjty.lostcities.worldgen.lost.BuildingInfo.updateMinMaxL2(BuildingInfo.java:1758) ~[lostcities-1.18-5.3.13.jar%23270!/:1.18-5.3.13]
	at mcjty.lostcities.worldgen.lost.BuildingInfo.getDesiredMaxHeightL2(BuildingInfo.java:1749) ~[lostcities-1.18-5.3.13.jar%23270!/:1.18-5.3.13]
	at mcjty.lostcities.worldgen.LostCityTerrainFeature.correctTerrainShape(LostCityTerrainFeature.java:1130) ~[lostcities-1.18-5.3.13.jar%23270!/:1.18-5.3.13]
	at mcjty.lostcities.worldgen.LostCityTerrainFeature.doNormalChunk(LostCityTerrainFeature.java:528) ~[lostcities-1.18-5.3.13.jar%23270!/:1.18-5.3.13]
	at mcjty.lostcities.worldgen.LostCityTerrainFeature.generate(LostCityTerrainFeature.java:292) ~[lostcities-1.18-5.3.13.jar%23270!/:1.18-5.3.13]
	at mcjty.lostcities.worldgen.LostCityFeature.m_142674_(LostCityFeature.java:74) ~[lostcities-1.18-5.3.13.jar%23270!/:1.18-5.3.13]
	at net.minecraft.world.level.levelgen.feature.Feature.m_204740_(Feature.java:153) ~[client-1.18.2-20220404.173914-srg.jar%23460!/:?]
	at net.minecraft.world.level.levelgen.feature.ConfiguredFeature.m_65385_(ConfiguredFeature.java:27) ~[client-1.18.2-20220404.173914-srg.jar%23460!/:?]
	at net.minecraft.world.level.levelgen.placement.PlacedFeature.m_191789_(PlacedFeature.java:56) ~[client-1.18.2-20220404.173914-srg.jar%23460!/:?]
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183) ~[?:?]
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183) ~[?:?]
	at java.util.stream.IntPipeline$1$1.accept(IntPipeline.java:180) ~[?:?]
	at java.util.stream.Streams$RangeIntSpliterator.forEachRemaining(Streams.java:104) ~[?:?]
	at java.util.Spliterator$OfInt.forEachRemaining(Spliterator.java:711) ~[?:?]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509) ~[?:?]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?]
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150) ~[?:?]
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173) ~[?:?]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596) ~[?:?]
	at java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:276) ~[?:?]
	at java.util.stream.Streams$StreamBuilderImpl.forEachRemaining(Streams.java:411) ~[?:?]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509) ~[?:?]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?]
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150) ~[?:?]
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173) ~[?:?]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596) ~[?:?]
	at net.minecraft.world.level.levelgen.placement.PlacedFeature.m_191797_(PlacedFeature.java:55) ~[client-1.18.2-20220404.173914-srg.jar%23460!/:?]
	at net.minecraft.world.level.levelgen.placement.PlacedFeature.m_191806_(PlacedFeature.java:44) ~[client-1.18.2-20220404.173914-srg.jar%23460!/:?]
	at net.minecraft.world.level.chunk.ChunkGenerator.m_183372_(ChunkGenerator.java:475) ~[client-1.18.2-20220404.173914-srg.jar%23460!/:?]
	at net.minecraft.world.level.chunk.ChunkStatus.m_187807_(ChunkStatus.java:135) ~[client-1.18.2-20220404.173914-srg.jar%23460!/:?]
	at net.minecraft.world.level.chunk.ChunkStatus.m_187788_(ChunkStatus.java:262) ~[client-1.18.2-20220404.173914-srg.jar%23460!/:?]
	at net.minecraft.server.level.ChunkMap.lambda$scheduleChunkGeneration$22(ChunkMap.java:589) ~[client-1.18.2-20220404.173914-srg.jar%23460!/:?]
	at com.mojang.datafixers.util.Either$Left.map(Either.java:38) ~[datafixerupper-4.1.27.jar%2334!/:?]
	at net.minecraft.server.level.ChunkMap.lambda$scheduleChunkGeneration$24(ChunkMap.java:587) ~[client-1.18.2-20220404.173914-srg.jar%23460!/:?]
	at java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1150) ~[?:?]
	... 11 more
[15:19:20] [Server thread/FATAL]: Preparing crash report

**Comment by McJty** [comment]
More info please! What are you doing? What profile? Did you make any modifications?
