### ISSUE TITLE
1.18.2 Error with pregen

### ISSUE THREAD

**Issue by UrbanSide** [McJty/LostCities#515]
I use https://www.curseforge.com/minecraft/mc-mods/chunkpregenerator and Lost City,have this error.I don’t know who to write to, so I wrote this error to the generator and here)
```
java.lang.ArrayIndexOutOfBoundsException: Index 1492 out of bounds for length 1025
	at it.unimi.dsi.fastutil.longs.LongLinkedOpenHashSet.removeFirstLong(LongLinkedOpenHashSet.java:601) ~[fastutil-8.5.6.jar%2330!/:?] {}
	at net.minecraft.world.level.lighting.DynamicGraphMinFixedPoint.m_75588_(DynamicGraphMinFixedPoint.java:195) ~[server-1.18.2-20220404.173914-srg.jar%23238!/:?] {re:classloading}
	at net.minecraft.server.level.DistanceManager$ChunkTicketTracker.m_140877_(DistanceManager.java:511) ~[server-1.18.2-20220404.173914-srg.jar%23238!/:?] {re:classloading}
	at net.minecraft.server.level.DistanceManager.m_140805_(DistanceManager.java:118) ~[server-1.18.2-20220404.173914-srg.jar%23238!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:chunkpregen.mixins.json:common.storage.TicketManagerMixin,pl:mixin:A}
	at net.minecraft.server.level.ServerChunkCache.m_8489_(ServerChunkCache.java:283) ~[server-1.18.2-20220404.173914-srg.jar%23238!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:chunkpregen.mixins.json:common.storage.ServerChunkProviderMixin,pl:mixin:A,re:mixin,pl:accesstransformer:B}
	at net.minecraft.server.level.ServerChunkCache$MainThreadExecutor.m_7245_(ServerChunkCache.java:602) ~[server-1.18.2-20220404.173914-srg.jar%23238!/:?] {re:classloading}
	at net.minecraft.util.thread.BlockableEventLoop.m_18701_(BlockableEventLoop.java:140) ~[server-1.18.2-20220404.173914-srg.jar%23238!/:?] {re:computing_frames,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B}
	at net.minecraft.server.level.ServerChunkCache.m_7587_(ServerChunkCache.java:131) ~[server-1.18.2-20220404.173914-srg.jar%23238!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:chunkpregen.mixins.json:common.storage.ServerChunkProviderMixin,pl:mixin:A,re:mixin,pl:accesstransformer:B}
	at net.minecraft.world.level.Level.m_6522_(Level.java:299) ~[server-1.18.2-20220404.173914-srg.jar%23238!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:kubejs-common.mixins.json:LevelMixin,pl:mixin:APP:sereneseasons.mixins.json:MixinLevel,pl:mixin:APP:lootr.mixins.json:MixinLevel,pl:mixin:A}
	at net.minecraft.world.level.LevelReader.m_46819_(LevelReader.java:123) ~[server-1.18.2-20220404.173914-srg.jar%23238!/:?] {re:computing_frames,re:classloading,re:mixin}
	at net.minecraft.world.level.Level.m_6325_(Level.java:294) ~[server-1.18.2-20220404.173914-srg.jar%23238!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:kubejs-common.mixins.json:LevelMixin,pl:mixin:APP:sereneseasons.mixins.json:MixinLevel,pl:mixin:APP:lootr.mixins.json:MixinLevel,pl:mixin:A}
	at net.minecraft.world.level.Level.m_8055_(Level.java:593) ~[server-1.18.2-20220404.173914-srg.jar%23238!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:kubejs-common.mixins.json:LevelMixin,pl:mixin:APP:sereneseasons.mixins.json:MixinLevel,pl:mixin:APP:lootr.mixins.json:MixinLevel,pl:mixin:A}
	at mcjty.lostcities.worldgen.GlobalTodo.lambda$executeAndClearTodo$3(GlobalTodo.java:127) ~[lostcities-1.18-5.3.13.jar%23158!/:1.18-5.3.13] {re:classloading}
	at java.util.HashMap.forEach(HashMap.java:1421) ~[?:?] {re:mixin,re:mixin,re:mixin,re:mixin,re:mixin,re:mixin,re:mixin,re:mixin,re:mixin,re:mixin,re:mixin,re:mixin,re:mixin}
	at mcjty.lostcities.worldgen.GlobalTodo.executeAndClearTodo(GlobalTodo.java:124) ~[lostcities-1.18-5.3.13.jar%23158!/:1.18-5.3.13] {re:classloading}
	at mcjty.lostcities.setup.ForgeEventHandlers.onWorldTick(ForgeEventHandlers.java:107) ~[lostcities-1.18-5.3.13.jar%23158!/:1.18-5.3.13] {re:classloading}
	at net.minecraftforge.eventbus.ASMEventHandler_1427_ForgeEventHandlers_onWorldTick_WorldTickEvent.invoke(.dynamic) ~[?:?] {}
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85) ~[eventbus-5.0.3.jar%232!/:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-5.0.3.jar%232!/:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-5.0.3.jar%232!/:?] {}
	at net.minecraftforge.event.ForgeEventFactory.onPostWorldTick(ForgeEventFactory.java:907) ~[forge-1.18.2-40.2.0-universal.jar%23243!/:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:1074) ~[server-1.18.2-20220404.173914-srg.jar%23238!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:kubejs-common.mixins.json:MinecraftServerMixin,pl:mixin:APP:kubejs-common.mixins.json:inject_resources.MinecraftServerMixin,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:APP:chunkpregen.mixins.json:common.server.MinecraftServerMixin,pl:mixin:APP:crafttweaker.mixins.json:common.access.server.AccessMinecraftServer,pl:mixin:APP:byg.mixins.json:access.MinecraftServerAccess,pl:mixin:APP:byg.mixins.json:server.MixinMinecraftServer,pl:mixin:A,re:mixin,pl:accesstransformer:B}
	at net.minecraft.server.dedicated.DedicatedServer.m_5703_(DedicatedServer.java:407) ~[server-1.18.2-20220404.173914-srg.jar%23238!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:chunkpregen.mixins.json:common.server.DedicatedServerMixin,pl:mixin:APP:blueprint.mixins.json:DedicatedServerMixin,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_5705_(MinecraftServer.java:977) ~[server-1.18.2-20220404.173914-srg.jar%23238!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:kubejs-common.mixins.json:MinecraftServerMixin,pl:mixin:APP:kubejs-common.mixins.json:inject_resources.MinecraftServerMixin,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:APP:chunkpregen.mixins.json:common.server.MinecraftServerMixin,pl:mixin:APP:crafttweaker.mixins.json:common.access.server.AccessMinecraftServer,pl:mixin:APP:byg.mixins.json:access.MinecraftServerAccess,pl:mixin:APP:byg.mixins.json:server.MixinMinecraftServer,pl:mixin:A,re:mixin,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:795) ~[server-1.18.2-20220404.173914-srg.jar%23238!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:kubejs-common.mixins.json:MinecraftServerMixin,pl:mixin:APP:kubejs-common.mixins.json:inject_resources.MinecraftServerMixin,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:APP:chunkpregen.mixins.json:common.server.MinecraftServerMixin,pl:mixin:APP:crafttweaker.mixins.json:common.access.server.AccessMinecraftServer,pl:mixin:APP:byg.mixins.json:access.MinecraftServerAccess,pl:mixin:APP:byg.mixins.json:server.MixinMinecraftServer,pl:mixin:A,re:mixin,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.m_177918_(MinecraftServer.java:253) ~[server-1.18.2-20220404.173914-srg.jar%23238!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:kubejs-common.mixins.json:MinecraftServerMixin,pl:mixin:APP:kubejs-common.mixins.json:inject_resources.MinecraftServerMixin,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:APP:chunkpregen.mixins.json:common.server.MinecraftServerMixin,pl:mixin:APP:crafttweaker.mixins.json:common.access.server.AccessMinecraftServer,pl:mixin:APP:byg.mixins.json:access.MinecraftServerAccess,pl:mixin:APP:byg.mixins.json:server.MixinMinecraftServer,pl:mixin:A,re:mixin,pl:accesstransformer:B}
	at java.lang.Thread.run(Thread.java:833) [?:?] {re:mixin,re:mixin,re:mixin,re:mixin,re:mixin,re:mixin,re:mixin,re:mixin,re:mixin,re:mixin,re:mixin,re:mixin,re:mixin}

```

**Comment by McJty** [comment]
First version
Secondly, did you also report this to ChunkPregenerator?

**Comment by UrbanSide** [comment]
> First version Secondly, did you also report this to ChunkPregenerator?

Version last (lostcities-1.18-5.3.13.jar) from CurseForge,Yes i send report to ChunkPregen too
