### ISSUE TITLE
encountered an error during the common_setup event phase

### ISSUE THREAD

**Issue by Haan789** [McJty/LostCities#587]
---- Minecraft Crash Report ----
// Uh... Did I do that?

Time: 21/10/23 08:01 PM
Description: Mod loading error has occurred

java.lang.Exception: Mod Loading has failed
	at net.minecraftforge.fml.CrashReportExtender.dumpModLoadingCrashReport(CrashReportExtender.java:85) [?:?] {re:classloading}
	at net.minecraftforge.fml.client.ClientModLoader.completeModLoading(ClientModLoader.java:188) [?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.lambda$null$1(Minecraft.java:508) [?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:tac.mixins.json:client.MinecraftStaticMixin,pl:mixin:APP:flywheel.mixins.json:ShaderCloseMixin,pl:mixin:APP:create.mixins.json:WindowResizeMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft$$Lambda$8717/1806207559.run(Unknown Source) [?:?] {}
	at net.minecraft.util.Util.func_215077_a(Util.java:320) [?:?] {re:classloading}
	at net.minecraft.client.Minecraft.lambda$new$2(Minecraft.java:504) [?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:tac.mixins.json:client.MinecraftStaticMixin,pl:mixin:APP:flywheel.mixins.json:ShaderCloseMixin,pl:mixin:APP:create.mixins.json:WindowResizeMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft$$Lambda$7274/1411069821.accept(Unknown Source) [?:?] {}
	at net.minecraft.client.gui.ResourceLoadProgressGui.func_230430_a_(ResourceLoadProgressGui.java:113) [?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.GameRenderer.func_195458_a(GameRenderer.java:481) [?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:tac.mixins.json:client.GameRendererMixin,pl:mixin:APP:flywheel.mixins.json:StoreProjectionMatrixMixin,pl:mixin:APP:tombstone.mixins.json:GameRendererMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:977) [?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:tac.mixins.json:client.MinecraftStaticMixin,pl:mixin:APP:flywheel.mixins.json:ShaderCloseMixin,pl:mixin:APP:create.mixins.json:WindowResizeMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:607) [?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:tac.mixins.json:client.MinecraftStaticMixin,pl:mixin:APP:flywheel.mixins.json:ShaderCloseMixin,pl:mixin:APP:create.mixins.json:WindowResizeMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:184) [?:?] {re:classloading,pl:runtimedistcleaner:A}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51] {}
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51) [forge-1.16.5-36.2.34.jar:36.2] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$475/887230059.call(Unknown Source) [forge-1.16.5-36.2.34.jar:36.2] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-8.1.3.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-8.1.3.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-8.1.3.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82) [modlauncher-8.1.3.jar:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) [modlauncher-8.1.3.jar:?] {}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at com.google.gson.JsonElement.getAsJsonObject(JsonElement.java:90) ~[gson-2.8.0.jar:?] {}
-- MOD lostcities --
Details:
	Mod File: lostcities-1.16-4.0.7-beta.jar
	Failure message: LostCities (lostcities) encountered an error during the common_setup event phase
		java.lang.IllegalStateException: Not a JSON Object: true
	Mod Version: 1.16-4.0.7-beta
	Mod Issue URL: http://github.com/McJtyMods/LostCities/issues
	Exception message: java.lang.IllegalStateException: Not a JSON Object: true
Stacktrace:
	at com.google.gson.JsonElement.getAsJsonObject(JsonElement.java:90) ~[gson-2.8.0.jar:?] {}
	at mcjty.lostcities.config.Configuration.fromJson(Configuration.java:135) ~[?:1.16-4.0.7-beta] {re:classloading}
	at mcjty.lostcities.config.LostCityProfile.<init>(LostCityProfile.java:225) ~[?:1.16-4.0.7-beta] {re:classloading}
	at mcjty.lostcities.config.LostCityConfiguration.readProfiles(LostCityConfiguration.java:497) ~[?:1.16-4.0.7-beta] {re:classloading}
	at mcjty.lostcities.config.LostCityConfiguration.setupProfiles(LostCityConfiguration.java:487) ~[?:1.16-4.0.7-beta] {re:classloading}
	at mcjty.lostcities.setup.ModSetup.init(ModSetup.java:35) ~[?:1.16-4.0.7-beta] {re:classloading}
	at mcjty.lostcities.LostCities$$Lambda$3418/56305859.accept(Unknown Source) ~[?:?] {}
	at net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:247) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:239) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.eventbus.EventBus$$Lambda$2953/718057154.invoke(Unknown Source) ~[?:?] {}
	at net.minecraftforge.eventbus.EventBus$$Lambda$3203/720693900.invoke(Unknown Source) ~[?:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.acceptEvent(FMLModContainer.java:120) ~[?:36.2] {re:classloading}
	at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$4(ModContainer.java:121) ~[?:?] {re:classloading}
	at net.minecraftforge.fml.ModContainer$$Lambda$3164/1643345873.run(Unknown Source) ~[?:?] {}
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1618) ~[?:1.8.0_51] {}
	at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1610) ~[?:1.8.0_51] {}
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289) ~[?:1.8.0_51] {}
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056) ~[?:1.8.0_51] {}
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1689) ~[?:1.8.0_51] {}
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157) ~[?:1.8.0_51] {}

-- System Details --
Details:
	Minecraft Version: 1.16.5
	Minecraft Version ID: 1.16.5
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 936049632 bytes (892 MB) / 1845493760 bytes (1760 MB) up to 2147483648 bytes (2048 MB)
	CPUs: 8
	JVM Flags: 10 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -XX:+IgnoreUnrecognizedVMOptions -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	ModLauncher: 8.1.3+8.1.3+main-8.1.x.c94d18ec
	ModLauncher launch target: fmlclient
	ModLauncher naming: srg
	ModLauncher services: 
		/mixin-0.8.4.jar mixin PLUGINSERVICE 
		/eventbus-4.0.0.jar eventbus PLUGINSERVICE 
		/forge-1.16.5-36.2.34.jar object_holder_definalize PLUGINSERVICE 
		/forge-1.16.5-36.2.34.jar runtime_enum_extender PLUGINSERVICE 
		/accesstransformers-3.0.1.jar accesstransformer PLUGINSERVICE 
		/forge-1.16.5-36.2.34.jar capability_inject_definalize PLUGINSERVICE 
		/forge-1.16.5-36.2.34.jar runtimedistcleaner PLUGINSERVICE 
		/mixin-0.8.4.jar mixin TRANSFORMATIONSERVICE 
		/forge-1.16.5-36.2.34.jar fml TRANSFORMATIONSERVICE 
	FML: 36.2
	Forge: net.minecraftforge:36.2.34
	FML Language Providers: 
		javafml@36.2
		minecraft@1
	Mod List: 
		forge-1.16.5-36.2.34-client.jar                   |Minecraft                     |minecraft                     |1.16.5              |SIDED_SETU|Manifest: NOSIGNATURE
		Zombie+Extreme+1.16.5+1.8.2.jar                   |Zombie Extreme                |zombie_extreme                |1.8.2               |SIDED_SETU|Manifest: NOSIGNATURE
		TenshiLib-1.16.3-1.3.0.jar                        |TenshiLib                     |tenshilib                     |1.16.3-1.3.0        |SIDED_SETU|Manifest: NOSIGNATURE
		morevillagers-FORGE-1.16.5-1.5.5.jar              |More Villagers                |morevillagers                 |1.5.5               |SIDED_SETU|Manifest: NOSIGNATURE
		Treasure2-mc1.16.5-f36.2.34-v2.5.0.jar            |Treasure2                     |treasure2                     |2.5.0               |SIDED_SETU|Manifest: NOSIGNATURE
		jei-1.16.5-7.7.1.153.jar                          |Just Enough Items             |jei                           |7.7.1.153           |SIDED_SETU|Manifest: NOSIGNATURE
		Horror+Elements+mod+1.16.5_Halloween_update.jar   |Horror elements mod           |horror_elements_mod           |1.0.0               |SIDED_SETU|Manifest: NOSIGNATURE
		tac-0.3.8.1-1.16.5.jar                            |Timeless and Classics Guns    |tac                           |0.3.8.1             |SIDED_SETU|Manifest: NOSIGNATURE
		flywheel-1.16-0.2.3 (1).jar                       |Flywheel                      |flywheel                      |1.16-0.2.3          |SIDED_SETU|Manifest: NOSIGNATURE
		curios-forge-1.16.5-4.0.8.1.jar                   |Curios API                    |curios                        |1.16.5-4.0.8.1      |SIDED_SETU|Manifest: NOSIGNATURE
		create-mc1.16.5_v0.3.2g (1).jar                   |Create                        |create                        |v0.3.2g             |SIDED_SETU|Manifest: NOSIGNATURE
		RingOfRepair-Forge-1.16.5-1.2.15.jar              |Ring of Repair                |ring_of_repair                |1.2.15              |SIDED_SETU|Manifest: NOSIGNATURE
		journeymap-1.16.5-5.8.5p6.jar                     |Journeymap                    |journeymap                    |5.8.5p6             |SIDED_SETU|Manifest: NOSIGNATURE
		corail_recycler-1.16.5-5.2.0.jar                  |Corail Recycler               |corail_recycler               |5.2.0               |SIDED_SETU|Manifest: NOSIGNATURE
		lostcities-1.16-4.0.7-beta.jar                    |LostCities                    |lostcities                    |1.16-4.0.7-beta     |ERROR     |Manifest: NOSIGNATURE
		tombstone-6.8.12-1.16.5.jar                       |Corail Tombstone              |tombstone                     |6.8.12              |SIDED_SETU|Manifest: NOSIGNATURE
		obfuscate-0.6.3-1.16.5.jar                        |Obfuscate                     |obfuscate                     |0.6.3               |SIDED_SETU|Manifest: NOSIGNATURE
		GottschCore-mc1.16.5-f36.2.34-v1.8.0.jar          |GottschCore                   |gottschcore                   |1.8.0               |SIDED_SETU|Manifest: NOSIGNATURE
		forge-branders-spawnermod-1.16.5-1.8.14.jar       |Enhanced Mob Spawners         |spawnermod                    |1.8.14              |SIDED_SETU|Manifest: NOSIGNATURE
		BadMobs-1.16.5-9.1.9.jar                          |BadMobs                       |badmobs                       |9.1.9               |SIDED_SETU|Manifest: eb:c4:b1:67:8b:f9:0c:db:dc:4f:01:b1:8e:61:64:39:4c:10:85:0b:a6:c4:c7:48:f0:fa:95:f2:cb:08:3a:e5
		CustomNPCs-1.16.5.20220515.jar                    |Custom NPCs                   |customnpcs                    |1.16.5.20220515     |SIDED_SETU|Manifest: NOSIGNATURE
		sophisticatedbackpacks-1.16.5-3.15.20.755.jar     |Sophisticated Backpacks       |sophisticatedbackpacks        |1.16.5-3.15.20.755  |SIDED_SETU|Manifest: NOSIGNATURE
		relics-1.16.5-0.3.4.4.jar                         |Relics                        |relics                        |0.3.4.4             |SIDED_SETU|Manifest: NOSIGNATURE
		WegotRunners0.3a.jar                              |wegotrunnners                 |wegotrunnners                 |1.0.0               |SIDED_SETU|Manifest: NOSIGNATURE
		getinthebucketmod-1.16.5-3.0.7.jar                |Get In The Bucket Mod         |getinthebucketmod             |3.0.7               |SIDED_SETU|Manifest: NOSIGNATURE
		forge-1.16.5-36.2.34-universal.jar                |Forge                         |forge                         |36.2.34             |SIDED_SETU|Manifest: 22:af:21:d8:19:82:7f:93:94:fe:2b:ac:b7:e4:41:57:68:39:87:b1:a7:5c:c6:44:f9:25:74:21:14:f5:0d:90
		improvedmobs-1.16.5-1.10.13.jar                   |Improved Mobs Mod             |improvedmobs                  |1.16.5-1.10.13      |SIDED_SETU|Manifest: NOSIGNATURE
		geckolib-forge-1.16.5-3.0.106.jar                 |GeckoLib                      |geckolib3                     |3.0.106             |SIDED_SETU|Manifest: NOSIGNATURE
	Crash Report UUID: db8b2373-2746-4155-8630-8f20140c5952

**Comment by McJty** [comment]
Remove the lost cities config file

**Comment by Haan789** [comment]
ty

**Comment by Haan789** [comment]
The above did not help, I went to the mcjty/lostcities/config folder and deleted the config folder but it gave me another error about the latter

**Comment by McJty** [comment]
What error?
