### ISSUE TITLE
LostCities (lostcities) encountered an error during the common_setup event phase  java.lang.IllegalStateException: Not a JSON Object: true

### ISSUE THREAD

**Issue by zMixg** [McJty/LostCities#602]
i dont know what happend idk if is for the mods or another issue.
help D:

**Comment by McJty** [comment]
The thing that happened is that you didn't give enough information (version, logs, ...)

**Comment by zMixg** [comment]
Im sorry thats is the log and the version is 1.16.5

---- Minecraft Crash Report ----
// Surprise! Haha. Well, this is awkward.

Time: 20/01/24 02:35 AM
Description: Mod loading error has occurred

java.lang.Exception: Mod Loading has failed
	at net.minecraftforge.fml.CrashReportExtender.dumpModLoadingCrashReport(CrashReportExtender.java:71) [?:?] {re:classloading}
	at net.minecraftforge.fml.client.ClientModLoader.completeModLoading(ClientModLoader.java:174) [?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.lambda$null$1(Minecraft.java:508) [?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:charm.mixins.json:accessor.MinecraftAccessor,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft$$Lambda$4913/1977035133.run(Unknown Source) [?:?] {}
	at net.minecraft.util.Util.func_215077_a(Util.java:320) [?:?] {re:classloading}
	at net.minecraft.client.Minecraft.lambda$new$2(Minecraft.java:504) [?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:charm.mixins.json:accessor.MinecraftAccessor,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft$$Lambda$4409/1354439711.accept(Unknown Source) [?:?] {}
	at net.minecraft.client.gui.ResourceLoadProgressGui.func_230430_a_(ResourceLoadProgressGui.java:113) [?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.GameRenderer.func_195458_a(GameRenderer.java:481) [?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:cgm.mixins.json:client.GameRendererMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:977) [?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:charm.mixins.json:accessor.MinecraftAccessor,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:607) [?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:charm.mixins.json:accessor.MinecraftAccessor,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:184) [?:?] {re:classloading,pl:runtimedistcleaner:A}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51] {}
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:37) [forge-1.16.5-36.2.41.jar:36.2] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$463/1847301137.call(Unknown Source) [forge-1.16.5-36.2.41.jar:36.2] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-8.1.3.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-8.1.3.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-8.1.3.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82) [modlauncher-8.1.3.jar:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) [modlauncher-8.1.3.jar:?] {}


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at com.google.gson.JsonElement.getAsJsonObject(JsonElement.java:90) ~[gson-2.8.0.jar:?] {}
-- MOD lostcities --
Details:
	Mod File: lostcities-1.16-4.0.12-beta (2).jar
	Failure message: LostCities (lostcities) encountered an error during the common_setup event phase
		java.lang.IllegalStateException: Not a JSON Object: true
	Mod Version: 1.16-4.0.12-beta
	Mod Issue URL: http://github.com/McJtyMods/LostCities/issues
	Exception message: java.lang.IllegalStateException: Not a JSON Object: true
Stacktrace:
	at com.google.gson.JsonElement.getAsJsonObject(JsonElement.java:90) ~[gson-2.8.0.jar:?] {}
	at mcjty.lostcities.config.Configuration.fromJson(Configuration.java:135) ~[?:1.16-4.0.12-beta] {re:classloading}
	at mcjty.lostcities.config.LostCityProfile.<init>(LostCityProfile.java:225) ~[?:1.16-4.0.12-beta] {re:classloading}
	at mcjty.lostcities.config.LostCityConfiguration.readProfiles(LostCityConfiguration.java:468) ~[?:1.16-4.0.12-beta] {re:classloading}
	at mcjty.lostcities.config.LostCityConfiguration.setupProfiles(LostCityConfiguration.java:458) ~[?:1.16-4.0.12-beta] {re:classloading}
	at mcjty.lostcities.setup.ModSetup.init(ModSetup.java:35) ~[?:1.16-4.0.12-beta] {re:classloading}
	at mcjty.lostcities.LostCities$$Lambda$3238/1307058325.accept(Unknown Source) ~[?:?] {}
	at net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:247) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:239) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.eventbus.EventBus$$Lambda$2966/897303688.invoke(Unknown Source) ~[?:?] {}
	at net.minecraftforge.eventbus.EventBus$$Lambda$3218/774328391.invoke(Unknown Source) ~[?:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.acceptEvent(FMLModContainer.java:106) ~[?:36.2] {re:classloading}
	at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$4(ModContainer.java:107) ~[?:?] {re:classloading}
	at net.minecraftforge.fml.ModContainer$$Lambda$3155/2096827468.run(Unknown Source) ~[?:?] {}
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1618) ~[?:1.8.0_51] {}
	at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1610) ~[?:1.8.0_51] {}
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289) ~[?:1.8.0_51] {}
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056) ~[?:1.8.0_51] {}
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1689) ~[?:1.8.0_51] {}
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157) ~[?:1.8.0_51] {}


-- System Details --
Details:
	Minecraft Version: 1.16.5
	Minecraft Version ID: 1.16.5
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 2479019760 bytes (2364 MB) / 3657433088 bytes (3488 MB) up to 4294967296 bytes (4096 MB)
	CPUs: 12
	JVM Flags: 10 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -XX:+IgnoreUnrecognizedVMOptions -Xmx4G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	ModLauncher: 8.1.3+8.1.3+main-8.1.x.c94d18ec
	ModLauncher launch target: fmlclient
	ModLauncher naming: srg
	ModLauncher services: 
		/mixin-0.8.4.jar mixin PLUGINSERVICE 
		/eventbus-4.0.0.jar eventbus PLUGINSERVICE 
		/forge-1.16.5-36.2.41.jar object_holder_definalize PLUGINSERVICE 
		/forge-1.16.5-36.2.41.jar runtime_enum_extender PLUGINSERVICE 
		/accesstransformers-3.0.1.jar accesstransformer PLUGINSERVICE 
		/forge-1.16.5-36.2.41.jar capability_inject_definalize PLUGINSERVICE 
		/forge-1.16.5-36.2.41.jar runtimedistcleaner PLUGINSERVICE 
		/mixin-0.8.4.jar mixin TRANSFORMATIONSERVICE 
		/forge-1.16.5-36.2.41.jar fml TRANSFORMATIONSERVICE 
	FML: 36.2
	Forge: net.minecraftforge:36.2.41
	FML Language Providers: 
		javafml@36.2
		minecraft@1
	Mod List: 
		forge-1.16.5-36.2.41-client.jar                   |Minecraft                     |minecraft                     |1.16.5              |SIDED_SETU|Manifest: NOSIGNATURE
		zombieawareness-1.16.5-1.12.jar                   |Zombie Awareness              |zombieawareness               |1.16.5-1.12         |SIDED_SETU|Manifest: NOSIGNATURE
		ToughAsNails-1.16.5-4.1.0.9-universal.jar         |Tough As Nails                |toughasnails                  |1.16.5-4.0.1.8      |SIDED_SETU|Manifest: NOSIGNATURE
		lostcities-1.16-4.0.12-beta (2).jar               |LostCities                    |lostcities                    |1.16-4.0.12-beta    |ERROR     |Manifest: NOSIGNATURE
		obfuscate-0.6.3-1.16.5 (2).jar                    |Obfuscate                     |obfuscate                     |0.6.3               |SIDED_SETU|Manifest: NOSIGNATURE
		coroutil-forge-1.16.5-1.3.6.jar                   |CoroUtil                      |coroutil                      |1.16.5-1.3.6        |SIDED_SETU|Manifest: NOSIGNATURE
		cgm-1.2.5-1.16.5.jar                              |MrCrayfish's Gun Mod          |cgm                           |1.2.5               |SIDED_SETU|Manifest: NOSIGNATURE
		CreativeCore_v2.2.1_mc1.16.5 (2).jar              |CreativeCore                  |creativecore                  |2.0.0               |SIDED_SETU|Manifest: NOSIGNATURE
		jei-1.16.5-7.8.0.1009 (1).jar                     |Just Enough Items             |jei                           |7.8.0.1009          |SIDED_SETU|Manifest: NOSIGNATURE
		charm-forge-1.16.5-2.3.2.jar                      |Charm                         |charm                         |2.3.2               |SIDED_SETU|Manifest: NOSIGNATURE
		firstaid-1.9.8.jar                                |First Aid                     |firstaid                      |1.9.8               |SIDED_SETU|Manifest: NOSIGNATURE
		forge-1.16.5-36.2.41-universal.jar                |Forge                         |forge                         |36.2.41             |SIDED_SETU|Manifest: 22:af:21:d8:19:82:7f:93:94:fe:2b:ac:b7:e4:41:57:68:39:87:b1:a7:5c:c6:44:f9:25:74:21:14:f5:0d:90
		appleskin-forge-mc1.16.x-2.5.1 (1).jar            |AppleSkin                     |appleskin                     |2.5.1+mc1.16.4      |SIDED_SETU|Manifest: NOSIGNATURE
		charmonium-forge-1.16.5-2.3.2.jar                 |Charmonium                    |charmonium                    |2.3.2               |SIDED_SETU|Manifest: NOSIGNATURE
		UNDEADv.1.7.b.release+Biome.jar                   |UNDEAD                        |undead                        |2.2.2               |SIDED_SETU|Manifest: NOSIGNATURE
		Xaeros_Minimap_23.9.4_Forge_1.16.5 (1).jar        |Xaero's Minimap               |xaerominimap                  |23.9.4              |SIDED_SETU|Manifest: NOSIGNATURE
		PlayerRevive_v2.0.0-pre04_mc1.16.5.jar            |PlayerRevive                  |playerrevive                  |2.0.0               |SIDED_SETU|Manifest: NOSIGNATURE
		mobsunscreen-1.16.5-3.0.4.jar                     |Mob Sunscreen                 |mobsunscreen                  |1.16.5-3.0.4        |SIDED_SETU|Manifest: NOSIGNATURE
		EverlastingSkins-1.16.5-0.3.0.3.jar               |Everlasting Skins             |everlastingskins              |0.3.0.3             |SIDED_SETU|Manifest: NOSIGNATURE
		EnhancedVisuals_v1.3.32_mc1.16.5.jar              |EnhancedVisuals               |enhancedvisuals               |1.3.0               |SIDED_SETU|Manifest: NOSIGNATURE
	Crash Report UUID: 39178d63-1d24-4956-bafd-6d9c8b1633b9

**Comment by McJty** [comment]
You hit a known issue. Remove the lost cities config folder
