### ISSUE TITLE
error with c2me

### ISSUE THREAD

**Issue by coco875** [McJty/LostCities#649]
when I try join lostcities:lostcity the world don't appear and multiple error like this appears.
```
[22oct.2024 13:16:57.563] [c2me-worker-7/ERROR] [lostcities/]: Error generating chunk -3,-3: Accessing PalettedContainer from multiple threads
net.minecraft.ReportedException: Accessing PalettedContainer from multiple threads
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.util.ThreadingDetector.makeThreadingException(ThreadingDetector.java:88) ~[client-1.21.1-20240808.144430-srg.jar%23174!/:?]
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.util.ThreadingDetector.checkAndUnlock(ThreadingDetector.java:69) ~[client-1.21.1-20240808.144430-srg.jar%23174!/:?]
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.world.level.chunk.PalettedContainer.release(PalettedContainer.java:43) ~[client-1.21.1-20240808.144430-srg.jar%23174!/:?]
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.world.level.chunk.LevelChunkSection.release(LevelChunkSection.java:51) ~[client-1.21.1-20240808.144430-srg.jar%23174!/:?]
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.world.level.chunk.BulkSectionAccess.close(BulkSectionAccess.java:58) ~[client-1.21.1-20240808.144430-srg.jar%23174!/:?]
	at TRANSFORMER/lostcities@1.21-8.2.2/mcjty.lostcities.worldgen.ChunkDriver.actuallyGenerate(ChunkDriver.java:45) ~[lostcities-1.21-8.2.2.jar%23179!/:1.21-8.2.2]
	at TRANSFORMER/lostcities@1.21-8.2.2/mcjty.lostcities.worldgen.LostCityTerrainFeature.generate(LostCityTerrainFeature.java:352) ~[lostcities-1.21-8.2.2.jar%23179!/:1.21-8.2.2]
	at TRANSFORMER/lostcities@1.21-8.2.2/mcjty.lostcities.worldgen.LostCityFeature.place(LostCityFeature.java:62) ~[lostcities-1.21-8.2.2.jar%23179!/:1.21-8.2.2]
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.world.level.levelgen.feature.ConfiguredFeature.place(ConfiguredFeature.java:537) ~[client-1.21.1-20240808.144430-srg.jar%23174!/:?]
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.world.level.levelgen.placement.PlacedFeature.lambda$placeWithContext$4(PlacedFeature.java:54) ~[client-1.21.1-20240808.144430-srg.jar%23174!/:?]
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184) ~[?:?]
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184) ~[?:?]
	at java.base/java.util.stream.IntPipeline$1$1.accept(IntPipeline.java:180) ~[?:?]
	at java.base/java.util.stream.Streams$RangeIntSpliterator.forEachRemaining(Streams.java:104) ~[?:?]
	at java.base/java.util.Spliterator$OfInt.forEachRemaining(Spliterator.java:712) ~[?:?]
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509) ~[?:?]
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?]
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151) ~[?:?]
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174) ~[?:?]
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596) ~[?:?]
	at java.base/java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:276) ~[?:?]
	at java.base/java.util.stream.Streams$StreamBuilderImpl.forEachRemaining(Streams.java:411) ~[?:?]
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509) ~[?:?]
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?]
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151) ~[?:?]
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174) ~[?:?]
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596) ~[?:?]
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.world.level.levelgen.placement.PlacedFeature.placeWithContext(PlacedFeature.java:53) ~[client-1.21.1-20240808.144430-srg.jar%23174!/:?]
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.world.level.levelgen.placement.PlacedFeature.placeWithBiomeCheck(PlacedFeature.java:42) ~[client-1.21.1-20240808.144430-srg.jar%23174!/:?]
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.world.level.chunk.ChunkGenerator.applyBiomeDecoration(ChunkGenerator.java:396) ~[client-1.21.1-20240808.144430-srg.jar%23174!/:?]
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.world.level.chunk.status.ChunkStatusTasks.generateFeatures(ChunkStatusTasks.java:154) ~[client-1.21.1-20240808.144430-srg.jar%23174!/:?]
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.world.level.chunk.status.ChunkStep.mixinextras$bridge$doWork$14(ChunkStep.java) ~[client-1.21.1-20240808.144430-srg.jar%23174!/:?]
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.world.level.chunk.status.ChunkStep.wrapOperation$zgk000$c2me_opts_chunk_access$runGenerationTask(ChunkStep.java:526) ~[client-1.21.1-20240808.144430-srg.jar%23174!/:?]
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.world.level.chunk.status.ChunkStep.apply(ChunkStep.java:33) ~[client-1.21.1-20240808.144430-srg.jar%23174!/:?]
	at TRANSFORMER/c2me_rewrites_chunk_system@0.3.0alpha.0.2921.21.1/com.ishland.c2me.rewrites.chunksystem.common.statuses.VanillaWorldGenerationDelegate.lambda$upgradeToThis$8(VanillaWorldGenerationDelegate.java:123) ~[c2me-fabric-mc1.21.1-0.3.0+alpha.0.292$c2me-rewrites-chunk-system-mc1.21.1-0.3.0+alpha.0.292_mapped_moj_1.21.1.jar%23370!/:?]
	at TRANSFORMER/c2me_base@0.3.0alpha.0.2921.21.1/com.ishland.c2me.base.common.scheduler.ScheduledTask.run(ScheduledTask.java:22) [c2me-fabric-mc1.21.1-0.3.0+alpha.0.292$c2me-base-mc1.21.1-0.3.0+alpha.0.292-all_mapped_moj_1.21.1.jar%23354!/:?]
	at TRANSFORMER/c2me_base@0.3.0alpha.0.2921.21.1/com.ishland.flowsched.executor.WorkerThread.pollTasks(WorkerThread.java:57) [c2me-fabric-mc1.21.1-0.3.0+alpha.0.292$c2me-base-mc1.21.1-0.3.0+alpha.0.292-all_mapped_moj_1.21.1.jar%23354!/:?]
	at TRANSFORMER/c2me_base@0.3.0alpha.0.2921.21.1/com.ishland.flowsched.executor.WorkerThread.run(WorkerThread.java:27) [c2me-fabric-mc1.21.1-0.3.0+alpha.0.292$c2me-base-mc1.21.1-0.3.0+alpha.0.292-all_mapped_moj_1.21.1.jar%23354!/:?]
Caused by: java.lang.IllegalStateException: Accessing PalettedContainer from multiple threads
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.util.ThreadingDetector.makeThreadingException(ThreadingDetector.java:84) ~[client-1.21.1-20240808.144430-srg.jar%23174!/:?]
	... 39 more
```

**Comment by McJty** [comment]
What is c2me?

**Comment by coco875** [comment]
A fabric mod (in this case load by connector) "mod designed to improve the performance of chunk generation, I/O, and loading. This is done by taking advantage of multiple CPU cores in parallel."

**Comment by McJty** [comment]
And does Lost Cities work fine without this mod? If so then that's not a problem of Lost Cities

**Comment by coco875** [comment]
yes it work fine without this mod

**Comment by coco875** [comment]
after talking with ishland (the dev of c2me) it the support should be on your end for him
![image](https://github.com/user-attachments/assets/ed35b8a9-440a-45fb-b16d-c895bb805df4)

**Comment by McJty** [comment]
Sorry but my mod works fine on Vanilla. If they do things that cause my mod to break then it's on THEM to fix that. Not me. At the very least they should tell me what I'm doing wrong instead of just telling me that I need to fix my mod. I don't even know how or what is wrong
