### ISSUE TITLE
Error generating chunk minecraft 1.20.1 Forge

### ISSUE THREAD

**Issue by HEROBRONERM** [McJty/LostCities#658]
Version: Minecraft: 1.20.1, Forge: 47.2.0
modpack used: Cursed Walking - A Modern Zombie Apocalypse +added LostCities Mod
ErrorLog:
[19:18:24] [Worker-Main-11/ERROR]: Error generating chunk -6,-14: Cannot invoke "net.minecraft.world.level.block.state.BlockState.m_60734_()" because "state" is null
java.lang.NullPointerException: Cannot invoke "net.minecraft.world.level.block.state.BlockState.m_60734_()" because "state" is null
	at mcjty.lostcities.worldgen.ChunkDriver.correct(ChunkDriver.java:281) ~[lostcities-1.20-7.1.8.jar%23355!/:1.20-7.1.8]
	at mcjty.lostcities.worldgen.ChunkDriver.add(ChunkDriver.java:322) ~[lostcities-1.20-7.1.8.jar%23355!/:1.20-7.1.8]
	at mcjty.lostcities.worldgen.LostCityTerrainFeature.actuallyGenerateStuff(LostCityTerrainFeature.java:1604) ~[lostcities-1.20-7.1.8.jar%23355!/:1.20-7.1.8]
	at mcjty.lostcities.worldgen.LostCityTerrainFeature.generateStuff(LostCityTerrainFeature.java:1546) ~[lostcities-1.20-7.1.8.jar%23355!/:1.20-7.1.8]
	at mcjty.lostcities.worldgen.LostCityTerrainFeature.doCityChunk(LostCityTerrainFeature.java:1529) ~[lostcities-1.20-7.1.8.jar%23355!/:1.20-7.1.8]
	at mcjty.lostcities.worldgen.LostCityTerrainFeature.generate(LostCityTerrainFeature.java:304) ~[lostcities-1.20-7.1.8.jar%23355!/:1.20-7.1.8]
	at mcjty.lostcities.worldgen.LostCityFeature.m_142674_(LostCityFeature.java:62) ~[lostcities-1.20-7.1.8.jar%23355!/:1.20-7.1.8]
	at net.minecraft.world.level.levelgen.feature.Feature.m_225028_(Feature.java:155) ~[client-1.20.1-20230612.114412-srg.jar%23414!/:?]
	at net.minecraft.world.level.levelgen.feature.ConfiguredFeature.m_224953_(ConfiguredFeature.java:28) ~[client-1.20.1-20230612.114412-srg.jar%23414!/:?]
	at net.minecraft.world.level.levelgen.placement.PlacedFeature.m_226362_(PlacedFeature.java:54) ~[client-1.20.1-20230612.114412-srg.jar%23414!/:?]
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183) ~[?:?]
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183) ~[?:?]
	at java.util.stream.IntPipeline$1$1.accept(IntPipeline.java:180) ~[?:?]
	at java.util.stream.Streams$RangeIntSpliterator.forEachRemaining(Streams.java:104) ~[?:?]
	at java.util.Spliterator$OfInt.forEachRemaining(Spliterator.java:711) ~[?:?]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509) ~[?:?]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?]
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150) ~[?:?]
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173) ~[?:?]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596) ~[?:?]
	at java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:276) ~[?:?]
	at java.util.stream.Streams$StreamBuilderImpl.forEachRemaining(Streams.java:411) ~[?:?]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509) ~[?:?]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?]
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150) ~[?:?]
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173) ~[?:?]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596) ~[?:?]
	at net.minecraft.world.level.levelgen.placement.PlacedFeature.m_226368_(PlacedFeature.java:53) ~[client-1.20.1-20230612.114412-srg.jar%23414!/:?]
	at net.minecraft.world.level.levelgen.placement.PlacedFeature.m_226377_(PlacedFeature.java:42) ~[client-1.20.1-20230612.114412-srg.jar%23414!/:?]
	at net.minecraft.world.level.chunk.ChunkGenerator.m_213609_(ChunkGenerator.java:357) ~[client-1.20.1-20230612.114412-srg.jar%23414!/:?]
	at net.minecraft.world.level.chunk.ChunkStatus.m_279978_(ChunkStatus.java:108) ~[client-1.20.1-20230612.114412-srg.jar%23414!/:?]
	at net.minecraft.world.level.chunk.ChunkStatus$SimpleGenerationTask.m_214024_(ChunkStatus.java:309) ~[client-1.20.1-20230612.114412-srg.jar%23414!/:?]
	at net.minecraft.world.level.chunk.ChunkStatus.m_280308_(ChunkStatus.java:252) ~[client-1.20.1-20230612.114412-srg.jar%23414!/:?]
	at net.minecraft.server.level.ChunkMap.lambda$scheduleChunkGeneration$27(ChunkMap.java:643) ~[client-1.20.1-20230612.114412-srg.jar%23414!/:?]
	at com.mojang.datafixers.util.Either$Left.map(Either.java:38) ~[datafixerupper-6.0.8.jar%23114!/:?]
	at net.minecraft.server.level.ChunkMap.lambda$scheduleChunkGeneration$29(ChunkMap.java:634) ~[client-1.20.1-20230612.114412-srg.jar%23414!/:?]
	at java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1150) ~[?:?]
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482) ~[?:?]
	at net.minecraft.server.level.ChunkTaskPriorityQueueSorter.m_143188_(ChunkTaskPriorityQueueSorter.java:62) ~[client-1.20.1-20230612.114412-srg.jar%23414!/:?]
	at net.minecraft.util.thread.ProcessorMailbox.m_18759_(ProcessorMailbox.java:91) ~[client-1.20.1-20230612.114412-srg.jar%23414!/:?]
	at net.minecraft.util.thread.ProcessorMailbox.m_18747_(ProcessorMailbox.java:146) ~[client-1.20.1-20230612.114412-srg.jar%23414!/:?]
	at net.minecraft.util.thread.ProcessorMailbox.run(ProcessorMailbox.java:102) ~[client-1.20.1-20230612.114412-srg.jar%23414!/:?]
	at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1395) ~[?:?]
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?]
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?]
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?]
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?]
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?]
	
In game picture: 
![image](https://github.com/user-attachments/assets/866b387e-f945-47a4-b080-07a6ab318d14)

maybe it's compatibility issue with other world generation mods, it would be helpful to find out with which and add some sort of compatibility.

**Comment by McJty** [comment]
Did you add one of the Lost City addons? Or is Lost Cities itself the only Lost Cities thing? Can I see the entire latest.log?

**Comment by HEROBRONERM** [comment]
> Did you add one of the Lost City addons? Or is Lost Cities itself the only Lost Cities thing? Can I see the entire latest.log?

i installed Keerdm's Zombie apocalypse essentials

Here the latest log where the error in the issue poped up.
[2024-11-27-5.log.gz](https://github.com/user-attachments/files/17938345/2024-11-27-5.log.gz)

**Comment by HEROBRONERM** [comment]
[2024-11-27-5.log.gz](https://github.com/user-attachments/files/17938339/2024-11-27-5.log.gz)

**Comment by HEROBRONERM** [comment]
i deleted it and now mod is working correctly 😅.... That was awkward.

**Comment by Keerdm** [comment]
> > Did you add one of the Lost City addons? Or is Lost Cities itself the only Lost Cities thing? Can I see the entire latest.log?
> 
> i installed Keerdm's Zombie apocalypse essentials
> 
> Here the latest log where the error in the issue poped up. [2024-11-27-5.log.gz](https://github.com/user-attachments/files/17938345/2024-11-27-5.log.gz)

That's a common issue. You just need to select the world style "keerdm_zombie_essentials:testworld" when customizing the lost cities, and it will work.
