### ISSUE TITLE
Error generating chunk: Invalid name given to minecraft:root getOrThrow!

### ISSUE THREAD

**Issue by BenjiLangQc** [McJty/LostCities#662]
Hey, I don't know if its an incompatibility with some of my mods, but I started to have some generation errors with the mod.

here's an image of the one of the missing chunks:
![2024-12-18_10 51 29](https://github.com/user-attachments/assets/3b47d396-c2a1-45c7-8b8f-4a000a3b6f87)

here's the log:
[2024-12-18-2.log.gz](https://github.com/user-attachments/files/18185606/2024-12-18-2.log.gz)

here's one of the errors in the log:
[10:36:32] [Worker-Main-8/ERROR]: Error generating chunk 15,125: Invalid name given to minecraft:root getOrThrow!
java.lang.RuntimeException: Invalid name given to minecraft:root getOrThrow!
	at mcjty.lostcities.worldgen.lost.cityassets.RegistryAssetRegistry.getOrThrow(RegistryAssetRegistry.java:43) ~[lostcities-1.20-7.3.5.jar%23388!/:1.20-7.3.5]
	at mcjty.lostcities.worldgen.lost.BuildingInfo.<init>(BuildingInfo.java:759) ~[lostcities-1.20-7.3.5.jar%23388!/:1.20-7.3.5]
	at mcjty.lostcities.worldgen.lost.BuildingInfo.getBuildingInfo(BuildingInfo.java:600) ~[lostcities-1.20-7.3.5.jar%23388!/:1.20-7.3.5]
	at mcjty.lostcities.worldgen.lost.BuildingInfo.getZmax(BuildingInfo.java:237) ~[lostcities-1.20-7.3.5.jar%23388!/:1.20-7.3.5]
	at mcjty.lostcities.worldgen.lost.BuildingInfo.getDesiredMaxHeightL1(BuildingInfo.java:1598) ~[lostcities-1.20-7.3.5.jar%23388!/:1.20-7.3.5]
	at mcjty.lostcities.worldgen.lost.BuildingInfo.updateMinMaxL2(BuildingInfo.java:1667) ~[lostcities-1.20-7.3.5.jar%23388!/:1.20-7.3.5]
	at mcjty.lostcities.worldgen.lost.BuildingInfo.getDesiredMaxHeightL2(BuildingInfo.java:1653) ~[lostcities-1.20-7.3.5.jar%23388!/:1.20-7.3.5]
	at mcjty.lostcities.worldgen.LostCityTerrainFeature.correctTerrainShape(LostCityTerrainFeature.java:631) ~[lostcities-1.20-7.3.5.jar%23388!/:1.20-7.3.5]
	at mcjty.lostcities.worldgen.LostCityTerrainFeature.doNormalChunk(LostCityTerrainFeature.java:458) ~[lostcities-1.20-7.3.5.jar%23388!/:1.20-7.3.5]
	at mcjty.lostcities.worldgen.LostCityTerrainFeature.generate(LostCityTerrainFeature.java:300) ~[lostcities-1.20-7.3.5.jar%23388!/:1.20-7.3.5]
	at mcjty.lostcities.worldgen.LostCityFeature.m_142674_(LostCityFeature.java:62) ~[lostcities-1.20-7.3.5.jar%23388!/:1.20-7.3.5]
	at net.minecraft.world.level.levelgen.feature.Feature.m_225028_(Feature.java:155) ~[client-1.20.1-20230612.114412-srg.jar%23454!/:?]
	at net.minecraft.world.level.levelgen.feature.ConfiguredFeature.m_224953_(ConfiguredFeature.java:28) ~[client-1.20.1-20230612.114412-srg.jar%23454!/:?]
	at net.minecraft.world.level.levelgen.placement.PlacedFeature.m_226362_(PlacedFeature.java:54) ~[client-1.20.1-20230612.114412-srg.jar%23454!/:?]
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183) ~[?:?]
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183) ~[?:?]
	at java.util.stream.IntPipeline$1$1.accept(IntPipeline.java:180) ~[?:?]
	at java.util.stream.Streams$RangeIntSpliterator.forEachRemaining(Streams.java:104) ~[?:?]
	at java.util.Spliterator$OfInt.forEachRemaining(Spliterator.java:711) ~[?:?]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509) ~[?:?]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?]
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150) ~[?:?]
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173) ~[?:?]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596) ~[?:?]
	at java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:276) ~[?:?]
	at java.util.stream.Streams$StreamBuilderImpl.forEachRemaining(Streams.java:411) ~[?:?]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509) ~[?:?]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?]
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150) ~[?:?]
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173) ~[?:?]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596) ~[?:?]
	at net.minecraft.world.level.levelgen.placement.PlacedFeature.m_226368_(PlacedFeature.java:53) ~[client-1.20.1-20230612.114412-srg.jar%23454!/:?]
	at net.minecraft.world.level.levelgen.placement.PlacedFeature.m_226377_(PlacedFeature.java:42) ~[client-1.20.1-20230612.114412-srg.jar%23454!/:?]
	at net.minecraft.world.level.chunk.ChunkGenerator.m_213609_(ChunkGenerator.java:357) ~[client-1.20.1-20230612.114412-srg.jar%23454!/:?]
	at net.minecraft.world.level.chunk.ChunkStatus.m_279978_(ChunkStatus.java:108) ~[client-1.20.1-20230612.114412-srg.jar%23454!/:?]
	at net.minecraft.world.level.chunk.ChunkStatus$SimpleGenerationTask.m_214024_(ChunkStatus.java:309) ~[client-1.20.1-20230612.114412-srg.jar%23454!/:?]
	at net.minecraft.world.level.chunk.ChunkStatus.m_280308_(ChunkStatus.java:252) ~[client-1.20.1-20230612.114412-srg.jar%23454!/:?]
	at net.minecraft.server.level.ChunkMap.lambda$scheduleChunkGeneration$27(ChunkMap.java:643) ~[client-1.20.1-20230612.114412-srg.jar%23454!/:?]
	at com.mojang.datafixers.util.Either$Left.map(Either.java:38) ~[datafixerupper-6.0.8.jar%23114!/:?]
	at net.minecraft.server.level.ChunkMap.lambda$scheduleChunkGeneration$29(ChunkMap.java:634) ~[client-1.20.1-20230612.114412-srg.jar%23454!/:?]
	at java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1150) ~[?:?]
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482) ~[?:?]
	at net.minecraft.server.level.ChunkTaskPriorityQueueSorter.m_143188_(ChunkTaskPriorityQueueSorter.java:62) ~[client-1.20.1-20230612.114412-srg.jar%23454!/:?]
	at net.minecraft.util.thread.ProcessorMailbox.m_18759_(ProcessorMailbox.java:91) ~[client-1.20.1-20230612.114412-srg.jar%23454!/:?]
	at net.minecraft.util.thread.ProcessorMailbox.m_18747_(ProcessorMailbox.java:146) ~[client-1.20.1-20230612.114412-srg.jar%23454!/:?]
	at net.minecraft.util.thread.ProcessorMailbox.run(ProcessorMailbox.java:102) ~[client-1.20.1-20230612.114412-srg.jar%23454!/:?]
	at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1395) ~[?:?]
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?]
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?]
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?]
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?]
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?]

if I forgot to send something, let me know!

**Comment by BenjiLangQc** [comment]
Ok so I think disabling Redirector fixed the issue, need more testing though. 

If its the case, you might want to add an incompatibility list on the mod page and add that mod to it.
