### ISSUE TITLE
Crashing when generating single biome world

### ISSUE THREAD

**Issue by el-vana** [McJty/LostCities#663]
---- Minecraft Crash Report ----
// I bet Cylons wouldn't have this problem.

Time: 19/12/24 23:23
Description: Exception in server tick loop

java.lang.NoSuchMethodError: 'void net.minecraft.server.level.DistanceManager.addRegionTicket(net.minecraft.server.level.TicketType, net.minecraft.world.level.ChunkPos, int, java.lang.Object, boolean)'
	at net.minecraft.server.level.ServerChunkCache.addRegionTicket(ServerChunkCache.java:429) ~[client-1.18.2-20220404.173914-srg.jar%2386!/:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.level.ServerChunkCache.m_8387_(ServerChunkCache.java:425) ~[client-1.18.2-20220404.173914-srg.jar%2386!/:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.m_129940_(MinecraftServer.java:471) ~[client-1.18.2-20220404.173914-srg.jar%2386!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.m_130006_(MinecraftServer.java:318) ~[client-1.18.2-20220404.173914-srg.jar%2386!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
	at net.minecraft.client.server.IntegratedServer.m_7038_(IntegratedServer.java:84) ~[client-1.18.2-20220404.173914-srg.jar%2386!/:?] {re:classloading,xf:OptiFine:default,re:mixin,xf:OptiFine:default}
	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:661) ~[client-1.18.2-20220404.173914-srg.jar%2386!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.m_177918_(MinecraftServer.java:261) ~[client-1.18.2-20220404.173914-srg.jar%2386!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
	at java.lang.Thread.run(Thread.java:833) [?:?] {}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.18.2
	Minecraft Version ID: 1.18.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 17.0.1, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 546416512 bytes (521 MiB) / 1728053248 bytes (1648 MiB) up to 4294967296 bytes (4096 MiB)
	CPUs: 4
	Processor Vendor: AuthenticAMD
	Processor Name: AMD Ryzen 3 3200G with Radeon Vega Graphics    
	Identifier: AuthenticAMD Family 23 Model 24 Stepping 1
	Microarchitecture: Zen / Zen+
	Frequency (GHz): 3,59
	Number of physical packages: 1
	Number of physical CPUs: 4
	Number of logical CPUs: 4
	Graphics card #0 name: AMD Radeon(TM) Vega 8 Graphics
	Graphics card #0 vendor: Advanced Micro Devices, Inc. (0x1002)
	Graphics card #0 VRAM (MB): 2048,00
	Graphics card #0 deviceId: 0x15d8
	Graphics card #0 versionInfo: DriverVersion=31.0.21921.1000
	Memory slot #0 capacity (MB): 8192,00
	Memory slot #0 clockSpeed (GHz): 2,40
	Memory slot #0 type: Unknown
	Memory slot #1 capacity (MB): 8192,00
	Memory slot #1 clockSpeed (GHz): 2,40
	Memory slot #1 type: Unknown
	Virtual memory max (MB): 28594,93
	Virtual memory used (MB): 15709,88
	Swap memory total (MB): 14336,00
	Swap memory used (MB): 479,55
	JVM Flags: 8 total; -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=16M -Xmx4096m -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump
	Server Running: true
	Player Count: 0 / 8; []
	Data Packs: vanilla, mod:tenshilib, mod:terrablender (incompatible), mod:hardcorezii, mod:biomesoplenty (incompatible), mod:plasmo_voice (incompatible), mod:creativecore (incompatible), mod:jei (incompatible), mod:incontrol (incompatible), mod:car (incompatible), mod:mobsunscreen (incompatible), mod:darkness (incompatible), mod:enhancedvisuals (incompatible), mod:configured (incompatible), mod:zombieawareness (incompatible), mod:backpacked (incompatible), mod:cgm, mod:lostcities (incompatible), mod:badmobs, mod:coroutil (incompatible), mod:minetraps, mod:enhancedcelestials (incompatible), mod:betterf3 (incompatible), mod:framework (incompatible), mod:firstaid (incompatible), mod:cloth_config (incompatible), mod:sound_physics_remastered (incompatible), mod:forge, mod:improvedmobs, mod:biometweaker (incompatible), mod:playerrevive (incompatible), mod:selene (incompatible), mod:supplementaries (incompatible), mod:presencefootsteps (incompatible), Supplementaries Generated Pack
	World Generation: Stable
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'forge'; Server brand changed to 'forge'
	OptiFine Version: OptiFine_1.18.2_HD_U_H7
	OptiFine Build: 20220410-185216
	Render Distance Chunks: 10
	Mipmaps: 1
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 3.2.0 Core Profile Context 24.9.1.240813
	OpenGlRenderer: AMD Radeon(TM) Vega 8 Graphics
	OpenGlVendor: ATI Technologies Inc.
	CpuCount: 4
	ModLauncher: 9.1.3+9.1.3+main.9b69c82a
	ModLauncher launch target: forgeclient
	ModLauncher naming: srg
	ModLauncher services: 
		 mixin PLUGINSERVICE 
		 eventbus PLUGINSERVICE 
		 slf4jfixer PLUGINSERVICE 
		 object_holder_definalize PLUGINSERVICE 
		 runtime_enum_extender PLUGINSERVICE 
		 capability_token_subclass PLUGINSERVICE 
		 accesstransformer PLUGINSERVICE 
		 runtimedistcleaner PLUGINSERVICE 
		 mixin TRANSFORMATIONSERVICE 
		 OptiFine TRANSFORMATIONSERVICE 
		 fml TRANSFORMATIONSERVICE 
	FML Language Providers: 
		minecraft@1.0
		lowcodefml@null
		javafml@null
	Mod List: 
		client-1.18.2-20220404.173914-srg.jar             |Minecraft                     |minecraft                     |1.18.2              |DONE      |Manifest: a1:d4:5e:04:4f:d3:d6:e0:7b:37:97:cf:77:b0:de:ad:4a:47:ce:8c:96:49:5f:0a:cf:8c:ae:b2:6d:4b:8a:3f
		tenshilib-1.18.2-1.6.8-forge.jar                  |TenshiLib                     |tenshilib                     |1.18.2-1.6.8        |DONE      |Manifest: NOSIGNATURE
		TerraBlender-forge-1.18.2-1.1.0.101.jar           |TerraBlender                  |terrablender                  |1.18.2-1.1.0.101    |DONE      |Manifest: NOSIGNATURE
		hardcorez.jar                                     |HardCoreZII                   |hardcorezii                   |1.0.0               |DONE      |Manifest: NOSIGNATURE
		BiomesOPlenty-1.18.2-16.0.0.109-universal.jar     |Biomes O' Plenty              |biomesoplenty                 |1.18.2-16.0.0.109   |DONE      |Manifest: NOSIGNATURE
		plasmovoice-forge-1.18-1.2.16.jar                 |Plasmo Voice                  |plasmo_voice                  |1.2.16              |DONE      |Manifest: NOSIGNATURE
		CreativeCore_FORGE_v2.6.9_mc1.18.2.jar            |CreativeCore                  |creativecore                  |2.6.9               |DONE      |Manifest: NOSIGNATURE
		jei-1.18.2-9.5.5.174.jar                          |Just Enough Items             |jei                           |9.5.5.174           |DONE      |Manifest: NOSIGNATURE
		incontrol-1.18-6.0.9.jar                          |InControl                     |incontrol                     |1.18-6.0.9          |DONE      |Manifest: NOSIGNATURE
		car-1.18.2-1.0.1.jar                              |Ultimate Car Mod              |car                           |1.18.2-1.0.1        |DONE      |Manifest: NOSIGNATURE
		mobsunscreen-1.18.1-3.0.4.jar                     |Mob Sunscreen                 |mobsunscreen                  |1.18.1-3.0.4        |DONE      |Manifest: NOSIGNATURE
		darkness-forge-mc118-2.0.91.jar                   |True Darkness                 |darkness                      |2.0.91              |DONE      |Manifest: NOSIGNATURE
		EnhancedVisuals_FORGE_v1.5.5_mc1.18.2.jar         |EnhancedVisuals               |enhancedvisuals               |1.5.5               |DONE      |Manifest: NOSIGNATURE
		configured-1.5.3-1.18.2.jar                       |Configured                    |configured                    |1.5.3               |DONE      |Manifest: NOSIGNATURE
		zombieawareness-1.18.1-1.12.3.jar                 |Zombie Awareness              |zombieawareness               |1.18.1-1.12.3       |DONE      |Manifest: NOSIGNATURE
		backpacked-2.1.8-1.18.2.jar                       |Backpacked                    |backpacked                    |2.1.8               |DONE      |Manifest: NOSIGNATURE
		cgm-1.2.5-1.18.2.jar                              |MrCrayfish's Gun Mod          |cgm                           |1.2.5               |DONE      |Manifest: NOSIGNATURE
		lostcities-1.18-5.2.1.jar                         |LostCities                    |lostcities                    |1.18-5.2.1          |DONE      |Manifest: NOSIGNATURE
		BadMobs-1.18.2-13.01.jar                          |BadMobs                       |badmobs                       |13.01               |DONE      |Manifest: NOSIGNATURE
		coroutil-1.18.1-1.2.37.jar                        |CoroUtil                      |coroutil                      |1.18.1-1.2.37       |DONE      |Manifest: NOSIGNATURE
		MineTraps-1.18.2-(v.2.1.4).jar                    |MineTraps                     |minetraps                     |2.1.4               |DONE      |Manifest: NOSIGNATURE
		Enhanced_Celestials-forge-1.18.2-2.0.7.jar        |Enhanced Celestials           |enhancedcelestials            |2.0.7               |DONE      |Manifest: NOSIGNATURE
		BetterF3-1.2.5-Forge-1.18.2.jar                   |BetterF3                      |betterf3                      |1.2.5               |DONE      |Manifest: NOSIGNATURE
		framework-0.2.3-1.18.2.jar                        |Framework                     |framework                     |0.2.3               |DONE      |Manifest: NOSIGNATURE
		firstaid-1.11.0.jar                               |First Aid                     |firstaid                      |1.11.0              |DONE      |Manifest: NOSIGNATURE
		cloth-config-6.2.62-forge.jar                     |Cloth Config v4 API           |cloth_config                  |6.2.62              |DONE      |Manifest: NOSIGNATURE
		soundphysics-forge-1.18.2-1.0.6.jar               |Sound Physics Remastered      |sound_physics_remastered      |1.18.2-1.0.6        |DONE      |Manifest: NOSIGNATURE
		forge-1.18.2-40.2.0-universal.jar                 |Forge                         |forge                         |40.2.0              |DONE      |Manifest: 84:ce:76:e8:45:35:e4:0e:63:86:df:47:59:80:0f:67:6c:c1:5f:6e:5f:4d:b3:54:47:1a:9f:7f:ed:5e:f2:90
		improvedmobs-1.18.2-1.10.14-forge.jar             |Improved Mobs Mod             |improvedmobs                  |1.18.2-1.10.14      |DONE      |Manifest: NOSIGNATURE
		biometweaker-1.18.2-4.0.26.jar                    |BiomeTweaker                  |biometweaker                  |1.18.2-4.0.26       |DONE      |Manifest: NOSIGNATURE
		PlayerRevive_FORGE_v2.0.1_mc1.18.2.jar            |PlayerRevive                  |playerrevive                  |2.0.1               |DONE      |Manifest: NOSIGNATURE
		selene-1.18.2-1.17.9.jar                          |Selene                        |selene                        |1.18.2-1.17.9       |DONE      |Manifest: NOSIGNATURE
		supplementaries-1.18.2-1.4.6.jar                  |Supplementaries               |supplementaries               |1.18.2-1.4.6        |DONE      |Manifest: NOSIGNATURE
		PresenceFootsteps-1.18.2-1.5.0-beta1-forge.jar    |Presence Footsteps (Forge)    |presencefootsteps             |1.18.2-1.5.0-beta1  |DONE      |Manifest: NOSIGNATURE
	Crash Report UUID: 9ef7f5cb-5445-4433-8290-9204f440d981
	FML: 40.2
	Forge: net.minecraftforge:40.2.0

**Comment by el-vana** [comment]
nvm solved by my self
