### ISSUE TITLE
LostCities (lostcities) encountered an error during the common_setup event phase  java.lang.IllegalStateException: Not a JSON Object: true

### ISSUE THREAD

**Issue by EMOR30** [McJty/LostCities#665]
---- Minecraft Crash Report ----
// Shall we play a game?

Time: 25/12/24 10:22 PM
Description: Mod loading error has occurred

java.lang.Exception: Mod Loading has failed
	at net.minecraftforge.fml.CrashReportExtender.dumpModLoadingCrashReport(CrashReportExtender.java:85) [?:?] {re:classloading}
	at net.minecraftforge.fml.client.ClientModLoader.completeModLoading(ClientModLoader.java:188) [?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.lambda$null$1(Minecraft.java:508) [?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:tac.mixins.json:client.MinecraftStaticMixin,pl:mixin:APP:modernfix-common.mixins.json:bugfix.concurrency.MinecraftMixin,pl:mixin:APP:modernfix-common.mixins.json:bugfix.world_leaks.MinecraftMixin,pl:mixin:APP:modernfix-common.mixins.json:perf.dedicated_reload_executor.MinecraftMixin,pl:mixin:APP:modernfix-common.mixins.json:feature.measure_time.MinecraftMixin,pl:mixin:APP:modernfix-forge.mixins.json:perf.skip_first_datapack_reload.MinecraftMixin,pl:mixin:APP:modernfix-forge.mixins.json:feature.measure_time.MinecraftMixin_Forge,pl:mixin:APP:memoryleakfix-16.mixins.json:targetEntityLeak.Minecraft_targetClearMixin,pl:mixin:APP:chat_heads.mixins.json:MinecraftMixin,pl:mixin:APP:architectury.mixins.json:MixinMinecraft,pl:mixin:APP:dynamic_fps-common.mixins.json:MinecraftMixin,pl:mixin:APP:betterf3.mixins.json:autof3.AutomaticDebugMixin,pl:mixin:APP:securitycraft.mixins.json:camera.MinecraftMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft$$Lambda$8475/934999594.run(Unknown Source) [?:?] {}
	at net.minecraft.util.Util.func_215077_a(Util.java:320) [?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
	at net.minecraft.client.Minecraft.lambda$new$2(Minecraft.java:504) [?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:tac.mixins.json:client.MinecraftStaticMixin,pl:mixin:APP:modernfix-common.mixins.json:bugfix.concurrency.MinecraftMixin,pl:mixin:APP:modernfix-common.mixins.json:bugfix.world_leaks.MinecraftMixin,pl:mixin:APP:modernfix-common.mixins.json:perf.dedicated_reload_executor.MinecraftMixin,pl:mixin:APP:modernfix-common.mixins.json:feature.measure_time.MinecraftMixin,pl:mixin:APP:modernfix-forge.mixins.json:perf.skip_first_datapack_reload.MinecraftMixin,pl:mixin:APP:modernfix-forge.mixins.json:feature.measure_time.MinecraftMixin_Forge,pl:mixin:APP:memoryleakfix-16.mixins.json:targetEntityLeak.Minecraft_targetClearMixin,pl:mixin:APP:chat_heads.mixins.json:MinecraftMixin,pl:mixin:APP:architectury.mixins.json:MixinMinecraft,pl:mixin:APP:dynamic_fps-common.mixins.json:MinecraftMixin,pl:mixin:APP:betterf3.mixins.json:autof3.AutomaticDebugMixin,pl:mixin:APP:securitycraft.mixins.json:camera.MinecraftMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft$$Lambda$7622/124764410.accept(Unknown Source) [?:?] {}
	at net.minecraft.client.gui.ResourceLoadProgressGui.func_230430_a_(ResourceLoadProgressGui.java:113) [?:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:mixin:APP:dynamic_fps-common.mixins.json:LoadingOverlayMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.GameRenderer.func_195458_a(GameRenderer.java:481) [?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:immersive_aircraft.mixins.json:GameRendererMixin,pl:mixin:APP:tac.mixins.json:client.GameRendererMixin,pl:mixin:APP:dynamic_fps.mixins.json:GameRendererMixin,pl:mixin:APP:dynamic_fps-common.mixins.json:GameRendererMixin,pl:mixin:APP:securitycraft.mixins.json:camera.GameRendererMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:977) [?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:tac.mixins.json:client.MinecraftStaticMixin,pl:mixin:APP:modernfix-common.mixins.json:bugfix.concurrency.MinecraftMixin,pl:mixin:APP:modernfix-common.mixins.json:bugfix.world_leaks.MinecraftMixin,pl:mixin:APP:modernfix-common.mixins.json:perf.dedicated_reload_executor.MinecraftMixin,pl:mixin:APP:modernfix-common.mixins.json:feature.measure_time.MinecraftMixin,pl:mixin:APP:modernfix-forge.mixins.json:perf.skip_first_datapack_reload.MinecraftMixin,pl:mixin:APP:modernfix-forge.mixins.json:feature.measure_time.MinecraftMixin_Forge,pl:mixin:APP:memoryleakfix-16.mixins.json:targetEntityLeak.Minecraft_targetClearMixin,pl:mixin:APP:chat_heads.mixins.json:MinecraftMixin,pl:mixin:APP:architectury.mixins.json:MixinMinecraft,pl:mixin:APP:dynamic_fps-common.mixins.json:MinecraftMixin,pl:mixin:APP:betterf3.mixins.json:autof3.AutomaticDebugMixin,pl:mixin:APP:securitycraft.mixins.json:camera.MinecraftMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:607) [?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:tac.mixins.json:client.MinecraftStaticMixin,pl:mixin:APP:modernfix-common.mixins.json:bugfix.concurrency.MinecraftMixin,pl:mixin:APP:modernfix-common.mixins.json:bugfix.world_leaks.MinecraftMixin,pl:mixin:APP:modernfix-common.mixins.json:perf.dedicated_reload_executor.MinecraftMixin,pl:mixin:APP:modernfix-common.mixins.json:feature.measure_time.MinecraftMixin,pl:mixin:APP:modernfix-forge.mixins.json:perf.skip_first_datapack_reload.MinecraftMixin,pl:mixin:APP:modernfix-forge.mixins.json:feature.measure_time.MinecraftMixin_Forge,pl:mixin:APP:memoryleakfix-16.mixins.json:targetEntityLeak.Minecraft_targetClearMixin,pl:mixin:APP:chat_heads.mixins.json:MinecraftMixin,pl:mixin:APP:architectury.mixins.json:MixinMinecraft,pl:mixin:APP:dynamic_fps-common.mixins.json:MinecraftMixin,pl:mixin:APP:betterf3.mixins.json:autof3.AutomaticDebugMixin,pl:mixin:APP:securitycraft.mixins.json:camera.MinecraftMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:184) [?:?] {re:classloading,pl:runtimedistcleaner:A}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51] {}
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51) [forge-1.16.5-36.2.34.jar:36.2] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$544/1731795367.call(Unknown Source) [forge-1.16.5-36.2.34.jar:36.2] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-8.1.3.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-8.1.3.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-8.1.3.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82) [modlauncher-8.1.3.jar:?] {re:classloading}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) [modlauncher-8.1.3.jar:?] {re:classloading}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at com.google.gson.JsonElement.getAsJsonObject(JsonElement.java:90) ~[gson-2.8.0.jar:?] {}
-- MOD lostcities --
Details:
	Mod File: lostcities-1.16-4.0.12-beta.jar
	Failure message: LostCities (lostcities) encountered an error during the common_setup event phase
		java.lang.IllegalStateException: Not a JSON Object: true
	Mod Version: 1.16-4.0.12-beta
	Mod Issue URL: http://github.com/McJtyMods/LostCities/issues
	Exception message: java.lang.IllegalStateException: Not a JSON Object: true
Stacktrace:
	at com.google.gson.JsonElement.getAsJsonObject(JsonElement.java:90) ~[gson-2.8.0.jar:?] {}
	at mcjty.lostcities.config.Configuration.fromJson(Configuration.java:135) ~[?:1.16-4.0.12-beta] {re:classloading}
	at mcjty.lostcities.config.LostCityProfile.<init>(LostCityProfile.java:225) ~[?:1.16-4.0.12-beta] {re:classloading}
	at mcjty.lostcities.config.LostCityConfiguration.readProfiles(LostCityConfiguration.java:468) ~[?:1.16-4.0.12-beta] {re:classloading}
	at mcjty.lostcities.config.LostCityConfiguration.setupProfiles(LostCityConfiguration.java:458) ~[?:1.16-4.0.12-beta] {re:classloading}
	at mcjty.lostcities.setup.ModSetup.init(ModSetup.java:35) ~[?:1.16-4.0.12-beta] {re:classloading}
	at mcjty.lostcities.LostCities$$Lambda$4869/325387797.accept(Unknown Source) ~[?:?] {}
	at net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:247) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:239) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.eventbus.EventBus$$Lambda$2651/893060889.invoke(Unknown Source) ~[?:?] {}
	at net.minecraftforge.eventbus.EventBus$$Lambda$2827/1426182600.invoke(Unknown Source) ~[?:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.acceptEvent(FMLModContainer.java:120) ~[?:36.2] {re:classloading}
	at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$4(ModContainer.java:121) ~[?:?] {re:mixin,re:classloading}
	at net.minecraftforge.fml.ModContainer$$Lambda$2892/1360273252.run(Unknown Source) ~[?:?] {}
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1618) ~[?:1.8.0_51] {}
	at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1610) ~[?:1.8.0_51] {}
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289) ~[?:1.8.0_51] {}
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056) ~[?:1.8.0_51] {}
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1689) ~[?:1.8.0_51] {re:computing_frames}
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157) ~[?:1.8.0_51] {}

-- System Details --
Details:
	Minecraft Version: 1.16.5
	Minecraft Version ID: 1.16.5
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 337496872 bytes (321 MB) / 1073741824 bytes (1024 MB) up to 4110417920 bytes (3920 MB)
	CPUs: 8
	JVM Flags: 9 total; -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=16M -Xmx3917m -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -XX:+IgnoreUnrecognizedVMOptions
	ModLauncher: 8.1.3+8.1.3+main-8.1.x.c94d18ec
	ModLauncher launch target: fmlclient
	ModLauncher naming: srg
	ModLauncher services: 
		/mixin-0.8.4.jar mixin PLUGINSERVICE 
		/eventbus-4.0.0.jar eventbus PLUGINSERVICE 
		/forge-1.16.5-36.2.34.jar object_holder_definalize PLUGINSERVICE 
		/forge-1.16.5-36.2.34.jar runtime_enum_extender PLUGINSERVICE 
		/accesstransformers-3.0.1.jar accesstransformer PLUGINSERVICE 
		/forge-1.16.5-36.2.34.jar capability_inject_definalize PLUGINSERVICE 
		/forge-1.16.5-36.2.34.jar runtimedistcleaner PLUGINSERVICE 
		/mixin-0.8.4.jar mixin TRANSFORMATIONSERVICE 
		/forge-1.16.5-36.2.34.jar fml TRANSFORMATIONSERVICE 
	FML: 36.2
	Forge: net.minecraftforge:36.2.34
	FML Language Providers: 
		javafml@36.2
		minecraft@1
	Mod List: 
		supermartijn642configlib-1.1.8-forge-mc1.16.jar   |SuperMartijn642's Config Libra|supermartijn642configlib      |1.1.8               |SIDED_SETU|Manifest: NOSIGNATURE
		Cure mod.jar                                      |Cure                          |cure                          |1.0.0               |SIDED_SETU|Manifest: NOSIGNATURE
		incontrol-1.16-5.2.12.jar                         |InControl                     |incontrol                     |1.16-5.2.12         |SIDED_SETU|Manifest: NOSIGNATURE
		immersive_aircraft-0.5.2+1.16.5-forge.jar         |Immersive Aircraft            |immersive_aircraft            |0.5.2+1.16.5        |SIDED_SETU|Manifest: NOSIGNATURE
		tac-release-0.3.14.2-1.16.5.jar                   |Timeless and Classics Guns    |tac                           |0.3.14.2            |SIDED_SETU|Manifest: NOSIGNATURE
		marbledsarsenal-1.16.5-2.1.1.jar                  |Marbled's Arsenal             |marbledsarsenal               |2.1.1               |SIDED_SETU|Manifest: NOSIGNATURE
		configurableextramobdrops_1.16.5-2.5.jar          |Configurable Extra Mob Drops  |configurableextramobdrops     |2.5                 |SIDED_SETU|Manifest: NOSIGNATURE
		EnhancedVisuals_v1.3.32_mc1.16.5.jar              |EnhancedVisuals               |enhancedvisuals               |1.3.0               |SIDED_SETU|Manifest: NOSIGNATURE
		modernfix-forge-5.18.0+mc1.16.5.jar               |ModernFix                     |modernfix                     |5.18.0+mc1.16.5     |SIDED_SETU|Manifest: NOSIGNATURE
		citadel-1.8.1-1.16.5.jar                          |Citadel                       |citadel                       |1.8.1               |SIDED_SETU|Manifest: NOSIGNATURE
		alexsmobs-1.12.1.jar                              |Alex's Mobs                   |alexsmobs                     |1.12.1              |SIDED_SETU|Manifest: NOSIGNATURE
		Horror_elements_mod_1.5.5_1.16.5.jar              |Horror Element Mod            |horror_element_mod            |1.5.5               |SIDED_SETU|Manifest: NOSIGNATURE
		SereneSeasons-1.16.5-4.0.1.130-universal.jar      |Serene Seasons                |sereneseasons                 |1.16.5-4.0.1.130    |SIDED_SETU|Manifest: NOSIGNATURE
		configured-1.5.4-1.16.5.jar                       |Configured                    |configured                    |1.5.4               |SIDED_SETU|Manifest: NOSIGNATURE
		zombieawareness-1.16.5-1.12.jar                   |Zombie Awareness              |zombieawareness               |1.16.5-1.12         |SIDED_SETU|Manifest: NOSIGNATURE
		YungsApi-1.16.4-Forge-13.jar                      |YUNG's API                    |yungsapi                      |1.16.4-Forge-13     |SIDED_SETU|Manifest: NOSIGNATURE
		adrenaline-rush-1.1.jar                           |Adrenaline Rush               |mr_adrenaline_rush            |1.1                 |SIDED_SETU|Manifest: NOSIGNATURE
		Bookshelf-Forge-1.16.5-10.4.33.jar                |Bookshelf                     |bookshelf                     |10.4.33             |SIDED_SETU|Manifest: eb:c4:b1:67:8b:f9:0c:db:dc:4f:01:b1:8e:61:64:39:4c:10:85:0b:a6:c4:c7:48:f0:fa:95:f2:cb:08:3a:e5
		BadMobs-1.16.5-9.1.9.jar                          |BadMobs                       |badmobs                       |9.1.9               |SIDED_SETU|Manifest: eb:c4:b1:67:8b:f9:0c:db:dc:4f:01:b1:8e:61:64:39:4c:10:85:0b:a6:c4:c7:48:f0:fa:95:f2:cb:08:3a:e5
		farsightedmobs-forge-1.16-1.1.jar                 |Farsighted Mobs               |farsightedmobs                |1.1                 |SIDED_SETU|Manifest: NOSIGNATURE
		lazydfu-0.1.3.jar                                 |LazyDFU                       |lazydfu                       |0.1.3               |SIDED_SETU|Manifest: NOSIGNATURE
		Kelka backpack's 1.5 1.16.5.jar                   |Kelka Backpack's              |kelka_backpack                |1.5.0               |SIDED_SETU|Manifest: NOSIGNATURE
		mcw-doors-1.1.1forge-mc1.16.5.jar                 |Macaw's Doors                 |mcwdoors                      |1.1.1               |SIDED_SETU|Manifest: NOSIGNATURE
		The-Hordes-1.16.5-1.1.5c.jar                      |The Hordes                    |hordes                        |1.1.5c              |SIDED_SETU|Manifest: NOSIGNATURE
		fusion-1.1.1-forge-mc1.16.jar                     |Fusion                        |fusion                        |1.1.1               |SIDED_SETU|Manifest: NOSIGNATURE
		FpsReducer-forge-1.24-mc1.16.5.jar                |FPS Reducer                   |fpsreducer                    |1.24-mc1.16.5       |SIDED_SETU|Manifest: NOSIGNATURE
		memoryleakfix-forge-pre1.17-1.1.5.jar             |Memory Leak Fix               |memoryleakfix                 |1.1.5               |SIDED_SETU|Manifest: NOSIGNATURE
		chat_heads-0.6.0-forge-1.16.5.jar                 |Chat Heads                    |chat_heads                    |0.6.0               |SIDED_SETU|Manifest: NOSIGNATURE
		watut-forge-1.16.5-1.0.14.jar                     |What Are They Up To           |watut                         |1.16.5-1.0.14       |SIDED_SETU|Manifest: NOSIGNATURE
		firstaid-1.9.8.jar                                |First Aid                     |firstaid                      |1.9.8               |SIDED_SETU|Manifest: NOSIGNATURE
		forge-1.16.5-36.2.34-universal.jar                |Forge                         |forge                         |36.2.34             |SIDED_SETU|Manifest: 22:af:21:d8:19:82:7f:93:94:fe:2b:ac:b7:e4:41:57:68:39:87:b1:a7:5c:c6:44:f9:25:74:21:14:f5:0d:90
		TravelersTitles-1.16.4-1.5.jar                    |Traveler's Titles             |travelerstitles               |1.16.4-1.5          |SIDED_SETU|Manifest: NOSIGNATURE
		scuba-gear-1.16.5-1.0.3.jar                       |Scuba Gear                    |scuba_gear                    |1.0.3               |SIDED_SETU|Manifest: NOSIGNATURE
		GPUTape-1.16x-1.17x-1.0.2.jar                     |GPUTape                       |gpu_tape                      |1.0.2               |SIDED_SETU|Manifest: NOSIGNATURE
		forge-1.16.5-36.2.34-client.jar                   |Minecraft                     |minecraft                     |1.16.5              |SIDED_SETU|Manifest: NOSIGNATURE
		TenshiLib-1.16.3-1.3.0.jar                        |TenshiLib                     |tenshilib                     |1.16.3-1.3.0        |SIDED_SETU|Manifest: NOSIGNATURE
		FarmersDelight-1.16.5-0.6.0.jar                   |Farmer's Delight              |farmersdelight                |1.16.5-0.6.0        |SIDED_SETU|Manifest: NOSIGNATURE
		voicechat-forge-1.16.5-2.5.26.jar                 |Simple Voice Chat             |voicechat                     |1.16.5-2.5.26       |SIDED_SETU|Manifest: NOSIGNATURE
		EnchantmentDescriptions-1.16.5-7.1.20.jar         |EnchantmentDescriptions       |enchdesc                      |7.1.20              |SIDED_SETU|Manifest: eb:c4:b1:67:8b:f9:0c:db:dc:4f:01:b1:8e:61:64:39:4c:10:85:0b:a6:c4:c7:48:f0:fa:95:f2:cb:08:3a:e5
		AmbientSounds_v3.1.9_mc1.16.5.jar                 |Ambient Sounds                |ambientsounds                 |3.0.3               |SIDED_SETU|Manifest: NOSIGNATURE
		BiomesOPlenty-1.16.5-13.1.0.488-universal.jar     |Biomes O' Plenty              |biomesoplenty                 |1.16.5-13.1.0.488   |SIDED_SETU|Manifest: NOSIGNATURE
		bettersafebed-forge-1.16.5-1.4.jar                |Better Safe Bed               |bettersafebed                 |forge-1.16.5-1.4    |SIDED_SETU|Manifest: NOSIGNATURE
		CreativeCore_v2.2.1_mc1.16.5.jar                  |CreativeCore                  |creativecore                  |2.0.0               |SIDED_SETU|Manifest: NOSIGNATURE
		Chunky-1.2.123.jar                                |Chunky                        |chunky                        |1.2.123             |SIDED_SETU|Manifest: NOSIGNATURE
		mcw-fences-1.1.2-mc1.16.5forge.jar                |Macaw's Fences and Walls      |mcwfences                     |1.1.2               |SIDED_SETU|Manifest: NOSIGNATURE
		supermartijn642corelib-1.1.17a-forge-mc1.16.jar   |SuperMartijn642's Core Lib    |supermartijn642corelib        |1.1.17a             |SIDED_SETU|Manifest: NOSIGNATURE
		movingelevators-1.4.10-forge-mc1.16.jar           |Moving Elevators              |movingelevators               |1.4.10              |SIDED_SETU|Manifest: NOSIGNATURE
		simplylight-1.16.5-1.4.2-build.32.jar             |Simply Light                  |simplylight                   |1.16.5-1.4.2-build.3|SIDED_SETU|Manifest: NOSIGNATURE
		RoughlyEnoughItems-6.5.436.jar                    |Roughly Enough Items (REI)    |roughlyenoughitems            |6.5.436             |SIDED_SETU|Manifest: NOSIGNATURE
		spark-1.9.1-forge.jar                             |spark                         |spark                         |1.9.1               |SIDED_SETU|Manifest: NOSIGNATURE
		realistic-item-drops-2.7DP.jar                    |Realistic Item Drops          |realistic_itemdrops_mr        |2.7DP               |SIDED_SETU|Manifest: NOSIGNATURE
		betterfpsdist-1.2.jar                             |betterfpsdist mod             |betterfpsdist                 |1.2                 |SIDED_SETU|Manifest: NOSIGNATURE
		curios-forge-1.16.5-4.1.0.0.jar                   |Curios API                    |curios                        |1.16.5-4.1.0.0      |SIDED_SETU|Manifest: NOSIGNATURE
		GameStages-Forge-1.16.5-7.3.14.jar                |GameStages                    |gamestages                    |7.3.14              |SIDED_SETU|Manifest: eb:c4:b1:67:8b:f9:0c:db:dc:4f:01:b1:8e:61:64:39:4c:10:85:0b:a6:c4:c7:48:f0:fa:95:f2:cb:08:3a:e5
		lucent-1.16.5-1.0.0.jar                           |Lucent                        |lucent                        |1.0.0               |SIDED_SETU|Manifest: NOSIGNATURE
		diet-forge-1.16.5-1.0.4.1.jar                     |Diet                          |diet                          |1.16.5-1.0.4.1      |SIDED_SETU|Manifest: NOSIGNATURE
		collective-1.16.5-5.49.jar                        |Collective                    |collective                    |5.49                |SIDED_SETU|Manifest: NOSIGNATURE
		mobsunscreen-1.16.4-2.1.3.jar                     |Mob Sunscreen                 |mobsunscreen                  |1.16.4-2.1.3        |SIDED_SETU|Manifest: NOSIGNATURE
		daycounter-1.jar                                  |Day Counter (Original)        |mr_daycounter                 |1                   |SIDED_SETU|Manifest: NOSIGNATURE
		polymorph-forge-1.16.5-0.41.jar                   |Polymorph                     |polymorph                     |1.16.5-0.41         |SIDED_SETU|Manifest: NOSIGNATURE
		[1.16.5] SecurityCraft v1.9.12.jar                |SecurityCraft                 |securitycraft                 |v1.9.12             |SIDED_SETU|Manifest: NOSIGNATURE
		immersive_paintings-0.4.4+1.16.5.jar              |Immersive Paintings           |immersive_paintings           |0.4.4+1.16.5        |SIDED_SETU|Manifest: NOSIGNATURE
		lostcities-1.16-4.0.12-beta.jar                   |LostCities                    |lostcities                    |1.16-4.0.12-beta    |ERROR     |Manifest: NOSIGNATURE
		obfuscate-0.6.3-1.16.5.jar                        |Obfuscate                     |obfuscate                     |0.6.3               |SIDED_SETU|Manifest: NOSIGNATURE
		vehicle-mod-0.45.2-1.16.3.jar                     |MrCrayfish's Vehicle Mod      |vehicle                       |0.45.2              |SIDED_SETU|Manifest: NOSIGNATURE
		zombie_apocalypse_core-1.2.1-forge-1.16.5.jar     |Zombie Apocalypse Core        |zombie_apocalypse_core        |1.2.1               |SIDED_SETU|Manifest: NOSIGNATURE
		Atlas-Lib-1.16.5-1.1.3c.jar                       |Atlas Lib                     |atlaslib                      |1.1.3c              |SIDED_SETU|Manifest: NOSIGNATURE
		coroutil-forge-1.16.5-1.3.6.jar                   |CoroUtil                      |coroutil                      |1.16.5-1.3.6        |SIDED_SETU|Manifest: NOSIGNATURE
		architectury-1.32.68.jar                          |Architectury                  |architectury                  |1.32.68             |SIDED_SETU|Manifest: NOSIGNATURE
		walkietalkie-forge-1.16.5-1.3.1.jar               |Walkie-Talkie                 |walkietalkie                  |1.3.1               |SIDED_SETU|Manifest: NOSIGNATURE
		appleskin-forge-mc1.16.x-2.5.1.jar                |AppleSkin                     |appleskin                     |2.5.1+mc1.16.4      |SIDED_SETU|Manifest: NOSIGNATURE
		lootr-1.16.5-0.2.19.51.jar                        |Lootr                         |lootr                         |0.2.19.51           |SIDED_SETU|Manifest: NOSIGNATURE
		ferritecore-2.1.1-forge.jar                       |Ferrite Core                  |ferritecore                   |2.1.1               |SIDED_SETU|Manifest: 41:ce:50:66:d1:a0:05:ce:a1:0e:02:85:9b:46:64:e0:bf:2e:cf:60:30:9a:fe:0c:27:e0:63:66:9a:84:ce:8a
		cloth-config-4.17.101-forge.jar                   |Cloth Config v4 API           |cloth-config                  |4.17.101            |SIDED_SETU|Manifest: NOSIGNATURE
		More sleeps 1.16.5 - 1.3.jar                      |More Sleeps                   |more_sleeps                   |1.3                 |SIDED_SETU|Manifest: NOSIGNATURE
		dynamic-fps-3.4.3+minecraft-1.16.5-forge.jar      |Dynamic FPS                   |dynamic_fps                   |3.4.3               |SIDED_SETU|Manifest: NOSIGNATURE
		PizzaCraft-1.16.5-3.0.9.jar                       |PizzaCraft                    |pizzacraft                    |3.0.9               |SIDED_SETU|Manifest: NOSIGNATURE
		byg-1.1.6.jar                                     |Oh The Biomes You'll Go       |byg                           |1.1.6               |SIDED_SETU|Manifest: NOSIGNATURE
		BetterF3-1.5.0-Forge-1.16.5.jar                   |BetterF3                      |betterf3                      |1.5.0               |SIDED_SETU|Manifest: NOSIGNATURE
		improvedmobs-1.16.5-1.10.13.jar                   |Improved Mobs Mod             |improvedmobs                  |1.16.5-1.10.13      |SIDED_SETU|Manifest: NOSIGNATURE
		explosiveenhancement-1.0.0.jar                    |Explosive Enhancement         |explosiveenhancement          |1.0.0               |SIDED_SETU|Manifest: NOSIGNATURE
		PlayerRevive_v2.0.0-pre04_mc1.16.5.jar            |PlayerRevive                  |playerrevive                  |2.0.0               |SIDED_SETU|Manifest: NOSIGNATURE
		geckolib-forge-1.16.5-3.0.106.jar                 |GeckoLib                      |geckolib3                     |3.0.106             |SIDED_SETU|Manifest: NOSIGNATURE
	Crash Report UUID: 00529fc8-b4ee-4bb7-a52e-09556a3be736

**Comment by McJty** [comment]
Delete the Lost Cities config files

**Comment by EMOR30** [comment]
It works now, thank you very much
