### ISSUE TITLE
NPE during worldgen creating mod structures in sky profiles

### ISSUE THREAD

**Issue by CplPibald** [McJty/LostCities#93]
Custom modpack using lostcities-1.12-2.0.1
Create new SSP world using "floating", "space", or "waterbubbles" profile.
Screen hangs indefinitely at "Generating terrain".  Console shows a crash.

Crash report shows NPE in LostCityChunkGenerator trying to create an Astral Sorcery treasure shrine.

```
java.lang.NullPointerException: Exception in server tick loop
	at net.minecraft.world.gen.structure.MapGenStronghold.func_189104_c(MapGenStronghold.java:141)
	at net.minecraft.world.gen.structure.MapGenStronghold.func_180706_b(MapGenStronghold.java:77)
	at mcjty.lostcities.dimensions.world.LostCityChunkGenerator.func_180513_a(LostCityChunkGenerator.java:656)
	at net.minecraft.world.gen.ChunkProviderServer.func_180513_a(ChunkProviderServer.java:307)
	at hellfirepvp.astralsorcery.common.world.structure.StructureTreasureShrine.getGenerationPosition(StructureTreasureShrine.java:85)
	at hellfirepvp.astralsorcery.common.world.WorldGenAttributeCommon.generate(WorldGenAttributeCommon.java:57)
	at hellfirepvp.astralsorcery.common.world.structure.WorldGenAttributeStructure.generate(WorldGenAttributeStructure.java:69)
	at hellfirepvp.astralsorcery.common.world.AstralWorldGenerator.generateWithLastKnownVersion(AstralWorldGenerator.java:107)
	at hellfirepvp.astralsorcery.common.world.AstralWorldGenerator.generate(AstralWorldGenerator.java:85)
	at net.minecraftforge.fml.common.registry.GameRegistry.generateWorld(GameRegistry.java:167)

```

Full crash report: https://pastebin.com/NL1TCm2Y

Worldgen succeeds in the "default" profile using lostcities 2.0.1, as well as all profiles using lostcities 1.0.2

**Comment by josephcsible** [comment]
Can you try with a vanilla (non-Lost Cities) customized world with strongholds disabled, and see if you get a similar crash then?

**Comment by CplPibald** [comment]
Yep, that was the problem.  Looks like this is fixed as https://github.com/HellFirePvP/AstralSorcery/issues/358 which I somehow missed when I was looking for the issue the first time.  My apologies for the spurious bug report.  :(

Cheers,
-CplPibald
